import 'package:flutter/cupertino.dart';

/*

To generate update the list run:

sh ci/generate_cupertino_icons_dart.sh

*/

Map<String, IconData> cupertinoIcons = {
  "cupertino_left_chevron": CupertinoIcons.left_chevron,
  "cupertino_right_chevron": CupertinoIcons.right_chevron,
  "cupertino_share": CupertinoIcons.share,
  "cupertino_share_solid": CupertinoIcons.share_solid,
  "cupertino_book": CupertinoIcons.book,
  "cupertino_book_solid": CupertinoIcons.book_solid,
  "cupertino_bookmark": CupertinoIcons.bookmark,
  "cupertino_bookmark_solid": CupertinoIcons.bookmark_solid,
  "cupertino_info": CupertinoIcons.info,
  "cupertino_reply": CupertinoIcons.reply,
  "cupertino_conversation_bubble": CupertinoIcons.conversation_bubble,
  "cupertino_profile_circled": CupertinoIcons.profile_circled,
  "cupertino_plus_circled": CupertinoIcons.plus_circled,
  "cupertino_minus_circled": CupertinoIcons.minus_circled,
  "cupertino_flag": CupertinoIcons.flag,
  "cupertino_search": CupertinoIcons.search,
  "cupertino_check_mark": CupertinoIcons.check_mark,
  "cupertino_check_mark_circled": CupertinoIcons.check_mark_circled,
  "cupertino_check_mark_circled_solid": CupertinoIcons.check_mark_circled_solid,
  "cupertino_circle": CupertinoIcons.circle,
  "cupertino_circle_filled": CupertinoIcons.circle_filled,
  "cupertino_back": CupertinoIcons.back,
  "cupertino_forward": CupertinoIcons.forward,
  "cupertino_home": CupertinoIcons.home,
  "cupertino_shopping_cart": CupertinoIcons.shopping_cart,
  "cupertino_ellipsis": CupertinoIcons.ellipsis,
  "cupertino_phone": CupertinoIcons.phone,
  "cupertino_phone_solid": CupertinoIcons.phone_solid,
  "cupertino_down_arrow": CupertinoIcons.down_arrow,
  "cupertino_up_arrow": CupertinoIcons.up_arrow,
  "cupertino_battery_charging": CupertinoIcons.battery_charging,
  "cupertino_battery_empty": CupertinoIcons.battery_empty,
  "cupertino_battery_full": CupertinoIcons.battery_full,
  "cupertino_battery_75_percent": CupertinoIcons.battery_75_percent,
  "cupertino_battery_25_percent": CupertinoIcons.battery_25_percent,
  "cupertino_bluetooth": CupertinoIcons.bluetooth,
  "cupertino_restart": CupertinoIcons.restart,
  "cupertino_reply_all": CupertinoIcons.reply_all,
  "cupertino_reply_thick_solid": CupertinoIcons.reply_thick_solid,
  "cupertino_share_up": CupertinoIcons.share_up,
  "cupertino_shuffle": CupertinoIcons.shuffle,
  "cupertino_shuffle_medium": CupertinoIcons.shuffle_medium,
  "cupertino_shuffle_thick": CupertinoIcons.shuffle_thick,
  "cupertino_photo_camera": CupertinoIcons.photo_camera,
  "cupertino_photo_camera_solid": CupertinoIcons.photo_camera_solid,
  "cupertino_video_camera": CupertinoIcons.video_camera,
  "cupertino_video_camera_solid": CupertinoIcons.video_camera_solid,
  "cupertino_switch_camera": CupertinoIcons.switch_camera,
  "cupertino_switch_camera_solid": CupertinoIcons.switch_camera_solid,
  "cupertino_collections": CupertinoIcons.collections,
  "cupertino_collections_solid": CupertinoIcons.collections_solid,
  "cupertino_folder": CupertinoIcons.folder,
  "cupertino_folder_solid": CupertinoIcons.folder_solid,
  "cupertino_folder_open": CupertinoIcons.folder_open,
  "cupertino_delete": CupertinoIcons.delete,
  "cupertino_delete_solid": CupertinoIcons.delete_solid,
  "cupertino_delete_simple": CupertinoIcons.delete_simple,
  "cupertino_pen": CupertinoIcons.pen,
  "cupertino_pencil": CupertinoIcons.pencil,
  "cupertino_create": CupertinoIcons.create,
  "cupertino_create_solid": CupertinoIcons.create_solid,
  "cupertino_refresh": CupertinoIcons.refresh,
  "cupertino_refresh_circled": CupertinoIcons.refresh_circled,
  "cupertino_refresh_circled_solid": CupertinoIcons.refresh_circled_solid,
  "cupertino_refresh_thin": CupertinoIcons.refresh_thin,
  "cupertino_refresh_thick": CupertinoIcons.refresh_thick,
  "cupertino_refresh_bold": CupertinoIcons.refresh_bold,
  "cupertino_clear_thick": CupertinoIcons.clear_thick,
  "cupertino_clear_thick_circled": CupertinoIcons.clear_thick_circled,
  "cupertino_clear": CupertinoIcons.clear,
  "cupertino_clear_circled": CupertinoIcons.clear_circled,
  "cupertino_clear_circled_solid": CupertinoIcons.clear_circled_solid,
  "cupertino_add": CupertinoIcons.add,
  "cupertino_add_circled": CupertinoIcons.add_circled,
  "cupertino_add_circled_solid": CupertinoIcons.add_circled_solid,
  "cupertino_gear": CupertinoIcons.gear,
  "cupertino_gear_solid": CupertinoIcons.gear_solid,
  "cupertino_gear_big": CupertinoIcons.gear_big,
  "cupertino_settings": CupertinoIcons.settings,
  "cupertino_settings_solid": CupertinoIcons.settings_solid,
  "cupertino_music_note": CupertinoIcons.music_note,
  "cupertino_double_music_note": CupertinoIcons.double_music_note,
  "cupertino_play_arrow": CupertinoIcons.play_arrow,
  "cupertino_play_arrow_solid": CupertinoIcons.play_arrow_solid,
  "cupertino_pause": CupertinoIcons.pause,
  "cupertino_pause_solid": CupertinoIcons.pause_solid,
  "cupertino_loop": CupertinoIcons.loop,
  "cupertino_loop_thick": CupertinoIcons.loop_thick,
  "cupertino_volume_down": CupertinoIcons.volume_down,
  "cupertino_volume_mute": CupertinoIcons.volume_mute,
  "cupertino_volume_off": CupertinoIcons.volume_off,
  "cupertino_volume_up": CupertinoIcons.volume_up,
  "cupertino_fullscreen": CupertinoIcons.fullscreen,
  "cupertino_fullscreen_exit": CupertinoIcons.fullscreen_exit,
  "cupertino_mic_off": CupertinoIcons.mic_off,
  "cupertino_mic": CupertinoIcons.mic,
  "cupertino_mic_solid": CupertinoIcons.mic_solid,
  "cupertino_clock": CupertinoIcons.clock,
  "cupertino_clock_solid": CupertinoIcons.clock_solid,
  "cupertino_time": CupertinoIcons.time,
  "cupertino_time_solid": CupertinoIcons.time_solid,
  "cupertino_padlock": CupertinoIcons.padlock,
  "cupertino_padlock_solid": CupertinoIcons.padlock_solid,
  "cupertino_eye": CupertinoIcons.eye,
  "cupertino_eye_solid": CupertinoIcons.eye_solid,
  "cupertino_person": CupertinoIcons.person,
  "cupertino_person_solid": CupertinoIcons.person_solid,
  "cupertino_person_add": CupertinoIcons.person_add,
  "cupertino_person_add_solid": CupertinoIcons.person_add_solid,
  "cupertino_group": CupertinoIcons.group,
  "cupertino_group_solid": CupertinoIcons.group_solid,
  "cupertino_mail": CupertinoIcons.mail,
  "cupertino_mail_solid": CupertinoIcons.mail_solid,
  "cupertino_location": CupertinoIcons.location,
  "cupertino_location_solid": CupertinoIcons.location_solid,
  "cupertino_tag": CupertinoIcons.tag,
  "cupertino_tag_solid": CupertinoIcons.tag_solid,
  "cupertino_tags": CupertinoIcons.tags,
  "cupertino_tags_solid": CupertinoIcons.tags_solid,
  "cupertino_bus": CupertinoIcons.bus,
  "cupertino_car": CupertinoIcons.car,
  "cupertino_car_detailed": CupertinoIcons.car_detailed,
  "cupertino_train_style_one": CupertinoIcons.train_style_one,
  "cupertino_train_style_two": CupertinoIcons.train_style_two,
  "cupertino_paw": CupertinoIcons.paw,
  "cupertino_paw_solid": CupertinoIcons.paw_solid,
  "cupertino_game_controller": CupertinoIcons.game_controller,
  "cupertino_game_controller_solid": CupertinoIcons.game_controller_solid,
  "cupertino_lab_flask": CupertinoIcons.lab_flask,
  "cupertino_lab_flask_solid": CupertinoIcons.lab_flask_solid,
  "cupertino_heart": CupertinoIcons.heart,
  "cupertino_heart_solid": CupertinoIcons.heart_solid,
  "cupertino_bell": CupertinoIcons.bell,
  "cupertino_bell_solid": CupertinoIcons.bell_solid,
  "cupertino_news": CupertinoIcons.news,
  "cupertino_news_solid": CupertinoIcons.news_solid,
  "cupertino_brightness": CupertinoIcons.brightness,
  "cupertino_brightness_solid": CupertinoIcons.brightness_solid,
  "cupertino_airplane": CupertinoIcons.airplane,
  "cupertino_alarm": CupertinoIcons.alarm,
  "cupertino_alarm_fill": CupertinoIcons.alarm_fill,
  "cupertino_alt": CupertinoIcons.alt,
  "cupertino_ant": CupertinoIcons.ant,
  "cupertino_ant_circle": CupertinoIcons.ant_circle,
  "cupertino_ant_circle_fill": CupertinoIcons.ant_circle_fill,
  "cupertino_ant_fill": CupertinoIcons.ant_fill,
  "cupertino_antenna_radiowaves_left_right":
      CupertinoIcons.antenna_radiowaves_left_right,
  "cupertino_app": CupertinoIcons.app,
  "cupertino_app_badge": CupertinoIcons.app_badge,
  "cupertino_app_badge_fill": CupertinoIcons.app_badge_fill,
  "cupertino_app_fill": CupertinoIcons.app_fill,
  "cupertino_archivebox": CupertinoIcons.archivebox,
  "cupertino_archivebox_fill": CupertinoIcons.archivebox_fill,
  "cupertino_arrow_2_circlepath": CupertinoIcons.arrow_2_circlepath,
  "cupertino_arrow_2_circlepath_circle":
      CupertinoIcons.arrow_2_circlepath_circle,
  "cupertino_arrow_2_circlepath_circle_fill":
      CupertinoIcons.arrow_2_circlepath_circle_fill,
  "cupertino_arrow_2_squarepath": CupertinoIcons.arrow_2_squarepath,
  "cupertino_arrow_3_trianglepath": CupertinoIcons.arrow_3_trianglepath,
  "cupertino_arrow_branch": CupertinoIcons.arrow_branch,
  "cupertino_arrow_clockwise": CupertinoIcons.arrow_clockwise,
  "cupertino_arrow_clockwise_circle": CupertinoIcons.arrow_clockwise_circle,
  "cupertino_arrow_clockwise_circle_fill":
      CupertinoIcons.arrow_clockwise_circle_fill,
  "cupertino_arrow_counterclockwise": CupertinoIcons.arrow_counterclockwise,
  "cupertino_arrow_counterclockwise_circle":
      CupertinoIcons.arrow_counterclockwise_circle,
  "cupertino_arrow_counterclockwise_circle_fill":
      CupertinoIcons.arrow_counterclockwise_circle_fill,
  "cupertino_arrow_down": CupertinoIcons.arrow_down,
  "cupertino_arrow_down_circle": CupertinoIcons.arrow_down_circle,
  "cupertino_arrow_down_circle_fill": CupertinoIcons.arrow_down_circle_fill,
  "cupertino_arrow_down_doc": CupertinoIcons.arrow_down_doc,
  "cupertino_arrow_down_doc_fill": CupertinoIcons.arrow_down_doc_fill,
  "cupertino_arrow_down_left": CupertinoIcons.arrow_down_left,
  "cupertino_arrow_down_left_circle": CupertinoIcons.arrow_down_left_circle,
  "cupertino_arrow_down_left_circle_fill":
      CupertinoIcons.arrow_down_left_circle_fill,
  "cupertino_arrow_down_left_square": CupertinoIcons.arrow_down_left_square,
  "cupertino_arrow_down_left_square_fill":
      CupertinoIcons.arrow_down_left_square_fill,
  "cupertino_arrow_down_right": CupertinoIcons.arrow_down_right,
  "cupertino_arrow_down_right_arrow_up_left":
      CupertinoIcons.arrow_down_right_arrow_up_left,
  "cupertino_arrow_down_right_circle": CupertinoIcons.arrow_down_right_circle,
  "cupertino_arrow_down_right_circle_fill":
      CupertinoIcons.arrow_down_right_circle_fill,
  "cupertino_arrow_down_right_square": CupertinoIcons.arrow_down_right_square,
  "cupertino_arrow_down_right_square_fill":
      CupertinoIcons.arrow_down_right_square_fill,
  "cupertino_arrow_down_square": CupertinoIcons.arrow_down_square,
  "cupertino_arrow_down_square_fill": CupertinoIcons.arrow_down_square_fill,
  "cupertino_arrow_down_to_line": CupertinoIcons.arrow_down_to_line,
  "cupertino_arrow_down_to_line_alt": CupertinoIcons.arrow_down_to_line_alt,
  "cupertino_arrow_left": CupertinoIcons.arrow_left,
  "cupertino_arrow_left_circle": CupertinoIcons.arrow_left_circle,
  "cupertino_arrow_left_circle_fill": CupertinoIcons.arrow_left_circle_fill,
  "cupertino_arrow_left_right": CupertinoIcons.arrow_left_right,
  "cupertino_arrow_left_right_circle": CupertinoIcons.arrow_left_right_circle,
  "cupertino_arrow_left_right_circle_fill":
      CupertinoIcons.arrow_left_right_circle_fill,
  "cupertino_arrow_left_right_square": CupertinoIcons.arrow_left_right_square,
  "cupertino_arrow_left_right_square_fill":
      CupertinoIcons.arrow_left_right_square_fill,
  "cupertino_arrow_left_square": CupertinoIcons.arrow_left_square,
  "cupertino_arrow_left_square_fill": CupertinoIcons.arrow_left_square_fill,
  "cupertino_arrow_left_to_line": CupertinoIcons.arrow_left_to_line,
  "cupertino_arrow_left_to_line_alt": CupertinoIcons.arrow_left_to_line_alt,
  "cupertino_arrow_merge": CupertinoIcons.arrow_merge,
  "cupertino_arrow_right": CupertinoIcons.arrow_right,
  "cupertino_arrow_right_arrow_left": CupertinoIcons.arrow_right_arrow_left,
  "cupertino_arrow_right_arrow_left_circle":
      CupertinoIcons.arrow_right_arrow_left_circle,
  "cupertino_arrow_right_arrow_left_circle_fill":
      CupertinoIcons.arrow_right_arrow_left_circle_fill,
  "cupertino_arrow_right_arrow_left_square":
      CupertinoIcons.arrow_right_arrow_left_square,
  "cupertino_arrow_right_arrow_left_square_fill":
      CupertinoIcons.arrow_right_arrow_left_square_fill,
  "cupertino_arrow_right_circle": CupertinoIcons.arrow_right_circle,
  "cupertino_arrow_right_circle_fill": CupertinoIcons.arrow_right_circle_fill,
  "cupertino_arrow_right_square": CupertinoIcons.arrow_right_square,
  "cupertino_arrow_right_square_fill": CupertinoIcons.arrow_right_square_fill,
  "cupertino_arrow_right_to_line": CupertinoIcons.arrow_right_to_line,
  "cupertino_arrow_right_to_line_alt": CupertinoIcons.arrow_right_to_line_alt,
  "cupertino_arrow_swap": CupertinoIcons.arrow_swap,
  "cupertino_arrow_turn_down_left": CupertinoIcons.arrow_turn_down_left,
  "cupertino_arrow_turn_down_right": CupertinoIcons.arrow_turn_down_right,
  "cupertino_arrow_turn_left_down": CupertinoIcons.arrow_turn_left_down,
  "cupertino_arrow_turn_left_up": CupertinoIcons.arrow_turn_left_up,
  "cupertino_arrow_turn_right_down": CupertinoIcons.arrow_turn_right_down,
  "cupertino_arrow_turn_right_up": CupertinoIcons.arrow_turn_right_up,
  "cupertino_arrow_turn_up_left": CupertinoIcons.arrow_turn_up_left,
  "cupertino_arrow_turn_up_right": CupertinoIcons.arrow_turn_up_right,
  "cupertino_arrow_up": CupertinoIcons.arrow_up,
  "cupertino_arrow_up_arrow_down": CupertinoIcons.arrow_up_arrow_down,
  "cupertino_arrow_up_arrow_down_circle":
      CupertinoIcons.arrow_up_arrow_down_circle,
  "cupertino_arrow_up_arrow_down_circle_fill":
      CupertinoIcons.arrow_up_arrow_down_circle_fill,
  "cupertino_arrow_up_arrow_down_square":
      CupertinoIcons.arrow_up_arrow_down_square,
  "cupertino_arrow_up_arrow_down_square_fill":
      CupertinoIcons.arrow_up_arrow_down_square_fill,
  "cupertino_arrow_up_bin": CupertinoIcons.arrow_up_bin,
  "cupertino_arrow_up_bin_fill": CupertinoIcons.arrow_up_bin_fill,
  "cupertino_arrow_up_circle": CupertinoIcons.arrow_up_circle,
  "cupertino_arrow_up_circle_fill": CupertinoIcons.arrow_up_circle_fill,
  "cupertino_arrow_up_doc": CupertinoIcons.arrow_up_doc,
  "cupertino_arrow_up_doc_fill": CupertinoIcons.arrow_up_doc_fill,
  "cupertino_arrow_up_down": CupertinoIcons.arrow_up_down,
  "cupertino_arrow_up_down_circle": CupertinoIcons.arrow_up_down_circle,
  "cupertino_arrow_up_down_circle_fill":
      CupertinoIcons.arrow_up_down_circle_fill,
  "cupertino_arrow_up_down_square": CupertinoIcons.arrow_up_down_square,
  "cupertino_arrow_up_down_square_fill":
      CupertinoIcons.arrow_up_down_square_fill,
  "cupertino_arrow_up_left": CupertinoIcons.arrow_up_left,
  "cupertino_arrow_up_left_arrow_down_right":
      CupertinoIcons.arrow_up_left_arrow_down_right,
  "cupertino_arrow_up_left_circle": CupertinoIcons.arrow_up_left_circle,
  "cupertino_arrow_up_left_circle_fill":
      CupertinoIcons.arrow_up_left_circle_fill,
  "cupertino_arrow_up_left_square": CupertinoIcons.arrow_up_left_square,
  "cupertino_arrow_up_left_square_fill":
      CupertinoIcons.arrow_up_left_square_fill,
  "cupertino_arrow_up_right": CupertinoIcons.arrow_up_right,
  "cupertino_arrow_up_right_circle": CupertinoIcons.arrow_up_right_circle,
  "cupertino_arrow_up_right_circle_fill":
      CupertinoIcons.arrow_up_right_circle_fill,
  "cupertino_arrow_up_right_diamond": CupertinoIcons.arrow_up_right_diamond,
  "cupertino_arrow_up_right_diamond_fill":
      CupertinoIcons.arrow_up_right_diamond_fill,
  "cupertino_arrow_up_right_square": CupertinoIcons.arrow_up_right_square,
  "cupertino_arrow_up_right_square_fill":
      CupertinoIcons.arrow_up_right_square_fill,
  "cupertino_arrow_up_square": CupertinoIcons.arrow_up_square,
  "cupertino_arrow_up_square_fill": CupertinoIcons.arrow_up_square_fill,
  "cupertino_arrow_up_to_line": CupertinoIcons.arrow_up_to_line,
  "cupertino_arrow_up_to_line_alt": CupertinoIcons.arrow_up_to_line_alt,
  "cupertino_arrow_uturn_down": CupertinoIcons.arrow_uturn_down,
  "cupertino_arrow_uturn_down_circle": CupertinoIcons.arrow_uturn_down_circle,
  "cupertino_arrow_uturn_down_circle_fill":
      CupertinoIcons.arrow_uturn_down_circle_fill,
  "cupertino_arrow_uturn_down_square": CupertinoIcons.arrow_uturn_down_square,
  "cupertino_arrow_uturn_down_square_fill":
      CupertinoIcons.arrow_uturn_down_square_fill,
  "cupertino_arrow_uturn_left": CupertinoIcons.arrow_uturn_left,
  "cupertino_arrow_uturn_left_circle": CupertinoIcons.arrow_uturn_left_circle,
  "cupertino_arrow_uturn_left_circle_fill":
      CupertinoIcons.arrow_uturn_left_circle_fill,
  "cupertino_arrow_uturn_left_square": CupertinoIcons.arrow_uturn_left_square,
  "cupertino_arrow_uturn_left_square_fill":
      CupertinoIcons.arrow_uturn_left_square_fill,
  "cupertino_arrow_uturn_right": CupertinoIcons.arrow_uturn_right,
  "cupertino_arrow_uturn_right_circle": CupertinoIcons.arrow_uturn_right_circle,
  "cupertino_arrow_uturn_right_circle_fill":
      CupertinoIcons.arrow_uturn_right_circle_fill,
  "cupertino_arrow_uturn_right_square": CupertinoIcons.arrow_uturn_right_square,
  "cupertino_arrow_uturn_right_square_fill":
      CupertinoIcons.arrow_uturn_right_square_fill,
  "cupertino_arrow_uturn_up": CupertinoIcons.arrow_uturn_up,
  "cupertino_arrow_uturn_up_circle": CupertinoIcons.arrow_uturn_up_circle,
  "cupertino_arrow_uturn_up_circle_fill":
      CupertinoIcons.arrow_uturn_up_circle_fill,
  "cupertino_arrow_uturn_up_square": CupertinoIcons.arrow_uturn_up_square,
  "cupertino_arrow_uturn_up_square_fill":
      CupertinoIcons.arrow_uturn_up_square_fill,
  "cupertino_arrowshape_turn_up_left": CupertinoIcons.arrowshape_turn_up_left,
  "cupertino_arrowshape_turn_up_left_2":
      CupertinoIcons.arrowshape_turn_up_left_2,
  "cupertino_arrowshape_turn_up_left_2_fill":
      CupertinoIcons.arrowshape_turn_up_left_2_fill,
  "cupertino_arrowshape_turn_up_left_circle":
      CupertinoIcons.arrowshape_turn_up_left_circle,
  "cupertino_arrowshape_turn_up_left_circle_fill":
      CupertinoIcons.arrowshape_turn_up_left_circle_fill,
  "cupertino_arrowshape_turn_up_left_fill":
      CupertinoIcons.arrowshape_turn_up_left_fill,
  "cupertino_arrowshape_turn_up_right": CupertinoIcons.arrowshape_turn_up_right,
  "cupertino_arrowshape_turn_up_right_circle":
      CupertinoIcons.arrowshape_turn_up_right_circle,
  "cupertino_arrowshape_turn_up_right_circle_fill":
      CupertinoIcons.arrowshape_turn_up_right_circle_fill,
  "cupertino_arrowshape_turn_up_right_fill":
      CupertinoIcons.arrowshape_turn_up_right_fill,
  "cupertino_arrowtriangle_down": CupertinoIcons.arrowtriangle_down,
  "cupertino_arrowtriangle_down_circle":
      CupertinoIcons.arrowtriangle_down_circle,
  "cupertino_arrowtriangle_down_circle_fill":
      CupertinoIcons.arrowtriangle_down_circle_fill,
  "cupertino_arrowtriangle_down_fill": CupertinoIcons.arrowtriangle_down_fill,
  "cupertino_arrowtriangle_down_square":
      CupertinoIcons.arrowtriangle_down_square,
  "cupertino_arrowtriangle_down_square_fill":
      CupertinoIcons.arrowtriangle_down_square_fill,
  "cupertino_arrowtriangle_left": CupertinoIcons.arrowtriangle_left,
  "cupertino_arrowtriangle_left_circle":
      CupertinoIcons.arrowtriangle_left_circle,
  "cupertino_arrowtriangle_left_circle_fill":
      CupertinoIcons.arrowtriangle_left_circle_fill,
  "cupertino_arrowtriangle_left_fill": CupertinoIcons.arrowtriangle_left_fill,
  "cupertino_arrowtriangle_left_square":
      CupertinoIcons.arrowtriangle_left_square,
  "cupertino_arrowtriangle_left_square_fill":
      CupertinoIcons.arrowtriangle_left_square_fill,
  "cupertino_arrowtriangle_right": CupertinoIcons.arrowtriangle_right,
  "cupertino_arrowtriangle_right_circle":
      CupertinoIcons.arrowtriangle_right_circle,
  "cupertino_arrowtriangle_right_circle_fill":
      CupertinoIcons.arrowtriangle_right_circle_fill,
  "cupertino_arrowtriangle_right_fill": CupertinoIcons.arrowtriangle_right_fill,
  "cupertino_arrowtriangle_right_square":
      CupertinoIcons.arrowtriangle_right_square,
  "cupertino_arrowtriangle_right_square_fill":
      CupertinoIcons.arrowtriangle_right_square_fill,
  "cupertino_arrowtriangle_up": CupertinoIcons.arrowtriangle_up,
  "cupertino_arrowtriangle_up_circle": CupertinoIcons.arrowtriangle_up_circle,
  "cupertino_arrowtriangle_up_circle_fill":
      CupertinoIcons.arrowtriangle_up_circle_fill,
  "cupertino_arrowtriangle_up_fill": CupertinoIcons.arrowtriangle_up_fill,
  "cupertino_arrowtriangle_up_square": CupertinoIcons.arrowtriangle_up_square,
  "cupertino_arrowtriangle_up_square_fill":
      CupertinoIcons.arrowtriangle_up_square_fill,
  "cupertino_asterisk_circle": CupertinoIcons.asterisk_circle,
  "cupertino_asterisk_circle_fill": CupertinoIcons.asterisk_circle_fill,
  "cupertino_at": CupertinoIcons.at,
  "cupertino_at_badge_minus": CupertinoIcons.at_badge_minus,
  "cupertino_at_badge_plus": CupertinoIcons.at_badge_plus,
  "cupertino_at_circle": CupertinoIcons.at_circle,
  "cupertino_at_circle_fill": CupertinoIcons.at_circle_fill,
  "cupertino_backward": CupertinoIcons.backward,
  "cupertino_backward_end": CupertinoIcons.backward_end,
  "cupertino_backward_end_alt": CupertinoIcons.backward_end_alt,
  "cupertino_backward_end_alt_fill": CupertinoIcons.backward_end_alt_fill,
  "cupertino_backward_end_fill": CupertinoIcons.backward_end_fill,
  "cupertino_backward_fill": CupertinoIcons.backward_fill,
  "cupertino_badge_plus_radiowaves_right":
      CupertinoIcons.badge_plus_radiowaves_right,
  "cupertino_bag": CupertinoIcons.bag,
  "cupertino_bag_badge_minus": CupertinoIcons.bag_badge_minus,
  "cupertino_bag_badge_plus": CupertinoIcons.bag_badge_plus,
  "cupertino_bag_fill": CupertinoIcons.bag_fill,
  "cupertino_bag_fill_badge_minus": CupertinoIcons.bag_fill_badge_minus,
  "cupertino_bag_fill_badge_plus": CupertinoIcons.bag_fill_badge_plus,
  "cupertino_bandage": CupertinoIcons.bandage,
  "cupertino_bandage_fill": CupertinoIcons.bandage_fill,
  "cupertino_barcode": CupertinoIcons.barcode,
  "cupertino_barcode_viewfinder": CupertinoIcons.barcode_viewfinder,
  "cupertino_bars": CupertinoIcons.bars,
  "cupertino_battery_0": CupertinoIcons.battery_0,
  "cupertino_battery_100": CupertinoIcons.battery_100,
  "cupertino_battery_25": CupertinoIcons.battery_25,
  "cupertino_bed_double": CupertinoIcons.bed_double,
  "cupertino_bed_double_fill": CupertinoIcons.bed_double_fill,
  "cupertino_bell_circle": CupertinoIcons.bell_circle,
  "cupertino_bell_circle_fill": CupertinoIcons.bell_circle_fill,
  "cupertino_bell_fill": CupertinoIcons.bell_fill,
  "cupertino_bell_slash": CupertinoIcons.bell_slash,
  "cupertino_bell_slash_fill": CupertinoIcons.bell_slash_fill,
  "cupertino_bin_xmark": CupertinoIcons.bin_xmark,
  "cupertino_bin_xmark_fill": CupertinoIcons.bin_xmark_fill,
  "cupertino_bitcoin": CupertinoIcons.bitcoin,
  "cupertino_bitcoin_circle": CupertinoIcons.bitcoin_circle,
  "cupertino_bitcoin_circle_fill": CupertinoIcons.bitcoin_circle_fill,
  "cupertino_bold": CupertinoIcons.bold,
  "cupertino_bold_italic_underline": CupertinoIcons.bold_italic_underline,
  "cupertino_bold_underline": CupertinoIcons.bold_underline,
  "cupertino_bolt": CupertinoIcons.bolt,
  "cupertino_bolt_badge_a": CupertinoIcons.bolt_badge_a,
  "cupertino_bolt_badge_a_fill": CupertinoIcons.bolt_badge_a_fill,
  "cupertino_bolt_circle": CupertinoIcons.bolt_circle,
  "cupertino_bolt_circle_fill": CupertinoIcons.bolt_circle_fill,
  "cupertino_bolt_fill": CupertinoIcons.bolt_fill,
  "cupertino_bolt_horizontal": CupertinoIcons.bolt_horizontal,
  "cupertino_bolt_horizontal_circle": CupertinoIcons.bolt_horizontal_circle,
  "cupertino_bolt_horizontal_circle_fill":
      CupertinoIcons.bolt_horizontal_circle_fill,
  "cupertino_bolt_horizontal_fill": CupertinoIcons.bolt_horizontal_fill,
  "cupertino_bolt_slash": CupertinoIcons.bolt_slash,
  "cupertino_bolt_slash_fill": CupertinoIcons.bolt_slash_fill,
  "cupertino_book_circle": CupertinoIcons.book_circle,
  "cupertino_book_circle_fill": CupertinoIcons.book_circle_fill,
  "cupertino_book_fill": CupertinoIcons.book_fill,
  "cupertino_bookmark_fill": CupertinoIcons.bookmark_fill,
  "cupertino_briefcase": CupertinoIcons.briefcase,
  "cupertino_briefcase_fill": CupertinoIcons.briefcase_fill,
  "cupertino_bubble_left": CupertinoIcons.bubble_left,
  "cupertino_bubble_left_bubble_right": CupertinoIcons.bubble_left_bubble_right,
  "cupertino_bubble_left_bubble_right_fill":
      CupertinoIcons.bubble_left_bubble_right_fill,
  "cupertino_bubble_left_fill": CupertinoIcons.bubble_left_fill,
  "cupertino_bubble_middle_bottom": CupertinoIcons.bubble_middle_bottom,
  "cupertino_bubble_middle_bottom_fill":
      CupertinoIcons.bubble_middle_bottom_fill,
  "cupertino_bubble_middle_top": CupertinoIcons.bubble_middle_top,
  "cupertino_bubble_middle_top_fill": CupertinoIcons.bubble_middle_top_fill,
  "cupertino_bubble_right": CupertinoIcons.bubble_right,
  "cupertino_bubble_right_fill": CupertinoIcons.bubble_right_fill,
  "cupertino_building_2_fill": CupertinoIcons.building_2_fill,
  "cupertino_burn": CupertinoIcons.burn,
  "cupertino_burst": CupertinoIcons.burst,
  "cupertino_burst_fill": CupertinoIcons.burst_fill,
  "cupertino_calendar": CupertinoIcons.calendar,
  "cupertino_calendar_badge_minus": CupertinoIcons.calendar_badge_minus,
  "cupertino_calendar_badge_plus": CupertinoIcons.calendar_badge_plus,
  "cupertino_calendar_circle": CupertinoIcons.calendar_circle,
  "cupertino_calendar_circle_fill": CupertinoIcons.calendar_circle_fill,
  "cupertino_calendar_today": CupertinoIcons.calendar_today,
  "cupertino_camera": CupertinoIcons.camera,
  "cupertino_camera_circle": CupertinoIcons.camera_circle,
  "cupertino_camera_circle_fill": CupertinoIcons.camera_circle_fill,
  "cupertino_camera_fill": CupertinoIcons.camera_fill,
  "cupertino_camera_on_rectangle": CupertinoIcons.camera_on_rectangle,
  "cupertino_camera_on_rectangle_fill": CupertinoIcons.camera_on_rectangle_fill,
  "cupertino_camera_rotate": CupertinoIcons.camera_rotate,
  "cupertino_camera_rotate_fill": CupertinoIcons.camera_rotate_fill,
  "cupertino_camera_viewfinder": CupertinoIcons.camera_viewfinder,
  "cupertino_capslock": CupertinoIcons.capslock,
  "cupertino_capslock_fill": CupertinoIcons.capslock_fill,
  "cupertino_capsule": CupertinoIcons.capsule,
  "cupertino_capsule_fill": CupertinoIcons.capsule_fill,
  "cupertino_captions_bubble": CupertinoIcons.captions_bubble,
  "cupertino_captions_bubble_fill": CupertinoIcons.captions_bubble_fill,
  "cupertino_car_fill": CupertinoIcons.car_fill,
  "cupertino_cart": CupertinoIcons.cart,
  "cupertino_cart_badge_minus": CupertinoIcons.cart_badge_minus,
  "cupertino_cart_badge_plus": CupertinoIcons.cart_badge_plus,
  "cupertino_cart_fill": CupertinoIcons.cart_fill,
  "cupertino_cart_fill_badge_minus": CupertinoIcons.cart_fill_badge_minus,
  "cupertino_cart_fill_badge_plus": CupertinoIcons.cart_fill_badge_plus,
  "cupertino_chart_bar": CupertinoIcons.chart_bar,
  "cupertino_chart_bar_alt_fill": CupertinoIcons.chart_bar_alt_fill,
  "cupertino_chart_bar_circle": CupertinoIcons.chart_bar_circle,
  "cupertino_chart_bar_circle_fill": CupertinoIcons.chart_bar_circle_fill,
  "cupertino_chart_bar_fill": CupertinoIcons.chart_bar_fill,
  "cupertino_chart_bar_square": CupertinoIcons.chart_bar_square,
  "cupertino_chart_bar_square_fill": CupertinoIcons.chart_bar_square_fill,
  "cupertino_chart_pie": CupertinoIcons.chart_pie,
  "cupertino_chart_pie_fill": CupertinoIcons.chart_pie_fill,
  "cupertino_chat_bubble": CupertinoIcons.chat_bubble,
  "cupertino_chat_bubble_2": CupertinoIcons.chat_bubble_2,
  "cupertino_chat_bubble_2_fill": CupertinoIcons.chat_bubble_2_fill,
  "cupertino_chat_bubble_fill": CupertinoIcons.chat_bubble_fill,
  "cupertino_chat_bubble_text": CupertinoIcons.chat_bubble_text,
  "cupertino_chat_bubble_text_fill": CupertinoIcons.chat_bubble_text_fill,
  "cupertino_checkmark": CupertinoIcons.checkmark,
  "cupertino_checkmark_alt": CupertinoIcons.checkmark_alt,
  "cupertino_checkmark_alt_circle": CupertinoIcons.checkmark_alt_circle,
  "cupertino_checkmark_alt_circle_fill":
      CupertinoIcons.checkmark_alt_circle_fill,
  "cupertino_checkmark_circle": CupertinoIcons.checkmark_circle,
  "cupertino_checkmark_circle_fill": CupertinoIcons.checkmark_circle_fill,
  "cupertino_checkmark_rectangle": CupertinoIcons.checkmark_rectangle,
  "cupertino_checkmark_rectangle_fill": CupertinoIcons.checkmark_rectangle_fill,
  "cupertino_checkmark_seal": CupertinoIcons.checkmark_seal,
  "cupertino_checkmark_seal_fill": CupertinoIcons.checkmark_seal_fill,
  "cupertino_checkmark_shield": CupertinoIcons.checkmark_shield,
  "cupertino_checkmark_shield_fill": CupertinoIcons.checkmark_shield_fill,
  "cupertino_checkmark_square": CupertinoIcons.checkmark_square,
  "cupertino_checkmark_square_fill": CupertinoIcons.checkmark_square_fill,
  "cupertino_chevron_back": CupertinoIcons.chevron_back,
  "cupertino_chevron_compact_down": CupertinoIcons.chevron_compact_down,
  "cupertino_chevron_compact_left": CupertinoIcons.chevron_compact_left,
  "cupertino_chevron_compact_right": CupertinoIcons.chevron_compact_right,
  "cupertino_chevron_compact_up": CupertinoIcons.chevron_compact_up,
  "cupertino_chevron_down": CupertinoIcons.chevron_down,
  "cupertino_chevron_down_circle": CupertinoIcons.chevron_down_circle,
  "cupertino_chevron_down_circle_fill": CupertinoIcons.chevron_down_circle_fill,
  "cupertino_chevron_down_square": CupertinoIcons.chevron_down_square,
  "cupertino_chevron_down_square_fill": CupertinoIcons.chevron_down_square_fill,
  "cupertino_chevron_forward": CupertinoIcons.chevron_forward,
  "cupertino_chevron_left": CupertinoIcons.chevron_left,
  "cupertino_chevron_left_2": CupertinoIcons.chevron_left_2,
  "cupertino_chevron_left_circle": CupertinoIcons.chevron_left_circle,
  "cupertino_chevron_left_circle_fill": CupertinoIcons.chevron_left_circle_fill,
  "cupertino_chevron_left_slash_chevron_right":
      CupertinoIcons.chevron_left_slash_chevron_right,
  "cupertino_chevron_left_square": CupertinoIcons.chevron_left_square,
  "cupertino_chevron_left_square_fill": CupertinoIcons.chevron_left_square_fill,
  "cupertino_chevron_right": CupertinoIcons.chevron_right,
  "cupertino_chevron_right_2": CupertinoIcons.chevron_right_2,
  "cupertino_chevron_right_circle": CupertinoIcons.chevron_right_circle,
  "cupertino_chevron_right_circle_fill":
      CupertinoIcons.chevron_right_circle_fill,
  "cupertino_chevron_right_square": CupertinoIcons.chevron_right_square,
  "cupertino_chevron_right_square_fill":
      CupertinoIcons.chevron_right_square_fill,
  "cupertino_chevron_up": CupertinoIcons.chevron_up,
  "cupertino_chevron_up_chevron_down": CupertinoIcons.chevron_up_chevron_down,
  "cupertino_chevron_up_circle": CupertinoIcons.chevron_up_circle,
  "cupertino_chevron_up_circle_fill": CupertinoIcons.chevron_up_circle_fill,
  "cupertino_chevron_up_square": CupertinoIcons.chevron_up_square,
  "cupertino_chevron_up_square_fill": CupertinoIcons.chevron_up_square_fill,
  "cupertino_circle_bottomthird_split": CupertinoIcons.circle_bottomthird_split,
  "cupertino_circle_fill": CupertinoIcons.circle_fill,
  "cupertino_circle_grid_3x3": CupertinoIcons.circle_grid_3x3,
  "cupertino_circle_grid_3x3_fill": CupertinoIcons.circle_grid_3x3_fill,
  "cupertino_circle_grid_hex": CupertinoIcons.circle_grid_hex,
  "cupertino_circle_grid_hex_fill": CupertinoIcons.circle_grid_hex_fill,
  "cupertino_circle_lefthalf_fill": CupertinoIcons.circle_lefthalf_fill,
  "cupertino_circle_righthalf_fill": CupertinoIcons.circle_righthalf_fill,
  "cupertino_clear_fill": CupertinoIcons.clear_fill,
  "cupertino_clock_fill": CupertinoIcons.clock_fill,
  "cupertino_cloud": CupertinoIcons.cloud,
  "cupertino_cloud_bolt": CupertinoIcons.cloud_bolt,
  "cupertino_cloud_bolt_fill": CupertinoIcons.cloud_bolt_fill,
  "cupertino_cloud_bolt_rain": CupertinoIcons.cloud_bolt_rain,
  "cupertino_cloud_bolt_rain_fill": CupertinoIcons.cloud_bolt_rain_fill,
  "cupertino_cloud_download": CupertinoIcons.cloud_download,
  "cupertino_cloud_download_fill": CupertinoIcons.cloud_download_fill,
  "cupertino_cloud_drizzle": CupertinoIcons.cloud_drizzle,
  "cupertino_cloud_drizzle_fill": CupertinoIcons.cloud_drizzle_fill,
  "cupertino_cloud_fill": CupertinoIcons.cloud_fill,
  "cupertino_cloud_fog": CupertinoIcons.cloud_fog,
  "cupertino_cloud_fog_fill": CupertinoIcons.cloud_fog_fill,
  "cupertino_cloud_hail": CupertinoIcons.cloud_hail,
  "cupertino_cloud_hail_fill": CupertinoIcons.cloud_hail_fill,
  "cupertino_cloud_heavyrain": CupertinoIcons.cloud_heavyrain,
  "cupertino_cloud_heavyrain_fill": CupertinoIcons.cloud_heavyrain_fill,
  "cupertino_cloud_moon": CupertinoIcons.cloud_moon,
  "cupertino_cloud_moon_bolt": CupertinoIcons.cloud_moon_bolt,
  "cupertino_cloud_moon_bolt_fill": CupertinoIcons.cloud_moon_bolt_fill,
  "cupertino_cloud_moon_fill": CupertinoIcons.cloud_moon_fill,
  "cupertino_cloud_moon_rain": CupertinoIcons.cloud_moon_rain,
  "cupertino_cloud_moon_rain_fill": CupertinoIcons.cloud_moon_rain_fill,
  "cupertino_cloud_rain": CupertinoIcons.cloud_rain,
  "cupertino_cloud_rain_fill": CupertinoIcons.cloud_rain_fill,
  "cupertino_cloud_sleet": CupertinoIcons.cloud_sleet,
  "cupertino_cloud_sleet_fill": CupertinoIcons.cloud_sleet_fill,
  "cupertino_cloud_snow": CupertinoIcons.cloud_snow,
  "cupertino_cloud_snow_fill": CupertinoIcons.cloud_snow_fill,
  "cupertino_cloud_sun": CupertinoIcons.cloud_sun,
  "cupertino_cloud_sun_bolt": CupertinoIcons.cloud_sun_bolt,
  "cupertino_cloud_sun_bolt_fill": CupertinoIcons.cloud_sun_bolt_fill,
  "cupertino_cloud_sun_fill": CupertinoIcons.cloud_sun_fill,
  "cupertino_cloud_sun_rain": CupertinoIcons.cloud_sun_rain,
  "cupertino_cloud_sun_rain_fill": CupertinoIcons.cloud_sun_rain_fill,
  "cupertino_cloud_upload": CupertinoIcons.cloud_upload,
  "cupertino_cloud_upload_fill": CupertinoIcons.cloud_upload_fill,
  "cupertino_color_filter": CupertinoIcons.color_filter,
  "cupertino_color_filter_fill": CupertinoIcons.color_filter_fill,
  "cupertino_command": CupertinoIcons.command,
  "cupertino_compass": CupertinoIcons.compass,
  "cupertino_compass_fill": CupertinoIcons.compass_fill,
  "cupertino_control": CupertinoIcons.control,
  "cupertino_creditcard": CupertinoIcons.creditcard,
  "cupertino_creditcard_fill": CupertinoIcons.creditcard_fill,
  "cupertino_crop": CupertinoIcons.crop,
  "cupertino_crop_rotate": CupertinoIcons.crop_rotate,
  "cupertino_cube": CupertinoIcons.cube,
  "cupertino_cube_box": CupertinoIcons.cube_box,
  "cupertino_cube_box_fill": CupertinoIcons.cube_box_fill,
  "cupertino_cube_fill": CupertinoIcons.cube_fill,
  "cupertino_cursor_rays": CupertinoIcons.cursor_rays,
  "cupertino_decrease_indent": CupertinoIcons.decrease_indent,
  "cupertino_decrease_quotelevel": CupertinoIcons.decrease_quotelevel,
  "cupertino_delete_left": CupertinoIcons.delete_left,
  "cupertino_delete_left_fill": CupertinoIcons.delete_left_fill,
  "cupertino_delete_right": CupertinoIcons.delete_right,
  "cupertino_delete_right_fill": CupertinoIcons.delete_right_fill,
  "cupertino_desktopcomputer": CupertinoIcons.desktopcomputer,
  "cupertino_device_desktop": CupertinoIcons.device_desktop,
  "cupertino_device_laptop": CupertinoIcons.device_laptop,
  "cupertino_device_phone_landscape": CupertinoIcons.device_phone_landscape,
  "cupertino_device_phone_portrait": CupertinoIcons.device_phone_portrait,
  "cupertino_dial": CupertinoIcons.dial,
  "cupertino_dial_fill": CupertinoIcons.dial_fill,
  "cupertino_divide": CupertinoIcons.divide,
  "cupertino_divide_circle": CupertinoIcons.divide_circle,
  "cupertino_divide_circle_fill": CupertinoIcons.divide_circle_fill,
  "cupertino_divide_square": CupertinoIcons.divide_square,
  "cupertino_divide_square_fill": CupertinoIcons.divide_square_fill,
  "cupertino_doc": CupertinoIcons.doc,
  "cupertino_doc_append": CupertinoIcons.doc_append,
  "cupertino_doc_chart": CupertinoIcons.doc_chart,
  "cupertino_doc_chart_fill": CupertinoIcons.doc_chart_fill,
  "cupertino_doc_checkmark": CupertinoIcons.doc_checkmark,
  "cupertino_doc_checkmark_fill": CupertinoIcons.doc_checkmark_fill,
  "cupertino_doc_circle": CupertinoIcons.doc_circle,
  "cupertino_doc_circle_fill": CupertinoIcons.doc_circle_fill,
  "cupertino_doc_fill": CupertinoIcons.doc_fill,
  "cupertino_doc_on_clipboard": CupertinoIcons.doc_on_clipboard,
  "cupertino_doc_on_clipboard_fill": CupertinoIcons.doc_on_clipboard_fill,
  "cupertino_doc_on_doc": CupertinoIcons.doc_on_doc,
  "cupertino_doc_on_doc_fill": CupertinoIcons.doc_on_doc_fill,
  "cupertino_doc_person": CupertinoIcons.doc_person,
  "cupertino_doc_person_fill": CupertinoIcons.doc_person_fill,
  "cupertino_doc_plaintext": CupertinoIcons.doc_plaintext,
  "cupertino_doc_richtext": CupertinoIcons.doc_richtext,
  "cupertino_doc_text": CupertinoIcons.doc_text,
  "cupertino_doc_text_fill": CupertinoIcons.doc_text_fill,
  "cupertino_doc_text_search": CupertinoIcons.doc_text_search,
  "cupertino_doc_text_viewfinder": CupertinoIcons.doc_text_viewfinder,
  "cupertino_dot_radiowaves_left_right":
      CupertinoIcons.dot_radiowaves_left_right,
  "cupertino_dot_radiowaves_right": CupertinoIcons.dot_radiowaves_right,
  "cupertino_dot_square": CupertinoIcons.dot_square,
  "cupertino_dot_square_fill": CupertinoIcons.dot_square_fill,
  "cupertino_download_circle": CupertinoIcons.download_circle,
  "cupertino_download_circle_fill": CupertinoIcons.download_circle_fill,
  "cupertino_drop": CupertinoIcons.drop,
  "cupertino_drop_fill": CupertinoIcons.drop_fill,
  "cupertino_drop_triangle": CupertinoIcons.drop_triangle,
  "cupertino_drop_triangle_fill": CupertinoIcons.drop_triangle_fill,
  "cupertino_ear": CupertinoIcons.ear,
  "cupertino_eject": CupertinoIcons.eject,
  "cupertino_eject_fill": CupertinoIcons.eject_fill,
  "cupertino_ellipses_bubble": CupertinoIcons.ellipses_bubble,
  "cupertino_ellipses_bubble_fill": CupertinoIcons.ellipses_bubble_fill,
  "cupertino_ellipsis_circle": CupertinoIcons.ellipsis_circle,
  "cupertino_ellipsis_circle_fill": CupertinoIcons.ellipsis_circle_fill,
  "cupertino_ellipsis_vertical": CupertinoIcons.ellipsis_vertical,
  "cupertino_ellipsis_vertical_circle": CupertinoIcons.ellipsis_vertical_circle,
  "cupertino_ellipsis_vertical_circle_fill":
      CupertinoIcons.ellipsis_vertical_circle_fill,
  "cupertino_envelope": CupertinoIcons.envelope,
  "cupertino_envelope_badge": CupertinoIcons.envelope_badge,
  "cupertino_envelope_badge_fill": CupertinoIcons.envelope_badge_fill,
  "cupertino_envelope_circle": CupertinoIcons.envelope_circle,
  "cupertino_envelope_circle_fill": CupertinoIcons.envelope_circle_fill,
  "cupertino_envelope_fill": CupertinoIcons.envelope_fill,
  "cupertino_envelope_open": CupertinoIcons.envelope_open,
  "cupertino_envelope_open_fill": CupertinoIcons.envelope_open_fill,
  "cupertino_equal": CupertinoIcons.equal,
  "cupertino_equal_circle": CupertinoIcons.equal_circle,
  "cupertino_equal_circle_fill": CupertinoIcons.equal_circle_fill,
  "cupertino_equal_square": CupertinoIcons.equal_square,
  "cupertino_equal_square_fill": CupertinoIcons.equal_square_fill,
  "cupertino_escape": CupertinoIcons.escape,
  "cupertino_exclamationmark": CupertinoIcons.exclamationmark,
  "cupertino_exclamationmark_bubble": CupertinoIcons.exclamationmark_bubble,
  "cupertino_exclamationmark_bubble_fill":
      CupertinoIcons.exclamationmark_bubble_fill,
  "cupertino_exclamationmark_circle": CupertinoIcons.exclamationmark_circle,
  "cupertino_exclamationmark_circle_fill":
      CupertinoIcons.exclamationmark_circle_fill,
  "cupertino_exclamationmark_octagon": CupertinoIcons.exclamationmark_octagon,
  "cupertino_exclamationmark_octagon_fill":
      CupertinoIcons.exclamationmark_octagon_fill,
  "cupertino_exclamationmark_shield": CupertinoIcons.exclamationmark_shield,
  "cupertino_exclamationmark_shield_fill":
      CupertinoIcons.exclamationmark_shield_fill,
  "cupertino_exclamationmark_square": CupertinoIcons.exclamationmark_square,
  "cupertino_exclamationmark_square_fill":
      CupertinoIcons.exclamationmark_square_fill,
  "cupertino_exclamationmark_triangle": CupertinoIcons.exclamationmark_triangle,
  "cupertino_exclamationmark_triangle_fill":
      CupertinoIcons.exclamationmark_triangle_fill,
  "cupertino_eye_fill": CupertinoIcons.eye_fill,
  "cupertino_eye_slash": CupertinoIcons.eye_slash,
  "cupertino_eye_slash_fill": CupertinoIcons.eye_slash_fill,
  "cupertino_eyedropper": CupertinoIcons.eyedropper,
  "cupertino_eyedropper_full": CupertinoIcons.eyedropper_full,
  "cupertino_eyedropper_halffull": CupertinoIcons.eyedropper_halffull,
  "cupertino_eyeglasses": CupertinoIcons.eyeglasses,
  "cupertino_f_cursive": CupertinoIcons.f_cursive,
  "cupertino_f_cursive_circle": CupertinoIcons.f_cursive_circle,
  "cupertino_f_cursive_circle_fill": CupertinoIcons.f_cursive_circle_fill,
  "cupertino_film": CupertinoIcons.film,
  "cupertino_film_fill": CupertinoIcons.film_fill,
  "cupertino_flag_circle": CupertinoIcons.flag_circle,
  "cupertino_flag_circle_fill": CupertinoIcons.flag_circle_fill,
  "cupertino_flag_fill": CupertinoIcons.flag_fill,
  "cupertino_flag_slash": CupertinoIcons.flag_slash,
  "cupertino_flag_slash_fill": CupertinoIcons.flag_slash_fill,
  "cupertino_flame": CupertinoIcons.flame,
  "cupertino_flame_fill": CupertinoIcons.flame_fill,
  "cupertino_floppy_disk": CupertinoIcons.floppy_disk,
  "cupertino_flowchart": CupertinoIcons.flowchart,
  "cupertino_flowchart_fill": CupertinoIcons.flowchart_fill,
  "cupertino_folder_badge_minus": CupertinoIcons.folder_badge_minus,
  "cupertino_folder_badge_person_crop": CupertinoIcons.folder_badge_person_crop,
  "cupertino_folder_badge_plus": CupertinoIcons.folder_badge_plus,
  "cupertino_folder_circle": CupertinoIcons.folder_circle,
  "cupertino_folder_circle_fill": CupertinoIcons.folder_circle_fill,
  "cupertino_folder_fill": CupertinoIcons.folder_fill,
  "cupertino_folder_fill_badge_minus": CupertinoIcons.folder_fill_badge_minus,
  "cupertino_folder_fill_badge_person_crop":
      CupertinoIcons.folder_fill_badge_person_crop,
  "cupertino_folder_fill_badge_plus": CupertinoIcons.folder_fill_badge_plus,
  "cupertino_forward_end": CupertinoIcons.forward_end,
  "cupertino_forward_end_alt": CupertinoIcons.forward_end_alt,
  "cupertino_forward_end_alt_fill": CupertinoIcons.forward_end_alt_fill,
  "cupertino_forward_end_fill": CupertinoIcons.forward_end_fill,
  "cupertino_forward_fill": CupertinoIcons.forward_fill,
  "cupertino_function": CupertinoIcons.function,
  "cupertino_fx": CupertinoIcons.fx,
  "cupertino_gamecontroller": CupertinoIcons.gamecontroller,
  "cupertino_gamecontroller_alt_fill": CupertinoIcons.gamecontroller_alt_fill,
  "cupertino_gamecontroller_fill": CupertinoIcons.gamecontroller_fill,
  "cupertino_gauge": CupertinoIcons.gauge,
  "cupertino_gauge_badge_minus": CupertinoIcons.gauge_badge_minus,
  "cupertino_gauge_badge_plus": CupertinoIcons.gauge_badge_plus,
  "cupertino_gear_alt": CupertinoIcons.gear_alt,
  "cupertino_gear_alt_fill": CupertinoIcons.gear_alt_fill,
  "cupertino_gift": CupertinoIcons.gift,
  "cupertino_gift_alt": CupertinoIcons.gift_alt,
  "cupertino_gift_alt_fill": CupertinoIcons.gift_alt_fill,
  "cupertino_gift_fill": CupertinoIcons.gift_fill,
  "cupertino_globe": CupertinoIcons.globe,
  "cupertino_gobackward": CupertinoIcons.gobackward,
  "cupertino_gobackward_10": CupertinoIcons.gobackward_10,
  "cupertino_gobackward_15": CupertinoIcons.gobackward_15,
  "cupertino_gobackward_30": CupertinoIcons.gobackward_30,
  "cupertino_gobackward_45": CupertinoIcons.gobackward_45,
  "cupertino_gobackward_60": CupertinoIcons.gobackward_60,
  "cupertino_gobackward_75": CupertinoIcons.gobackward_75,
  "cupertino_gobackward_90": CupertinoIcons.gobackward_90,
  "cupertino_gobackward_minus": CupertinoIcons.gobackward_minus,
  "cupertino_goforward": CupertinoIcons.goforward,
  "cupertino_goforward_10": CupertinoIcons.goforward_10,
  "cupertino_goforward_15": CupertinoIcons.goforward_15,
  "cupertino_goforward_30": CupertinoIcons.goforward_30,
  "cupertino_goforward_45": CupertinoIcons.goforward_45,
  "cupertino_goforward_60": CupertinoIcons.goforward_60,
  "cupertino_goforward_75": CupertinoIcons.goforward_75,
  "cupertino_goforward_90": CupertinoIcons.goforward_90,
  "cupertino_goforward_plus": CupertinoIcons.goforward_plus,
  "cupertino_graph_circle": CupertinoIcons.graph_circle,
  "cupertino_graph_circle_fill": CupertinoIcons.graph_circle_fill,
  "cupertino_graph_square": CupertinoIcons.graph_square,
  "cupertino_graph_square_fill": CupertinoIcons.graph_square_fill,
  "cupertino_greaterthan": CupertinoIcons.greaterthan,
  "cupertino_greaterthan_circle": CupertinoIcons.greaterthan_circle,
  "cupertino_greaterthan_circle_fill": CupertinoIcons.greaterthan_circle_fill,
  "cupertino_greaterthan_square": CupertinoIcons.greaterthan_square,
  "cupertino_greaterthan_square_fill": CupertinoIcons.greaterthan_square_fill,
  "cupertino_grid": CupertinoIcons.grid,
  "cupertino_grid_circle": CupertinoIcons.grid_circle,
  "cupertino_grid_circle_fill": CupertinoIcons.grid_circle_fill,
  "cupertino_guitars": CupertinoIcons.guitars,
  "cupertino_hammer": CupertinoIcons.hammer,
  "cupertino_hammer_fill": CupertinoIcons.hammer_fill,
  "cupertino_hand_draw": CupertinoIcons.hand_draw,
  "cupertino_hand_draw_fill": CupertinoIcons.hand_draw_fill,
  "cupertino_hand_point_left": CupertinoIcons.hand_point_left,
  "cupertino_hand_point_left_fill": CupertinoIcons.hand_point_left_fill,
  "cupertino_hand_point_right": CupertinoIcons.hand_point_right,
  "cupertino_hand_point_right_fill": CupertinoIcons.hand_point_right_fill,
  "cupertino_hand_raised": CupertinoIcons.hand_raised,
  "cupertino_hand_raised_fill": CupertinoIcons.hand_raised_fill,
  "cupertino_hand_raised_slash": CupertinoIcons.hand_raised_slash,
  "cupertino_hand_raised_slash_fill": CupertinoIcons.hand_raised_slash_fill,
  "cupertino_hand_thumbsdown": CupertinoIcons.hand_thumbsdown,
  "cupertino_hand_thumbsdown_fill": CupertinoIcons.hand_thumbsdown_fill,
  "cupertino_hand_thumbsup": CupertinoIcons.hand_thumbsup,
  "cupertino_hand_thumbsup_fill": CupertinoIcons.hand_thumbsup_fill,
  "cupertino_hare": CupertinoIcons.hare,
  "cupertino_hare_fill": CupertinoIcons.hare_fill,
  "cupertino_headphones": CupertinoIcons.headphones,
  "cupertino_heart_circle": CupertinoIcons.heart_circle,
  "cupertino_heart_circle_fill": CupertinoIcons.heart_circle_fill,
  "cupertino_heart_fill": CupertinoIcons.heart_fill,
  "cupertino_heart_slash": CupertinoIcons.heart_slash,
  "cupertino_heart_slash_circle": CupertinoIcons.heart_slash_circle,
  "cupertino_heart_slash_circle_fill": CupertinoIcons.heart_slash_circle_fill,
  "cupertino_heart_slash_fill": CupertinoIcons.heart_slash_fill,
  "cupertino_helm": CupertinoIcons.helm,
  "cupertino_hexagon": CupertinoIcons.hexagon,
  "cupertino_hexagon_fill": CupertinoIcons.hexagon_fill,
  "cupertino_hifispeaker": CupertinoIcons.hifispeaker,
  "cupertino_hifispeaker_fill": CupertinoIcons.hifispeaker_fill,
  "cupertino_hourglass": CupertinoIcons.hourglass,
  "cupertino_hourglass_bottomhalf_fill":
      CupertinoIcons.hourglass_bottomhalf_fill,
  "cupertino_hourglass_tophalf_fill": CupertinoIcons.hourglass_tophalf_fill,
  "cupertino_house": CupertinoIcons.house,
  "cupertino_house_alt": CupertinoIcons.house_alt,
  "cupertino_house_alt_fill": CupertinoIcons.house_alt_fill,
  "cupertino_house_fill": CupertinoIcons.house_fill,
  "cupertino_hurricane": CupertinoIcons.hurricane,
  "cupertino_increase_indent": CupertinoIcons.increase_indent,
  "cupertino_increase_quotelevel": CupertinoIcons.increase_quotelevel,
  "cupertino_infinite": CupertinoIcons.infinite,
  "cupertino_info_circle": CupertinoIcons.info_circle,
  "cupertino_info_circle_fill": CupertinoIcons.info_circle_fill,
  "cupertino_italic": CupertinoIcons.italic,
  "cupertino_keyboard": CupertinoIcons.keyboard,
  "cupertino_keyboard_chevron_compact_down":
      CupertinoIcons.keyboard_chevron_compact_down,
  "cupertino_largecircle_fill_circle": CupertinoIcons.largecircle_fill_circle,
  "cupertino_lasso": CupertinoIcons.lasso,
  "cupertino_layers": CupertinoIcons.layers,
  "cupertino_layers_alt": CupertinoIcons.layers_alt,
  "cupertino_layers_alt_fill": CupertinoIcons.layers_alt_fill,
  "cupertino_layers_fill": CupertinoIcons.layers_fill,
  "cupertino_leaf_arrow_circlepath": CupertinoIcons.leaf_arrow_circlepath,
  "cupertino_lessthan": CupertinoIcons.lessthan,
  "cupertino_lessthan_circle": CupertinoIcons.lessthan_circle,
  "cupertino_lessthan_circle_fill": CupertinoIcons.lessthan_circle_fill,
  "cupertino_lessthan_square": CupertinoIcons.lessthan_square,
  "cupertino_lessthan_square_fill": CupertinoIcons.lessthan_square_fill,
  "cupertino_light_max": CupertinoIcons.light_max,
  "cupertino_light_min": CupertinoIcons.light_min,
  "cupertino_lightbulb": CupertinoIcons.lightbulb,
  "cupertino_lightbulb_fill": CupertinoIcons.lightbulb_fill,
  "cupertino_lightbulb_slash": CupertinoIcons.lightbulb_slash,
  "cupertino_lightbulb_slash_fill": CupertinoIcons.lightbulb_slash_fill,
  "cupertino_line_horizontal_3": CupertinoIcons.line_horizontal_3,
  "cupertino_line_horizontal_3_decrease":
      CupertinoIcons.line_horizontal_3_decrease,
  "cupertino_line_horizontal_3_decrease_circle":
      CupertinoIcons.line_horizontal_3_decrease_circle,
  "cupertino_line_horizontal_3_decrease_circle_fill":
      CupertinoIcons.line_horizontal_3_decrease_circle_fill,
  "cupertino_link": CupertinoIcons.link,
  "cupertino_link_circle": CupertinoIcons.link_circle,
  "cupertino_link_circle_fill": CupertinoIcons.link_circle_fill,
  "cupertino_list_bullet": CupertinoIcons.list_bullet,
  "cupertino_list_bullet_below_rectangle":
      CupertinoIcons.list_bullet_below_rectangle,
  "cupertino_list_bullet_indent": CupertinoIcons.list_bullet_indent,
  "cupertino_list_dash": CupertinoIcons.list_dash,
  "cupertino_list_number": CupertinoIcons.list_number,
  "cupertino_list_number_rtl": CupertinoIcons.list_number_rtl,
  "cupertino_location_circle": CupertinoIcons.location_circle,
  "cupertino_location_circle_fill": CupertinoIcons.location_circle_fill,
  "cupertino_location_fill": CupertinoIcons.location_fill,
  "cupertino_location_north": CupertinoIcons.location_north,
  "cupertino_location_north_fill": CupertinoIcons.location_north_fill,
  "cupertino_location_north_line": CupertinoIcons.location_north_line,
  "cupertino_location_north_line_fill": CupertinoIcons.location_north_line_fill,
  "cupertino_location_slash": CupertinoIcons.location_slash,
  "cupertino_location_slash_fill": CupertinoIcons.location_slash_fill,
  "cupertino_lock": CupertinoIcons.lock,
  "cupertino_lock_circle": CupertinoIcons.lock_circle,
  "cupertino_lock_circle_fill": CupertinoIcons.lock_circle_fill,
  "cupertino_lock_fill": CupertinoIcons.lock_fill,
  "cupertino_lock_open": CupertinoIcons.lock_open,
  "cupertino_lock_open_fill": CupertinoIcons.lock_open_fill,
  "cupertino_lock_rotation": CupertinoIcons.lock_rotation,
  "cupertino_lock_rotation_open": CupertinoIcons.lock_rotation_open,
  "cupertino_lock_shield": CupertinoIcons.lock_shield,
  "cupertino_lock_shield_fill": CupertinoIcons.lock_shield_fill,
  "cupertino_lock_slash": CupertinoIcons.lock_slash,
  "cupertino_lock_slash_fill": CupertinoIcons.lock_slash_fill,
  "cupertino_macwindow": CupertinoIcons.macwindow,
  "cupertino_map": CupertinoIcons.map,
  "cupertino_map_fill": CupertinoIcons.map_fill,
  "cupertino_map_pin": CupertinoIcons.map_pin,
  "cupertino_map_pin_ellipse": CupertinoIcons.map_pin_ellipse,
  "cupertino_map_pin_slash": CupertinoIcons.map_pin_slash,
  "cupertino_memories": CupertinoIcons.memories,
  "cupertino_memories_badge_minus": CupertinoIcons.memories_badge_minus,
  "cupertino_memories_badge_plus": CupertinoIcons.memories_badge_plus,
  "cupertino_metronome": CupertinoIcons.metronome,
  "cupertino_mic_circle": CupertinoIcons.mic_circle,
  "cupertino_mic_circle_fill": CupertinoIcons.mic_circle_fill,
  "cupertino_mic_fill": CupertinoIcons.mic_fill,
  "cupertino_mic_slash": CupertinoIcons.mic_slash,
  "cupertino_mic_slash_fill": CupertinoIcons.mic_slash_fill,
  "cupertino_minus": CupertinoIcons.minus,
  "cupertino_minus_circle": CupertinoIcons.minus_circle,
  "cupertino_minus_circle_fill": CupertinoIcons.minus_circle_fill,
  "cupertino_minus_rectangle": CupertinoIcons.minus_rectangle,
  "cupertino_minus_rectangle_fill": CupertinoIcons.minus_rectangle_fill,
  "cupertino_minus_slash_plus": CupertinoIcons.minus_slash_plus,
  "cupertino_minus_square": CupertinoIcons.minus_square,
  "cupertino_minus_square_fill": CupertinoIcons.minus_square_fill,
  "cupertino_money_dollar": CupertinoIcons.money_dollar,
  "cupertino_money_dollar_circle": CupertinoIcons.money_dollar_circle,
  "cupertino_money_dollar_circle_fill": CupertinoIcons.money_dollar_circle_fill,
  "cupertino_money_euro": CupertinoIcons.money_euro,
  "cupertino_money_euro_circle": CupertinoIcons.money_euro_circle,
  "cupertino_money_euro_circle_fill": CupertinoIcons.money_euro_circle_fill,
  "cupertino_money_pound": CupertinoIcons.money_pound,
  "cupertino_money_pound_circle": CupertinoIcons.money_pound_circle,
  "cupertino_money_pound_circle_fill": CupertinoIcons.money_pound_circle_fill,
  "cupertino_money_rubl": CupertinoIcons.money_rubl,
  "cupertino_money_rubl_circle": CupertinoIcons.money_rubl_circle,
  "cupertino_money_rubl_circle_fill": CupertinoIcons.money_rubl_circle_fill,
  "cupertino_money_yen": CupertinoIcons.money_yen,
  "cupertino_money_yen_circle": CupertinoIcons.money_yen_circle,
  "cupertino_money_yen_circle_fill": CupertinoIcons.money_yen_circle_fill,
  "cupertino_moon": CupertinoIcons.moon,
  "cupertino_moon_circle": CupertinoIcons.moon_circle,
  "cupertino_moon_circle_fill": CupertinoIcons.moon_circle_fill,
  "cupertino_moon_fill": CupertinoIcons.moon_fill,
  "cupertino_moon_stars": CupertinoIcons.moon_stars,
  "cupertino_moon_stars_fill": CupertinoIcons.moon_stars_fill,
  "cupertino_moon_zzz": CupertinoIcons.moon_zzz,
  "cupertino_moon_zzz_fill": CupertinoIcons.moon_zzz_fill,
  "cupertino_move": CupertinoIcons.move,
  "cupertino_multiply": CupertinoIcons.multiply,
  "cupertino_multiply_circle": CupertinoIcons.multiply_circle,
  "cupertino_multiply_circle_fill": CupertinoIcons.multiply_circle_fill,
  "cupertino_multiply_square": CupertinoIcons.multiply_square,
  "cupertino_multiply_square_fill": CupertinoIcons.multiply_square_fill,
  "cupertino_music_albums": CupertinoIcons.music_albums,
  "cupertino_music_albums_fill": CupertinoIcons.music_albums_fill,
  "cupertino_music_house": CupertinoIcons.music_house,
  "cupertino_music_house_fill": CupertinoIcons.music_house_fill,
  "cupertino_music_mic": CupertinoIcons.music_mic,
  "cupertino_music_note_2": CupertinoIcons.music_note_2,
  "cupertino_music_note_list": CupertinoIcons.music_note_list,
  "cupertino_nosign": CupertinoIcons.nosign,
  "cupertino_number": CupertinoIcons.number,
  "cupertino_number_circle": CupertinoIcons.number_circle,
  "cupertino_number_circle_fill": CupertinoIcons.number_circle_fill,
  "cupertino_number_square": CupertinoIcons.number_square,
  "cupertino_number_square_fill": CupertinoIcons.number_square_fill,
  "cupertino_option": CupertinoIcons.option,
  "cupertino_paintbrush": CupertinoIcons.paintbrush,
  "cupertino_paintbrush_fill": CupertinoIcons.paintbrush_fill,
  "cupertino_pano": CupertinoIcons.pano,
  "cupertino_pano_fill": CupertinoIcons.pano_fill,
  "cupertino_paperclip": CupertinoIcons.paperclip,
  "cupertino_paperplane": CupertinoIcons.paperplane,
  "cupertino_paperplane_fill": CupertinoIcons.paperplane_fill,
  "cupertino_paragraph": CupertinoIcons.paragraph,
  "cupertino_pause_circle": CupertinoIcons.pause_circle,
  "cupertino_pause_circle_fill": CupertinoIcons.pause_circle_fill,
  "cupertino_pause_fill": CupertinoIcons.pause_fill,
  "cupertino_pause_rectangle": CupertinoIcons.pause_rectangle,
  "cupertino_pause_rectangle_fill": CupertinoIcons.pause_rectangle_fill,
  "cupertino_pencil_circle": CupertinoIcons.pencil_circle,
  "cupertino_pencil_circle_fill": CupertinoIcons.pencil_circle_fill,
  "cupertino_pencil_ellipsis_rectangle":
      CupertinoIcons.pencil_ellipsis_rectangle,
  "cupertino_pencil_outline": CupertinoIcons.pencil_outline,
  "cupertino_pencil_slash": CupertinoIcons.pencil_slash,
  "cupertino_percent": CupertinoIcons.percent,
  "cupertino_person_2": CupertinoIcons.person_2,
  "cupertino_person_2_alt": CupertinoIcons.person_2_alt,
  "cupertino_person_2_fill": CupertinoIcons.person_2_fill,
  "cupertino_person_2_square_stack": CupertinoIcons.person_2_square_stack,
  "cupertino_person_2_square_stack_fill":
      CupertinoIcons.person_2_square_stack_fill,
  "cupertino_person_3": CupertinoIcons.person_3,
  "cupertino_person_3_fill": CupertinoIcons.person_3_fill,
  "cupertino_person_alt": CupertinoIcons.person_alt,
  "cupertino_person_alt_circle": CupertinoIcons.person_alt_circle,
  "cupertino_person_alt_circle_fill": CupertinoIcons.person_alt_circle_fill,
  "cupertino_person_badge_minus": CupertinoIcons.person_badge_minus,
  "cupertino_person_badge_minus_fill": CupertinoIcons.person_badge_minus_fill,
  "cupertino_person_badge_plus": CupertinoIcons.person_badge_plus,
  "cupertino_person_badge_plus_fill": CupertinoIcons.person_badge_plus_fill,
  "cupertino_person_circle": CupertinoIcons.person_circle,
  "cupertino_person_circle_fill": CupertinoIcons.person_circle_fill,
  "cupertino_person_crop_circle": CupertinoIcons.person_crop_circle,
  "cupertino_person_crop_circle_badge_checkmark":
      CupertinoIcons.person_crop_circle_badge_checkmark,
  "cupertino_person_crop_circle_badge_exclam":
      CupertinoIcons.person_crop_circle_badge_exclam,
  "cupertino_person_crop_circle_badge_minus":
      CupertinoIcons.person_crop_circle_badge_minus,
  "cupertino_person_crop_circle_badge_plus":
      CupertinoIcons.person_crop_circle_badge_plus,
  "cupertino_person_crop_circle_badge_xmark":
      CupertinoIcons.person_crop_circle_badge_xmark,
  "cupertino_person_crop_circle_fill": CupertinoIcons.person_crop_circle_fill,
  "cupertino_person_crop_circle_fill_badge_checkmark":
      CupertinoIcons.person_crop_circle_fill_badge_checkmark,
  "cupertino_person_crop_circle_fill_badge_exclam":
      CupertinoIcons.person_crop_circle_fill_badge_exclam,
  "cupertino_person_crop_circle_fill_badge_minus":
      CupertinoIcons.person_crop_circle_fill_badge_minus,
  "cupertino_person_crop_circle_fill_badge_plus":
      CupertinoIcons.person_crop_circle_fill_badge_plus,
  "cupertino_person_crop_circle_fill_badge_xmark":
      CupertinoIcons.person_crop_circle_fill_badge_xmark,
  "cupertino_person_crop_rectangle": CupertinoIcons.person_crop_rectangle,
  "cupertino_person_crop_rectangle_fill":
      CupertinoIcons.person_crop_rectangle_fill,
  "cupertino_person_crop_square": CupertinoIcons.person_crop_square,
  "cupertino_person_crop_square_fill": CupertinoIcons.person_crop_square_fill,
  "cupertino_person_fill": CupertinoIcons.person_fill,
  "cupertino_personalhotspot": CupertinoIcons.personalhotspot,
  "cupertino_perspective": CupertinoIcons.perspective,
  "cupertino_phone_arrow_down_left": CupertinoIcons.phone_arrow_down_left,
  "cupertino_phone_arrow_right": CupertinoIcons.phone_arrow_right,
  "cupertino_phone_arrow_up_right": CupertinoIcons.phone_arrow_up_right,
  "cupertino_phone_badge_plus": CupertinoIcons.phone_badge_plus,
  "cupertino_phone_circle": CupertinoIcons.phone_circle,
  "cupertino_phone_circle_fill": CupertinoIcons.phone_circle_fill,
  "cupertino_phone_down": CupertinoIcons.phone_down,
  "cupertino_phone_down_circle": CupertinoIcons.phone_down_circle,
  "cupertino_phone_down_circle_fill": CupertinoIcons.phone_down_circle_fill,
  "cupertino_phone_down_fill": CupertinoIcons.phone_down_fill,
  "cupertino_phone_fill": CupertinoIcons.phone_fill,
  "cupertino_phone_fill_arrow_down_left":
      CupertinoIcons.phone_fill_arrow_down_left,
  "cupertino_phone_fill_arrow_right": CupertinoIcons.phone_fill_arrow_right,
  "cupertino_phone_fill_arrow_up_right":
      CupertinoIcons.phone_fill_arrow_up_right,
  "cupertino_phone_fill_badge_plus": CupertinoIcons.phone_fill_badge_plus,
  "cupertino_photo": CupertinoIcons.photo,
  "cupertino_photo_fill": CupertinoIcons.photo_fill,
  "cupertino_photo_fill_on_rectangle_fill":
      CupertinoIcons.photo_fill_on_rectangle_fill,
  "cupertino_photo_on_rectangle": CupertinoIcons.photo_on_rectangle,
  "cupertino_piano": CupertinoIcons.piano,
  "cupertino_pin": CupertinoIcons.pin,
  "cupertino_pin_fill": CupertinoIcons.pin_fill,
  "cupertino_pin_slash": CupertinoIcons.pin_slash,
  "cupertino_pin_slash_fill": CupertinoIcons.pin_slash_fill,
  "cupertino_placemark": CupertinoIcons.placemark,
  "cupertino_placemark_fill": CupertinoIcons.placemark_fill,
  "cupertino_play": CupertinoIcons.play,
  "cupertino_play_circle": CupertinoIcons.play_circle,
  "cupertino_play_circle_fill": CupertinoIcons.play_circle_fill,
  "cupertino_play_fill": CupertinoIcons.play_fill,
  "cupertino_play_rectangle": CupertinoIcons.play_rectangle,
  "cupertino_play_rectangle_fill": CupertinoIcons.play_rectangle_fill,
  "cupertino_playpause": CupertinoIcons.playpause,
  "cupertino_playpause_fill": CupertinoIcons.playpause_fill,
  "cupertino_plus": CupertinoIcons.plus,
  "cupertino_plus_app": CupertinoIcons.plus_app,
  "cupertino_plus_app_fill": CupertinoIcons.plus_app_fill,
  "cupertino_plus_bubble": CupertinoIcons.plus_bubble,
  "cupertino_plus_bubble_fill": CupertinoIcons.plus_bubble_fill,
  "cupertino_plus_circle": CupertinoIcons.plus_circle,
  "cupertino_plus_circle_fill": CupertinoIcons.plus_circle_fill,
  "cupertino_plus_rectangle": CupertinoIcons.plus_rectangle,
  "cupertino_plus_rectangle_fill": CupertinoIcons.plus_rectangle_fill,
  "cupertino_plus_rectangle_fill_on_rectangle_fill":
      CupertinoIcons.plus_rectangle_fill_on_rectangle_fill,
  "cupertino_plus_rectangle_on_rectangle":
      CupertinoIcons.plus_rectangle_on_rectangle,
  "cupertino_plus_slash_minus": CupertinoIcons.plus_slash_minus,
  "cupertino_plus_square": CupertinoIcons.plus_square,
  "cupertino_plus_square_fill": CupertinoIcons.plus_square_fill,
  "cupertino_plus_square_fill_on_square_fill":
      CupertinoIcons.plus_square_fill_on_square_fill,
  "cupertino_plus_square_on_square": CupertinoIcons.plus_square_on_square,
  "cupertino_plusminus": CupertinoIcons.plusminus,
  "cupertino_plusminus_circle": CupertinoIcons.plusminus_circle,
  "cupertino_plusminus_circle_fill": CupertinoIcons.plusminus_circle_fill,
  "cupertino_power": CupertinoIcons.power,
  "cupertino_printer": CupertinoIcons.printer,
  "cupertino_printer_fill": CupertinoIcons.printer_fill,
  "cupertino_projective": CupertinoIcons.projective,
  "cupertino_purchased": CupertinoIcons.purchased,
  "cupertino_purchased_circle": CupertinoIcons.purchased_circle,
  "cupertino_purchased_circle_fill": CupertinoIcons.purchased_circle_fill,
  "cupertino_qrcode": CupertinoIcons.qrcode,
  "cupertino_qrcode_viewfinder": CupertinoIcons.qrcode_viewfinder,
  "cupertino_question": CupertinoIcons.question,
  "cupertino_question_circle": CupertinoIcons.question_circle,
  "cupertino_question_circle_fill": CupertinoIcons.question_circle_fill,
  "cupertino_question_diamond": CupertinoIcons.question_diamond,
  "cupertino_question_diamond_fill": CupertinoIcons.question_diamond_fill,
  "cupertino_question_square": CupertinoIcons.question_square,
  "cupertino_question_square_fill": CupertinoIcons.question_square_fill,
  "cupertino_quote_bubble": CupertinoIcons.quote_bubble,
  "cupertino_quote_bubble_fill": CupertinoIcons.quote_bubble_fill,
  "cupertino_radiowaves_left": CupertinoIcons.radiowaves_left,
  "cupertino_radiowaves_right": CupertinoIcons.radiowaves_right,
  "cupertino_rays": CupertinoIcons.rays,
  "cupertino_recordingtape": CupertinoIcons.recordingtape,
  "cupertino_rectangle": CupertinoIcons.rectangle,
  "cupertino_rectangle_3_offgrid": CupertinoIcons.rectangle_3_offgrid,
  "cupertino_rectangle_3_offgrid_fill": CupertinoIcons.rectangle_3_offgrid_fill,
  "cupertino_rectangle_arrow_up_right_arrow_down_left":
      CupertinoIcons.rectangle_arrow_up_right_arrow_down_left,
  "cupertino_rectangle_arrow_up_right_arrow_down_left_slash":
      CupertinoIcons.rectangle_arrow_up_right_arrow_down_left_slash,
  "cupertino_rectangle_badge_checkmark":
      CupertinoIcons.rectangle_badge_checkmark,
  "cupertino_rectangle_badge_xmark": CupertinoIcons.rectangle_badge_xmark,
  "cupertino_rectangle_compress_vertical":
      CupertinoIcons.rectangle_compress_vertical,
  "cupertino_rectangle_dock": CupertinoIcons.rectangle_dock,
  "cupertino_rectangle_expand_vertical":
      CupertinoIcons.rectangle_expand_vertical,
  "cupertino_rectangle_fill": CupertinoIcons.rectangle_fill,
  "cupertino_rectangle_fill_badge_checkmark":
      CupertinoIcons.rectangle_fill_badge_checkmark,
  "cupertino_rectangle_fill_badge_xmark":
      CupertinoIcons.rectangle_fill_badge_xmark,
  "cupertino_rectangle_fill_on_rectangle_angled_fill":
      CupertinoIcons.rectangle_fill_on_rectangle_angled_fill,
  "cupertino_rectangle_fill_on_rectangle_fill":
      CupertinoIcons.rectangle_fill_on_rectangle_fill,
  "cupertino_rectangle_grid_1x2": CupertinoIcons.rectangle_grid_1x2,
  "cupertino_rectangle_grid_1x2_fill": CupertinoIcons.rectangle_grid_1x2_fill,
  "cupertino_rectangle_grid_2x2": CupertinoIcons.rectangle_grid_2x2,
  "cupertino_rectangle_grid_2x2_fill": CupertinoIcons.rectangle_grid_2x2_fill,
  "cupertino_rectangle_grid_3x2": CupertinoIcons.rectangle_grid_3x2,
  "cupertino_rectangle_grid_3x2_fill": CupertinoIcons.rectangle_grid_3x2_fill,
  "cupertino_rectangle_on_rectangle": CupertinoIcons.rectangle_on_rectangle,
  "cupertino_rectangle_on_rectangle_angled":
      CupertinoIcons.rectangle_on_rectangle_angled,
  "cupertino_rectangle_paperclip": CupertinoIcons.rectangle_paperclip,
  "cupertino_rectangle_split_3x1": CupertinoIcons.rectangle_split_3x1,
  "cupertino_rectangle_split_3x1_fill": CupertinoIcons.rectangle_split_3x1_fill,
  "cupertino_rectangle_split_3x3": CupertinoIcons.rectangle_split_3x3,
  "cupertino_rectangle_split_3x3_fill": CupertinoIcons.rectangle_split_3x3_fill,
  "cupertino_rectangle_stack": CupertinoIcons.rectangle_stack,
  "cupertino_rectangle_stack_badge_minus":
      CupertinoIcons.rectangle_stack_badge_minus,
  "cupertino_rectangle_stack_badge_person_crop":
      CupertinoIcons.rectangle_stack_badge_person_crop,
  "cupertino_rectangle_stack_badge_plus":
      CupertinoIcons.rectangle_stack_badge_plus,
  "cupertino_rectangle_stack_fill": CupertinoIcons.rectangle_stack_fill,
  "cupertino_rectangle_stack_fill_badge_minus":
      CupertinoIcons.rectangle_stack_fill_badge_minus,
  "cupertino_rectangle_stack_fill_badge_person_crop":
      CupertinoIcons.rectangle_stack_fill_badge_person_crop,
  "cupertino_rectangle_stack_fill_badge_plus":
      CupertinoIcons.rectangle_stack_fill_badge_plus,
  "cupertino_rectangle_stack_person_crop":
      CupertinoIcons.rectangle_stack_person_crop,
  "cupertino_rectangle_stack_person_crop_fill":
      CupertinoIcons.rectangle_stack_person_crop_fill,
  "cupertino_repeat": CupertinoIcons.repeat,
  "cupertino_repeat_1": CupertinoIcons.repeat_1,
  "cupertino_resize": CupertinoIcons.resize,
  "cupertino_resize_h": CupertinoIcons.resize_h,
  "cupertino_resize_v": CupertinoIcons.resize_v,
  "cupertino_return_icon": CupertinoIcons.return_icon,
  "cupertino_rhombus": CupertinoIcons.rhombus,
  "cupertino_rhombus_fill": CupertinoIcons.rhombus_fill,
  "cupertino_rocket": CupertinoIcons.rocket,
  "cupertino_rocket_fill": CupertinoIcons.rocket_fill,
  "cupertino_rosette": CupertinoIcons.rosette,
  "cupertino_rotate_left": CupertinoIcons.rotate_left,
  "cupertino_rotate_left_fill": CupertinoIcons.rotate_left_fill,
  "cupertino_rotate_right": CupertinoIcons.rotate_right,
  "cupertino_rotate_right_fill": CupertinoIcons.rotate_right_fill,
  "cupertino_scissors": CupertinoIcons.scissors,
  "cupertino_scissors_alt": CupertinoIcons.scissors_alt,
  "cupertino_scope": CupertinoIcons.scope,
  "cupertino_scribble": CupertinoIcons.scribble,
  "cupertino_search_circle": CupertinoIcons.search_circle,
  "cupertino_search_circle_fill": CupertinoIcons.search_circle_fill,
  "cupertino_selection_pin_in_out": CupertinoIcons.selection_pin_in_out,
  "cupertino_shield": CupertinoIcons.shield,
  "cupertino_shield_fill": CupertinoIcons.shield_fill,
  "cupertino_shield_lefthalf_fill": CupertinoIcons.shield_lefthalf_fill,
  "cupertino_shield_slash": CupertinoIcons.shield_slash,
  "cupertino_shield_slash_fill": CupertinoIcons.shield_slash_fill,
  "cupertino_shift": CupertinoIcons.shift,
  "cupertino_shift_fill": CupertinoIcons.shift_fill,
  "cupertino_sidebar_left": CupertinoIcons.sidebar_left,
  "cupertino_sidebar_right": CupertinoIcons.sidebar_right,
  "cupertino_signature": CupertinoIcons.signature,
  "cupertino_skew": CupertinoIcons.skew,
  "cupertino_slash_circle": CupertinoIcons.slash_circle,
  "cupertino_slash_circle_fill": CupertinoIcons.slash_circle_fill,
  "cupertino_slider_horizontal_3": CupertinoIcons.slider_horizontal_3,
  "cupertino_slider_horizontal_below_rectangle":
      CupertinoIcons.slider_horizontal_below_rectangle,
  "cupertino_slowmo": CupertinoIcons.slowmo,
  "cupertino_smallcircle_circle": CupertinoIcons.smallcircle_circle,
  "cupertino_smallcircle_circle_fill": CupertinoIcons.smallcircle_circle_fill,
  "cupertino_smallcircle_fill_circle": CupertinoIcons.smallcircle_fill_circle,
  "cupertino_smallcircle_fill_circle_fill":
      CupertinoIcons.smallcircle_fill_circle_fill,
  "cupertino_smiley": CupertinoIcons.smiley,
  "cupertino_smiley_fill": CupertinoIcons.smiley_fill,
  "cupertino_smoke": CupertinoIcons.smoke,
  "cupertino_smoke_fill": CupertinoIcons.smoke_fill,
  "cupertino_snow": CupertinoIcons.snow,
  "cupertino_sort_down": CupertinoIcons.sort_down,
  "cupertino_sort_down_circle": CupertinoIcons.sort_down_circle,
  "cupertino_sort_down_circle_fill": CupertinoIcons.sort_down_circle_fill,
  "cupertino_sort_up": CupertinoIcons.sort_up,
  "cupertino_sort_up_circle": CupertinoIcons.sort_up_circle,
  "cupertino_sort_up_circle_fill": CupertinoIcons.sort_up_circle_fill,
  "cupertino_sparkles": CupertinoIcons.sparkles,
  "cupertino_speaker": CupertinoIcons.speaker,
  "cupertino_speaker_1": CupertinoIcons.speaker_1,
  "cupertino_speaker_1_fill": CupertinoIcons.speaker_1_fill,
  "cupertino_speaker_2": CupertinoIcons.speaker_2,
  "cupertino_speaker_2_fill": CupertinoIcons.speaker_2_fill,
  "cupertino_speaker_3": CupertinoIcons.speaker_3,
  "cupertino_speaker_3_fill": CupertinoIcons.speaker_3_fill,
  "cupertino_speaker_fill": CupertinoIcons.speaker_fill,
  "cupertino_speaker_slash": CupertinoIcons.speaker_slash,
  "cupertino_speaker_slash_fill": CupertinoIcons.speaker_slash_fill,
  "cupertino_speaker_slash_fill_rtl": CupertinoIcons.speaker_slash_fill_rtl,
  "cupertino_speaker_slash_rtl": CupertinoIcons.speaker_slash_rtl,
  "cupertino_speaker_zzz": CupertinoIcons.speaker_zzz,
  "cupertino_speaker_zzz_fill": CupertinoIcons.speaker_zzz_fill,
  "cupertino_speaker_zzz_fill_rtl": CupertinoIcons.speaker_zzz_fill_rtl,
  "cupertino_speaker_zzz_rtl": CupertinoIcons.speaker_zzz_rtl,
  "cupertino_speedometer": CupertinoIcons.speedometer,
  "cupertino_sportscourt": CupertinoIcons.sportscourt,
  "cupertino_sportscourt_fill": CupertinoIcons.sportscourt_fill,
  "cupertino_square": CupertinoIcons.square,
  "cupertino_square_arrow_down": CupertinoIcons.square_arrow_down,
  "cupertino_square_arrow_down_fill": CupertinoIcons.square_arrow_down_fill,
  "cupertino_square_arrow_down_on_square":
      CupertinoIcons.square_arrow_down_on_square,
  "cupertino_square_arrow_down_on_square_fill":
      CupertinoIcons.square_arrow_down_on_square_fill,
  "cupertino_square_arrow_left": CupertinoIcons.square_arrow_left,
  "cupertino_square_arrow_left_fill": CupertinoIcons.square_arrow_left_fill,
  "cupertino_square_arrow_right": CupertinoIcons.square_arrow_right,
  "cupertino_square_arrow_right_fill": CupertinoIcons.square_arrow_right_fill,
  "cupertino_square_arrow_up": CupertinoIcons.square_arrow_up,
  "cupertino_square_arrow_up_fill": CupertinoIcons.square_arrow_up_fill,
  "cupertino_square_arrow_up_on_square":
      CupertinoIcons.square_arrow_up_on_square,
  "cupertino_square_arrow_up_on_square_fill":
      CupertinoIcons.square_arrow_up_on_square_fill,
  "cupertino_square_favorites": CupertinoIcons.square_favorites,
  "cupertino_square_favorites_alt": CupertinoIcons.square_favorites_alt,
  "cupertino_square_favorites_alt_fill":
      CupertinoIcons.square_favorites_alt_fill,
  "cupertino_square_favorites_fill": CupertinoIcons.square_favorites_fill,
  "cupertino_square_fill": CupertinoIcons.square_fill,
  "cupertino_square_fill_line_vertical_square":
      CupertinoIcons.square_fill_line_vertical_square,
  "cupertino_square_fill_line_vertical_square_fill":
      CupertinoIcons.square_fill_line_vertical_square_fill,
  "cupertino_square_fill_on_circle_fill":
      CupertinoIcons.square_fill_on_circle_fill,
  "cupertino_square_fill_on_square_fill":
      CupertinoIcons.square_fill_on_square_fill,
  "cupertino_square_grid_2x2": CupertinoIcons.square_grid_2x2,
  "cupertino_square_grid_2x2_fill": CupertinoIcons.square_grid_2x2_fill,
  "cupertino_square_grid_3x2": CupertinoIcons.square_grid_3x2,
  "cupertino_square_grid_3x2_fill": CupertinoIcons.square_grid_3x2_fill,
  "cupertino_square_grid_4x3_fill": CupertinoIcons.square_grid_4x3_fill,
  "cupertino_square_lefthalf_fill": CupertinoIcons.square_lefthalf_fill,
  "cupertino_square_line_vertical_square":
      CupertinoIcons.square_line_vertical_square,
  "cupertino_square_line_vertical_square_fill":
      CupertinoIcons.square_line_vertical_square_fill,
  "cupertino_square_list": CupertinoIcons.square_list,
  "cupertino_square_list_fill": CupertinoIcons.square_list_fill,
  "cupertino_square_on_circle": CupertinoIcons.square_on_circle,
  "cupertino_square_on_square": CupertinoIcons.square_on_square,
  "cupertino_square_pencil": CupertinoIcons.square_pencil,
  "cupertino_square_pencil_fill": CupertinoIcons.square_pencil_fill,
  "cupertino_square_righthalf_fill": CupertinoIcons.square_righthalf_fill,
  "cupertino_square_split_1x2": CupertinoIcons.square_split_1x2,
  "cupertino_square_split_1x2_fill": CupertinoIcons.square_split_1x2_fill,
  "cupertino_square_split_2x1": CupertinoIcons.square_split_2x1,
  "cupertino_square_split_2x1_fill": CupertinoIcons.square_split_2x1_fill,
  "cupertino_square_split_2x2": CupertinoIcons.square_split_2x2,
  "cupertino_square_split_2x2_fill": CupertinoIcons.square_split_2x2_fill,
  "cupertino_square_stack": CupertinoIcons.square_stack,
  "cupertino_square_stack_3d_down_dottedline":
      CupertinoIcons.square_stack_3d_down_dottedline,
  "cupertino_square_stack_3d_down_right":
      CupertinoIcons.square_stack_3d_down_right,
  "cupertino_square_stack_3d_down_right_fill":
      CupertinoIcons.square_stack_3d_down_right_fill,
  "cupertino_square_stack_3d_up": CupertinoIcons.square_stack_3d_up,
  "cupertino_square_stack_3d_up_fill": CupertinoIcons.square_stack_3d_up_fill,
  "cupertino_square_stack_3d_up_slash": CupertinoIcons.square_stack_3d_up_slash,
  "cupertino_square_stack_3d_up_slash_fill":
      CupertinoIcons.square_stack_3d_up_slash_fill,
  "cupertino_square_stack_fill": CupertinoIcons.square_stack_fill,
  "cupertino_squares_below_rectangle": CupertinoIcons.squares_below_rectangle,
  "cupertino_star": CupertinoIcons.star,
  "cupertino_star_circle": CupertinoIcons.star_circle,
  "cupertino_star_circle_fill": CupertinoIcons.star_circle_fill,
  "cupertino_star_fill": CupertinoIcons.star_fill,
  "cupertino_star_lefthalf_fill": CupertinoIcons.star_lefthalf_fill,
  "cupertino_star_slash": CupertinoIcons.star_slash,
  "cupertino_star_slash_fill": CupertinoIcons.star_slash_fill,
  "cupertino_staroflife": CupertinoIcons.staroflife,
  "cupertino_staroflife_fill": CupertinoIcons.staroflife_fill,
  "cupertino_stop": CupertinoIcons.stop,
  "cupertino_stop_circle": CupertinoIcons.stop_circle,
  "cupertino_stop_circle_fill": CupertinoIcons.stop_circle_fill,
  "cupertino_stop_fill": CupertinoIcons.stop_fill,
  "cupertino_stopwatch": CupertinoIcons.stopwatch,
  "cupertino_stopwatch_fill": CupertinoIcons.stopwatch_fill,
  "cupertino_strikethrough": CupertinoIcons.strikethrough,
  "cupertino_suit_club": CupertinoIcons.suit_club,
  "cupertino_suit_club_fill": CupertinoIcons.suit_club_fill,
  "cupertino_suit_diamond": CupertinoIcons.suit_diamond,
  "cupertino_suit_diamond_fill": CupertinoIcons.suit_diamond_fill,
  "cupertino_suit_heart": CupertinoIcons.suit_heart,
  "cupertino_suit_heart_fill": CupertinoIcons.suit_heart_fill,
  "cupertino_suit_spade": CupertinoIcons.suit_spade,
  "cupertino_suit_spade_fill": CupertinoIcons.suit_spade_fill,
  "cupertino_sum": CupertinoIcons.sum,
  "cupertino_sun_dust": CupertinoIcons.sun_dust,
  "cupertino_sun_dust_fill": CupertinoIcons.sun_dust_fill,
  "cupertino_sun_haze": CupertinoIcons.sun_haze,
  "cupertino_sun_haze_fill": CupertinoIcons.sun_haze_fill,
  "cupertino_sun_max": CupertinoIcons.sun_max,
  "cupertino_sun_max_fill": CupertinoIcons.sun_max_fill,
  "cupertino_sun_min": CupertinoIcons.sun_min,
  "cupertino_sun_min_fill": CupertinoIcons.sun_min_fill,
  "cupertino_sunrise": CupertinoIcons.sunrise,
  "cupertino_sunrise_fill": CupertinoIcons.sunrise_fill,
  "cupertino_sunset": CupertinoIcons.sunset,
  "cupertino_sunset_fill": CupertinoIcons.sunset_fill,
  "cupertino_t_bubble": CupertinoIcons.t_bubble,
  "cupertino_t_bubble_fill": CupertinoIcons.t_bubble_fill,
  "cupertino_table": CupertinoIcons.table,
  "cupertino_table_badge_more": CupertinoIcons.table_badge_more,
  "cupertino_table_badge_more_fill": CupertinoIcons.table_badge_more_fill,
  "cupertino_table_fill": CupertinoIcons.table_fill,
  "cupertino_tag_circle": CupertinoIcons.tag_circle,
  "cupertino_tag_circle_fill": CupertinoIcons.tag_circle_fill,
  "cupertino_tag_fill": CupertinoIcons.tag_fill,
  "cupertino_text_aligncenter": CupertinoIcons.text_aligncenter,
  "cupertino_text_alignleft": CupertinoIcons.text_alignleft,
  "cupertino_text_alignright": CupertinoIcons.text_alignright,
  "cupertino_text_append": CupertinoIcons.text_append,
  "cupertino_text_badge_checkmark": CupertinoIcons.text_badge_checkmark,
  "cupertino_text_badge_minus": CupertinoIcons.text_badge_minus,
  "cupertino_text_badge_plus": CupertinoIcons.text_badge_plus,
  "cupertino_text_badge_star": CupertinoIcons.text_badge_star,
  "cupertino_text_badge_xmark": CupertinoIcons.text_badge_xmark,
  "cupertino_text_bubble": CupertinoIcons.text_bubble,
  "cupertino_text_bubble_fill": CupertinoIcons.text_bubble_fill,
  "cupertino_text_cursor": CupertinoIcons.text_cursor,
  "cupertino_text_insert": CupertinoIcons.text_insert,
  "cupertino_text_justify": CupertinoIcons.text_justify,
  "cupertino_text_justifyleft": CupertinoIcons.text_justifyleft,
  "cupertino_text_justifyright": CupertinoIcons.text_justifyright,
  "cupertino_text_quote": CupertinoIcons.text_quote,
  "cupertino_textbox": CupertinoIcons.textbox,
  "cupertino_textformat": CupertinoIcons.textformat,
  "cupertino_textformat_123": CupertinoIcons.textformat_123,
  "cupertino_textformat_abc": CupertinoIcons.textformat_abc,
  "cupertino_textformat_abc_dottedunderline":
      CupertinoIcons.textformat_abc_dottedunderline,
  "cupertino_textformat_alt": CupertinoIcons.textformat_alt,
  "cupertino_textformat_size": CupertinoIcons.textformat_size,
  "cupertino_textformat_subscript": CupertinoIcons.textformat_subscript,
  "cupertino_textformat_superscript": CupertinoIcons.textformat_superscript,
  "cupertino_thermometer": CupertinoIcons.thermometer,
  "cupertino_thermometer_snowflake": CupertinoIcons.thermometer_snowflake,
  "cupertino_thermometer_sun": CupertinoIcons.thermometer_sun,
  "cupertino_ticket": CupertinoIcons.ticket,
  "cupertino_ticket_fill": CupertinoIcons.ticket_fill,
  "cupertino_tickets": CupertinoIcons.tickets,
  "cupertino_tickets_fill": CupertinoIcons.tickets_fill,
  "cupertino_timelapse": CupertinoIcons.timelapse,
  "cupertino_timer": CupertinoIcons.timer,
  "cupertino_timer_fill": CupertinoIcons.timer_fill,
  "cupertino_today": CupertinoIcons.today,
  "cupertino_today_fill": CupertinoIcons.today_fill,
  "cupertino_tornado": CupertinoIcons.tornado,
  "cupertino_tortoise": CupertinoIcons.tortoise,
  "cupertino_tortoise_fill": CupertinoIcons.tortoise_fill,
  "cupertino_tram_fill": CupertinoIcons.tram_fill,
  "cupertino_trash": CupertinoIcons.trash,
  "cupertino_trash_circle": CupertinoIcons.trash_circle,
  "cupertino_trash_circle_fill": CupertinoIcons.trash_circle_fill,
  "cupertino_trash_fill": CupertinoIcons.trash_fill,
  "cupertino_trash_slash": CupertinoIcons.trash_slash,
  "cupertino_trash_slash_fill": CupertinoIcons.trash_slash_fill,
  "cupertino_tray": CupertinoIcons.tray,
  "cupertino_tray_2": CupertinoIcons.tray_2,
  "cupertino_tray_2_fill": CupertinoIcons.tray_2_fill,
  "cupertino_tray_arrow_down": CupertinoIcons.tray_arrow_down,
  "cupertino_tray_arrow_down_fill": CupertinoIcons.tray_arrow_down_fill,
  "cupertino_tray_arrow_up": CupertinoIcons.tray_arrow_up,
  "cupertino_tray_arrow_up_fill": CupertinoIcons.tray_arrow_up_fill,
  "cupertino_tray_fill": CupertinoIcons.tray_fill,
  "cupertino_tray_full": CupertinoIcons.tray_full,
  "cupertino_tray_full_fill": CupertinoIcons.tray_full_fill,
  "cupertino_tree": CupertinoIcons.tree,
  "cupertino_triangle": CupertinoIcons.triangle,
  "cupertino_triangle_fill": CupertinoIcons.triangle_fill,
  "cupertino_triangle_lefthalf_fill": CupertinoIcons.triangle_lefthalf_fill,
  "cupertino_triangle_righthalf_fill": CupertinoIcons.triangle_righthalf_fill,
  "cupertino_tropicalstorm": CupertinoIcons.tropicalstorm,
  "cupertino_tuningfork": CupertinoIcons.tuningfork,
  "cupertino_tv": CupertinoIcons.tv,
  "cupertino_tv_circle": CupertinoIcons.tv_circle,
  "cupertino_tv_circle_fill": CupertinoIcons.tv_circle_fill,
  "cupertino_tv_fill": CupertinoIcons.tv_fill,
  "cupertino_tv_music_note": CupertinoIcons.tv_music_note,
  "cupertino_tv_music_note_fill": CupertinoIcons.tv_music_note_fill,
  "cupertino_uiwindow_split_2x1": CupertinoIcons.uiwindow_split_2x1,
  "cupertino_umbrella": CupertinoIcons.umbrella,
  "cupertino_umbrella_fill": CupertinoIcons.umbrella_fill,
  "cupertino_underline": CupertinoIcons.underline,
  "cupertino_upload_circle": CupertinoIcons.upload_circle,
  "cupertino_upload_circle_fill": CupertinoIcons.upload_circle_fill,
  "cupertino_videocam": CupertinoIcons.videocam,
  "cupertino_videocam_circle": CupertinoIcons.videocam_circle,
  "cupertino_videocam_circle_fill": CupertinoIcons.videocam_circle_fill,
  "cupertino_videocam_fill": CupertinoIcons.videocam_fill,
  "cupertino_view_2d": CupertinoIcons.view_2d,
  "cupertino_view_3d": CupertinoIcons.view_3d,
  "cupertino_viewfinder": CupertinoIcons.viewfinder,
  "cupertino_viewfinder_circle": CupertinoIcons.viewfinder_circle,
  "cupertino_viewfinder_circle_fill": CupertinoIcons.viewfinder_circle_fill,
  "cupertino_wand_rays": CupertinoIcons.wand_rays,
  "cupertino_wand_rays_inverse": CupertinoIcons.wand_rays_inverse,
  "cupertino_wand_stars": CupertinoIcons.wand_stars,
  "cupertino_wand_stars_inverse": CupertinoIcons.wand_stars_inverse,
  "cupertino_waveform": CupertinoIcons.waveform,
  "cupertino_waveform_circle": CupertinoIcons.waveform_circle,
  "cupertino_waveform_circle_fill": CupertinoIcons.waveform_circle_fill,
  "cupertino_waveform_path": CupertinoIcons.waveform_path,
  "cupertino_waveform_path_badge_minus":
      CupertinoIcons.waveform_path_badge_minus,
  "cupertino_waveform_path_badge_plus": CupertinoIcons.waveform_path_badge_plus,
  "cupertino_waveform_path_ecg": CupertinoIcons.waveform_path_ecg,
  "cupertino_wifi": CupertinoIcons.wifi,
  "cupertino_wifi_exclamationmark": CupertinoIcons.wifi_exclamationmark,
  "cupertino_wifi_slash": CupertinoIcons.wifi_slash,
  "cupertino_wind": CupertinoIcons.wind,
  "cupertino_wind_snow": CupertinoIcons.wind_snow,
  "cupertino_wrench": CupertinoIcons.wrench,
  "cupertino_wrench_fill": CupertinoIcons.wrench_fill,
  "cupertino_xmark": CupertinoIcons.xmark,
  "cupertino_xmark_circle": CupertinoIcons.xmark_circle,
  "cupertino_xmark_circle_fill": CupertinoIcons.xmark_circle_fill,
  "cupertino_xmark_octagon": CupertinoIcons.xmark_octagon,
  "cupertino_xmark_octagon_fill": CupertinoIcons.xmark_octagon_fill,
  "cupertino_xmark_rectangle": CupertinoIcons.xmark_rectangle,
  "cupertino_xmark_rectangle_fill": CupertinoIcons.xmark_rectangle_fill,
  "cupertino_xmark_seal": CupertinoIcons.xmark_seal,
  "cupertino_xmark_seal_fill": CupertinoIcons.xmark_seal_fill,
  "cupertino_xmark_shield": CupertinoIcons.xmark_shield,
  "cupertino_xmark_shield_fill": CupertinoIcons.xmark_shield_fill,
  "cupertino_xmark_square": CupertinoIcons.xmark_square,
  "cupertino_xmark_square_fill": CupertinoIcons.xmark_square_fill,
  "cupertino_zoom_in": CupertinoIcons.zoom_in,
  "cupertino_zoom_out": CupertinoIcons.zoom_out,
  "cupertino_zzz": CupertinoIcons.zzz,
};
