[tool.poetry]
name = "flet-web"
version = "0.1.0"
description = "Flet web client in Flutter."
authors = ["Appveyor Systems Inc. <hello@flet.dev>"]
license = "Apache-2.0"
readme = "README.md"

packages = [{ include = "flet_web", from = "src" }]

include = [{ path = "src/flet_web/web/**/*", format = ["sdist", "wheel"] }]

[tool.poetry.urls]
homepage = "https://flet.dev"
repository = "https://github.com/flet-dev/flet"
documentation = "https://flet.dev/docs"

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "*"
uvicorn = { extras = ["standard"], version = "*" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
float_to_top = true
