title: "[Question]"
labels: ["help needed"]
body:
  - type: markdown
    attributes:
      value: |
        This is the place to ask for specifics about flet or for help with problems you encountered while using it.
  - type: checkboxes
    id: similar-search
    attributes:
      label: X
      options:
        - label: I have searched for answers to my question both in the issues and in previous discussions.
          required: true
  - type: textarea
    id: question
    attributes:
      label: Your question
      description: Type out your question as precisely as possible.
      value: ""
    validations:
      required: true
  - type: textarea
    id: code
    attributes:
      label: Code sample
      description: |
        If applicable, paste in a code sample of your best attempt so far. It will automatically be rendered as python code.
      value: ""
      render: python
  - type: textarea
    id: error
    attributes:
      label: Error message
      description: If applicable, paste in the full error message you received.
      value: ""
      render: bash
