authors:
  feodor:
    name: Feodor Fitsner
    description: Flet Founder and Developer
    url: ttps://github.com/FeodorFitsner
    avatar: https://avatars0.githubusercontent.com/u/5041459?s=400&v=4
    socials:
      github: FeodorFitsner
      x: fletdev

  henri:
    name: Henri Ndonko
    description: Flet Contributor and Maintainer
    url: https://github.com/ndonkoHenri
    avatar: https://avatars.githubusercontent.com/u/98978078?v=4
    socials:
      github: ndonkoHenri
      x: ndonkoHenri