"""
Flet Lucide Icons Stub

To generate/update this file run from the root of the repository:

```
uv run .github/scripts/generate_icons.py
```
"""

from flet.controls.icon_data import IconData

__all__ = ["LucideIcons"]

class LucideIcons:
    A_ARROW_DOWN: IconData
    A_ARROW_UP: IconData
    A_LARGE_SMALL: IconData
    ACCESSIBILITY: IconData
    ACTIVITY: IconData
    ACTIVITY_SQUARE: IconData
    AD: IconData
    AIR_VENT: IconData
    AIRPLAY: IconData
    ALARM_CHECK: IconData
    ALARM_CLOCK: IconData
    ALARM_CLOCK_CHECK: IconData
    ALARM_CLOCK_MINUS: IconData
    ALARM_CLOCK_OFF: IconData
    ALARM_CLOCK_PLUS: IconData
    ALARM_MINUS: IconData
    ALARM_PLUS: IconData
    ALARM_SMOKE: IconData
    ALBUM: IconData
    ALERT_CIRCLE: IconData
    ALERT_OCTAGON: IconData
    ALERT_TRIANGLE: IconData
    ALIGN_CENTER: IconData
    ALIGN_CENTER_HORIZONTAL: IconData
    ALIGN_CENTER_VERTICAL: IconData
    ALIGN_END_HORIZONTAL: IconData
    ALIGN_END_VERTICAL: IconData
    ALIGN_HORIZONTAL_DISTRIBUTE_CENTER: IconData
    ALIGN_HORIZONTAL_DISTRIBUTE_END: IconData
    ALIGN_HORIZONTAL_DISTRIBUTE_START: IconData
    ALIGN_HORIZONTAL_JUSTIFY_CENTER: IconData
    ALIGN_HORIZONTAL_JUSTIFY_END: IconData
    ALIGN_HORIZONTAL_JUSTIFY_START: IconData
    ALIGN_HORIZONTAL_SPACE_AROUND: IconData
    ALIGN_HORIZONTAL_SPACE_BETWEEN: IconData
    ALIGN_JUSTIFY: IconData
    ALIGN_LEFT: IconData
    ALIGN_RIGHT: IconData
    ALIGN_START_HORIZONTAL: IconData
    ALIGN_START_VERTICAL: IconData
    ALIGN_VERTICAL_DISTRIBUTE_CENTER: IconData
    ALIGN_VERTICAL_DISTRIBUTE_END: IconData
    ALIGN_VERTICAL_DISTRIBUTE_START: IconData
    ALIGN_VERTICAL_JUSTIFY_CENTER: IconData
    ALIGN_VERTICAL_JUSTIFY_END: IconData
    ALIGN_VERTICAL_JUSTIFY_START: IconData
    ALIGN_VERTICAL_SPACE_AROUND: IconData
    ALIGN_VERTICAL_SPACE_BETWEEN: IconData
    AMBULANCE: IconData
    AMPERSAND: IconData
    AMPERSANDS: IconData
    AMPHORA: IconData
    ANCHOR: IconData
    ANGLE: IconData
    ANGRY: IconData
    ANNOYED: IconData
    ANTENNA: IconData
    ANVIL: IconData
    APERTURE: IconData
    APP_WINDOW: IconData
    APP_WINDOW_MAC: IconData
    APPLE: IconData
    ARCHIVE: IconData
    ARCHIVE_RESTORE: IconData
    ARCHIVE_X: IconData
    AREA_CHART: IconData
    ARMCHAIR: IconData
    ARROW_BIG_DOWN: IconData
    ARROW_BIG_DOWN_DASH: IconData
    ARROW_BIG_LEFT: IconData
    ARROW_BIG_LEFT_DASH: IconData
    ARROW_BIG_RIGHT: IconData
    ARROW_BIG_RIGHT_DASH: IconData
    ARROW_BIG_UP: IconData
    ARROW_BIG_UP_DASH: IconData
    ARROW_DOWN: IconData
    ARROW_DOWN_01: IconData
    ARROW_DOWN_10: IconData
    ARROW_DOWN_AZ: IconData
    ARROW_DOWN_CIRCLE: IconData
    ARROW_DOWN_FROM_LINE: IconData
    ARROW_DOWN_LEFT: IconData
    ARROW_DOWN_LEFT_FROM_CIRCLE: IconData
    ARROW_DOWN_LEFT_FROM_SQUARE: IconData
    ARROW_DOWN_LEFT_SQUARE: IconData
    ARROW_DOWN_NARROW_WIDE: IconData
    ARROW_DOWN_RIGHT: IconData
    ARROW_DOWN_RIGHT_FROM_CIRCLE: IconData
    ARROW_DOWN_RIGHT_FROM_SQUARE: IconData
    ARROW_DOWN_RIGHT_SQUARE: IconData
    ARROW_DOWN_SQUARE: IconData
    ARROW_DOWN_TO_DOT: IconData
    ARROW_DOWN_TO_LINE: IconData
    ARROW_DOWN_UP: IconData
    ARROW_DOWN_WIDE_NARROW: IconData
    ARROW_DOWN_ZA: IconData
    ARROW_LEFT: IconData
    ARROW_LEFT_CIRCLE: IconData
    ARROW_LEFT_FROM_LINE: IconData
    ARROW_LEFT_RIGHT: IconData
    ARROW_LEFT_SQUARE: IconData
    ARROW_LEFT_TO_LINE: IconData
    ARROW_RIGHT: IconData
    ARROW_RIGHT_CIRCLE: IconData
    ARROW_RIGHT_FROM_LINE: IconData
    ARROW_RIGHT_LEFT: IconData
    ARROW_RIGHT_SQUARE: IconData
    ARROW_RIGHT_TO_LINE: IconData
    ARROW_UP: IconData
    ARROW_UP_01: IconData
    ARROW_UP_10: IconData
    ARROW_UP_AZ: IconData
    ARROW_UP_CIRCLE: IconData
    ARROW_UP_DOWN: IconData
    ARROW_UP_FROM_DOT: IconData
    ARROW_UP_FROM_LINE: IconData
    ARROW_UP_LEFT: IconData
    ARROW_UP_LEFT_FROM_CIRCLE: IconData
    ARROW_UP_LEFT_FROM_SQUARE: IconData
    ARROW_UP_LEFT_SQUARE: IconData
    ARROW_UP_NARROW_WIDE: IconData
    ARROW_UP_RIGHT: IconData
    ARROW_UP_RIGHT_FROM_CIRCLE: IconData
    ARROW_UP_RIGHT_FROM_SQUARE: IconData
    ARROW_UP_RIGHT_SQUARE: IconData
    ARROW_UP_SQUARE: IconData
    ARROW_UP_TO_LINE: IconData
    ARROW_UP_WIDE_NARROW: IconData
    ARROW_UP_ZA: IconData
    ARROWS_UP_FROM_LINE: IconData
    ASTERISK: IconData
    ASTERISK_SQUARE: IconData
    ASTROID: IconData
    AT_SIGN: IconData
    ATOM: IconData
    AUDIO_LINES: IconData
    AUDIO_LINES_OFF: IconData
    AUDIO_LINES_X: IconData
    AUDIO_WAVEFORM: IconData
    AWARD: IconData
    AXE: IconData
    AXIS_3_D: IconData
    AXIS_3D: IconData
    BABY: IconData
    BACKPACK: IconData
    BADGE: IconData
    BADGE_ALERT: IconData
    BADGE_CENT: IconData
    BADGE_CHECK: IconData
    BADGE_DOLLAR_SIGN: IconData
    BADGE_EURO: IconData
    BADGE_HELP: IconData
    BADGE_INDIAN_RUPEE: IconData
    BADGE_INFO: IconData
    BADGE_JAPANESE_YEN: IconData
    BADGE_MINUS: IconData
    BADGE_PERCENT: IconData
    BADGE_PLUS: IconData
    BADGE_POUND_STERLING: IconData
    BADGE_QUESTION_MARK: IconData
    BADGE_RUSSIAN_RUBLE: IconData
    BADGE_SWISS_FRANC: IconData
    BADGE_TURKISH_LIRA: IconData
    BADGE_X: IconData
    BAGGAGE_CLAIM: IconData
    BALLOON: IconData
    BAN: IconData
    BANANA: IconData
    BANDAGE: IconData
    BANKNOTE: IconData
    BANKNOTE_ARROW_DOWN: IconData
    BANKNOTE_ARROW_UP: IconData
    BANKNOTE_CHECK: IconData
    BANKNOTE_X: IconData
    BAR_CHART: IconData
    BAR_CHART_2: IconData
    BAR_CHART_3: IconData
    BAR_CHART_4: IconData
    BAR_CHART_BIG: IconData
    BAR_CHART_HORIZONTAL: IconData
    BAR_CHART_HORIZONTAL_BIG: IconData
    BARCODE: IconData
    BARREL: IconData
    BASELINE: IconData
    BATH: IconData
    BATTERY: IconData
    BATTERY_CHARGING: IconData
    BATTERY_FULL: IconData
    BATTERY_LOW: IconData
    BATTERY_MEDIUM: IconData
    BATTERY_PLUS: IconData
    BATTERY_WARNING: IconData
    BEAKER: IconData
    BEAN: IconData
    BEAN_OFF: IconData
    BED: IconData
    BED_DOUBLE: IconData
    BED_SINGLE: IconData
    BEEF: IconData
    BEEF_OFF: IconData
    BEER: IconData
    BEER_OFF: IconData
    BELL: IconData
    BELL_CHECK: IconData
    BELL_DOT: IconData
    BELL_ELECTRIC: IconData
    BELL_MINUS: IconData
    BELL_OFF: IconData
    BELL_PLUS: IconData
    BELL_RING: IconData
    BETWEEN_HORIZONAL_END: IconData
    BETWEEN_HORIZONAL_START: IconData
    BETWEEN_HORIZONTAL_END: IconData
    BETWEEN_HORIZONTAL_START: IconData
    BETWEEN_VERTICAL_END: IconData
    BETWEEN_VERTICAL_START: IconData
    BICEPS_FLEXED: IconData
    BIKE: IconData
    BINARY: IconData
    BINOCULARS: IconData
    BIOHAZARD: IconData
    BIRD: IconData
    BIRDHOUSE: IconData
    BITCOIN: IconData
    BLEND: IconData
    BLENDER: IconData
    BLINDS: IconData
    BLOCKS: IconData
    BLUETOOTH: IconData
    BLUETOOTH_CONNECTED: IconData
    BLUETOOTH_OFF: IconData
    BLUETOOTH_SEARCHING: IconData
    BOLD: IconData
    BOLT: IconData
    BOMB: IconData
    BONE: IconData
    BONE_FRACTURE: IconData
    BOOK: IconData
    BOOK_A: IconData
    BOOK_ALERT: IconData
    BOOK_AUDIO: IconData
    BOOK_BOOKMARK: IconData
    BOOK_CHECK: IconData
    BOOK_COPY: IconData
    BOOK_DASHED: IconData
    BOOK_DOWN: IconData
    BOOK_HEADPHONES: IconData
    BOOK_HEART: IconData
    BOOK_IMAGE: IconData
    BOOK_KEY: IconData
    BOOK_LOCK: IconData
    BOOK_MARKED: IconData
    BOOK_MINUS: IconData
    BOOK_OPEN: IconData
    BOOK_OPEN_CHECK: IconData
    BOOK_OPEN_TEXT: IconData
    BOOK_PLUS: IconData
    BOOK_SEARCH: IconData
    BOOK_TEMPLATE: IconData
    BOOK_TEXT: IconData
    BOOK_TYPE: IconData
    BOOK_UP: IconData
    BOOK_UP_2: IconData
    BOOK_USER: IconData
    BOOK_X: IconData
    BOOKMARK: IconData
    BOOKMARK_CHECK: IconData
    BOOKMARK_MINUS: IconData
    BOOKMARK_OFF: IconData
    BOOKMARK_PLUS: IconData
    BOOKMARK_X: IconData
    BOOM_BOX: IconData
    BOT: IconData
    BOT_MESSAGE_SQUARE: IconData
    BOT_OFF: IconData
    BOTTLE_WINE: IconData
    BOW_ARROW: IconData
    BOX: IconData
    BOX_SELECT: IconData
    BOXES: IconData
    BRACES: IconData
    BRACKETS: IconData
    BRAIN: IconData
    BRAIN_CIRCUIT: IconData
    BRAIN_COG: IconData
    BRICK_WALL: IconData
    BRICK_WALL_FIRE: IconData
    BRICK_WALL_SHIELD: IconData
    BRIDGE: IconData
    BRIEFCASE: IconData
    BRIEFCASE_BUSINESS: IconData
    BRIEFCASE_CONVEYOR_BELT: IconData
    BRIEFCASE_MEDICAL: IconData
    BRING_TO_FRONT: IconData
    BROCCOLI: IconData
    BROOM: IconData
    BROOM_SPARKLES: IconData
    BRUSH: IconData
    BRUSH_CLEANING: IconData
    BUBBLES: IconData
    BUG: IconData
    BUG_OFF: IconData
    BUG_PLAY: IconData
    BUILDING: IconData
    BUILDING_2: IconData
    BUILDING_COMPLEX: IconData
    BUILDING_COMPLEX_PLUS: IconData
    BUS: IconData
    BUS_FRONT: IconData
    CABLE: IconData
    CABLE_CAR: IconData
    CAKE: IconData
    CAKE_SLICE: IconData
    CALCULATOR: IconData
    CALENDAR: IconData
    CALENDAR_1: IconData
    CALENDAR_ARROW_DOWN: IconData
    CALENDAR_ARROW_UP: IconData
    CALENDAR_CHECK: IconData
    CALENDAR_CHECK_2: IconData
    CALENDAR_CHEVRONS_RIGHT: IconData
    CALENDAR_CLOCK: IconData
    CALENDAR_COG: IconData
    CALENDAR_DAYS: IconData
    CALENDAR_FOLD: IconData
    CALENDAR_HEART: IconData
    CALENDAR_MINUS: IconData
    CALENDAR_MINUS_2: IconData
    CALENDAR_OFF: IconData
    CALENDAR_PLUS: IconData
    CALENDAR_PLUS_2: IconData
    CALENDAR_RANGE: IconData
    CALENDAR_SEARCH: IconData
    CALENDAR_SYNC: IconData
    CALENDAR_X: IconData
    CALENDAR_X_2: IconData
    CALENDARS: IconData
    CAMERA: IconData
    CAMERA_OFF: IconData
    CAN: IconData
    CAN_SODA: IconData
    CANDLESTICK_CHART: IconData
    CANDY: IconData
    CANDY_CANE: IconData
    CANDY_OFF: IconData
    CANNABIS: IconData
    CANNABIS_OFF: IconData
    CAPTIONS: IconData
    CAPTIONS_OFF: IconData
    CAR: IconData
    CAR_BATTERY: IconData
    CAR_FRONT: IconData
    CAR_TAXI_FRONT: IconData
    CARAVAN: IconData
    CARD_SIM: IconData
    CARROT: IconData
    CARTON: IconData
    CARTON_OFF: IconData
    CASE_LOWER: IconData
    CASE_SENSITIVE: IconData
    CASE_UPPER: IconData
    CASSETTE_TAPE: IconData
    CAST: IconData
    CASTLE: IconData
    CAT: IconData
    CCTV: IconData
    CCTV_OFF: IconData
    CHART_AREA: IconData
    CHART_BAR: IconData
    CHART_BAR_BIG: IconData
    CHART_BAR_DECREASING: IconData
    CHART_BAR_INCREASING: IconData
    CHART_BAR_STACKED: IconData
    CHART_CANDLESTICK: IconData
    CHART_COLUMN: IconData
    CHART_COLUMN_BIG: IconData
    CHART_COLUMN_DECREASING: IconData
    CHART_COLUMN_INCREASING: IconData
    CHART_COLUMN_STACKED: IconData
    CHART_GANTT: IconData
    CHART_LINE: IconData
    CHART_NETWORK: IconData
    CHART_NO_AXES_COLUMN: IconData
    CHART_NO_AXES_COLUMN_DECREASING: IconData
    CHART_NO_AXES_COLUMN_INCREASING: IconData
    CHART_NO_AXES_COMBINED: IconData
    CHART_NO_AXES_GANTT: IconData
    CHART_PIE: IconData
    CHART_SCATTER: IconData
    CHART_SPLINE: IconData
    CHECK: IconData
    CHECK_CHECK: IconData
    CHECK_CIRCLE: IconData
    CHECK_CIRCLE_2: IconData
    CHECK_LINE: IconData
    CHECK_SQUARE: IconData
    CHECK_SQUARE_2: IconData
    CHEF_HAT: IconData
    CHERRY: IconData
    CHESS_BISHOP: IconData
    CHESS_KING: IconData
    CHESS_KNIGHT: IconData
    CHESS_PAWN: IconData
    CHESS_QUEEN: IconData
    CHESS_ROOK: IconData
    CHEVRON_DOWN: IconData
    CHEVRON_DOWN_CIRCLE: IconData
    CHEVRON_DOWN_SQUARE: IconData
    CHEVRON_FIRST: IconData
    CHEVRON_LAST: IconData
    CHEVRON_LEFT: IconData
    CHEVRON_LEFT_CIRCLE: IconData
    CHEVRON_LEFT_SQUARE: IconData
    CHEVRON_RIGHT: IconData
    CHEVRON_RIGHT_CIRCLE: IconData
    CHEVRON_RIGHT_SQUARE: IconData
    CHEVRON_UP: IconData
    CHEVRON_UP_CIRCLE: IconData
    CHEVRON_UP_SQUARE: IconData
    CHEVRONS_DOWN: IconData
    CHEVRONS_DOWN_UP: IconData
    CHEVRONS_LEFT: IconData
    CHEVRONS_LEFT_RIGHT: IconData
    CHEVRONS_LEFT_RIGHT_ELLIPSIS: IconData
    CHEVRONS_RIGHT: IconData
    CHEVRONS_RIGHT_LEFT: IconData
    CHEVRONS_UP: IconData
    CHEVRONS_UP_DOWN: IconData
    CHURCH: IconData
    CIGARETTE: IconData
    CIGARETTE_OFF: IconData
    CIRCLE: IconData
    CIRCLE_ALERT: IconData
    CIRCLE_ARROW_DOWN: IconData
    CIRCLE_ARROW_LEFT: IconData
    CIRCLE_ARROW_OUT_DOWN_LEFT: IconData
    CIRCLE_ARROW_OUT_DOWN_RIGHT: IconData
    CIRCLE_ARROW_OUT_UP_LEFT: IconData
    CIRCLE_ARROW_OUT_UP_RIGHT: IconData
    CIRCLE_ARROW_RIGHT: IconData
    CIRCLE_ARROW_UP: IconData
    CIRCLE_CHECK: IconData
    CIRCLE_CHECK_BIG: IconData
    CIRCLE_CHEVRON_DOWN: IconData
    CIRCLE_CHEVRON_LEFT: IconData
    CIRCLE_CHEVRON_RIGHT: IconData
    CIRCLE_CHEVRON_UP: IconData
    CIRCLE_DASHED: IconData
    CIRCLE_DASHED_CHECK: IconData
    CIRCLE_DIVIDE: IconData
    CIRCLE_DOLLAR_SIGN: IconData
    CIRCLE_DOT: IconData
    CIRCLE_DOT_DASHED: IconData
    CIRCLE_ELLIPSIS: IconData
    CIRCLE_EQUAL: IconData
    CIRCLE_EURO: IconData
    CIRCLE_FADING_ARROW_UP: IconData
    CIRCLE_FADING_PLUS: IconData
    CIRCLE_GAUGE: IconData
    CIRCLE_HELP: IconData
    CIRCLE_MINUS: IconData
    CIRCLE_OFF: IconData
    CIRCLE_PARKING: IconData
    CIRCLE_PARKING_OFF: IconData
    CIRCLE_PAUSE: IconData
    CIRCLE_PERCENT: IconData
    CIRCLE_PILE: IconData
    CIRCLE_PLAY: IconData
    CIRCLE_PLUS: IconData
    CIRCLE_POUND_STERLING: IconData
    CIRCLE_POWER: IconData
    CIRCLE_QUESTION_MARK: IconData
    CIRCLE_SLASH: IconData
    CIRCLE_SLASH_2: IconData
    CIRCLE_SLASHED: IconData
    CIRCLE_SMALL: IconData
    CIRCLE_STAR: IconData
    CIRCLE_STOP: IconData
    CIRCLE_USER: IconData
    CIRCLE_USER_ROUND: IconData
    CIRCLE_X: IconData
    CIRCUIT_BOARD: IconData
    CITRUS: IconData
    CLAPPERBOARD: IconData
    CLEF_ALTO: IconData
    CLEF_BASS: IconData
    CLEF_TREBLE: IconData
    CLIPBOARD: IconData
    CLIPBOARD_CHECK: IconData
    CLIPBOARD_CLOCK: IconData
    CLIPBOARD_COPY: IconData
    CLIPBOARD_EDIT: IconData
    CLIPBOARD_LIST: IconData
    CLIPBOARD_MINUS: IconData
    CLIPBOARD_PASTE: IconData
    CLIPBOARD_PEN: IconData
    CLIPBOARD_PEN_LINE: IconData
    CLIPBOARD_PLUS: IconData
    CLIPBOARD_SIGNATURE: IconData
    CLIPBOARD_TYPE: IconData
    CLIPBOARD_X: IconData
    CLOCK: IconData
    CLOCK_1: IconData
    CLOCK_10: IconData
    CLOCK_11: IconData
    CLOCK_12: IconData
    CLOCK_2: IconData
    CLOCK_3: IconData
    CLOCK_4: IconData
    CLOCK_5: IconData
    CLOCK_6: IconData
    CLOCK_7: IconData
    CLOCK_8: IconData
    CLOCK_9: IconData
    CLOCK_ALERT: IconData
    CLOCK_ARROW_DOWN: IconData
    CLOCK_ARROW_LEFT: IconData
    CLOCK_ARROW_RIGHT: IconData
    CLOCK_ARROW_UP: IconData
    CLOCK_CHECK: IconData
    CLOCK_FADING: IconData
    CLOCK_PLUS: IconData
    CLOSED_CAPTION: IconData
    CLOUD: IconData
    CLOUD_ALERT: IconData
    CLOUD_BACKUP: IconData
    CLOUD_CHECK: IconData
    CLOUD_COG: IconData
    CLOUD_DOWNLOAD: IconData
    CLOUD_DRIZZLE: IconData
    CLOUD_FOG: IconData
    CLOUD_HAIL: IconData
    CLOUD_LIGHTNING: IconData
    CLOUD_MOON: IconData
    CLOUD_MOON_RAIN: IconData
    CLOUD_OFF: IconData
    CLOUD_RAIN: IconData
    CLOUD_RAIN_WIND: IconData
    CLOUD_SNOW: IconData
    CLOUD_SUN: IconData
    CLOUD_SUN_RAIN: IconData
    CLOUD_SYNC: IconData
    CLOUD_UPLOAD: IconData
    CLOUDY: IconData
    CLOVER: IconData
    CLUB: IconData
    CODE: IconData
    CODE_2: IconData
    CODE_SQUARE: IconData
    CODE_XML: IconData
    COFFEE: IconData
    COG: IconData
    COINS: IconData
    COLUMNS: IconData
    COLUMNS_2: IconData
    COLUMNS_3: IconData
    COLUMNS_3_COG: IconData
    COLUMNS_4: IconData
    COLUMNS_SETTINGS: IconData
    COMBINE: IconData
    COMMAND: IconData
    COMPASS: IconData
    COMPONENT: IconData
    COMPUTER: IconData
    CONCIERGE_BELL: IconData
    CONE: IconData
    CONSTRUCTION: IconData
    CONTACT: IconData
    CONTACT_2: IconData
    CONTACT_ROUND: IconData
    CONTAINER: IconData
    CONTRAST: IconData
    COOKIE: IconData
    COOKING_POT: IconData
    COPY: IconData
    COPY_CHECK: IconData
    COPY_MINUS: IconData
    COPY_PLUS: IconData
    COPY_SLASH: IconData
    COPY_X: IconData
    COPYLEFT: IconData
    COPYRIGHT: IconData
    CORNER_DOWN_LEFT: IconData
    CORNER_DOWN_RIGHT: IconData
    CORNER_LEFT_DOWN: IconData
    CORNER_LEFT_UP: IconData
    CORNER_RIGHT_DOWN: IconData
    CORNER_RIGHT_UP: IconData
    CORNER_UP_LEFT: IconData
    CORNER_UP_RIGHT: IconData
    CPU: IconData
    CREATIVE_COMMONS: IconData
    CREDIT_CARD: IconData
    CREDIT_CARD_CHECK: IconData
    CREDIT_CARD_MINUS: IconData
    CREDIT_CARD_PLUS: IconData
    CREDIT_CARD_READER: IconData
    CREDIT_CARD_X: IconData
    CROISSANT: IconData
    CROP: IconData
    CROSS: IconData
    CROSSHAIR: IconData
    CROWN: IconData
    CUBOID: IconData
    CUP_SODA: IconData
    CURLY_BRACES: IconData
    CURRENCY: IconData
    CYLINDER: IconData
    DAM: IconData
    DATABASE: IconData
    DATABASE_ARROW_DOWN: IconData
    DATABASE_ARROW_UP: IconData
    DATABASE_BACKUP: IconData
    DATABASE_CHECK: IconData
    DATABASE_MINUS: IconData
    DATABASE_PLUS: IconData
    DATABASE_SEARCH: IconData
    DATABASE_X: IconData
    DATABASE_ZAP: IconData
    DECIMALS_ARROW_LEFT: IconData
    DECIMALS_ARROW_RIGHT: IconData
    DELETE: IconData
    DESSERT: IconData
    DIAMETER: IconData
    DIAMOND: IconData
    DIAMOND_MINUS: IconData
    DIAMOND_PERCENT: IconData
    DIAMOND_PLUS: IconData
    DICE_1: IconData
    DICE_2: IconData
    DICE_3: IconData
    DICE_4: IconData
    DICE_5: IconData
    DICE_6: IconData
    DICES: IconData
    DIFF: IconData
    DISC: IconData
    DISC_2: IconData
    DISC_3: IconData
    DISC_ALBUM: IconData
    DIVIDE: IconData
    DIVIDE_CIRCLE: IconData
    DIVIDE_SQUARE: IconData
    DNA: IconData
    DNA_OFF: IconData
    DOCK: IconData
    DOG: IconData
    DOLLAR_SIGN: IconData
    DOME: IconData
    DONUT: IconData
    DOOR_CLOSED: IconData
    DOOR_CLOSED_LOCKED: IconData
    DOOR_OPEN: IconData
    DOOR_STAIRWELL: IconData
    DOT: IconData
    DOT_SQUARE: IconData
    DOWNLOAD: IconData
    DOWNLOAD_CLOUD: IconData
    DRAFTING_COMPASS: IconData
    DRAMA: IconData
    DRILL: IconData
    DRONE: IconData
    DROPLET: IconData
    DROPLET_OFF: IconData
    DROPLETS: IconData
    DRUM: IconData
    DRUMSTICK: IconData
    DUMBBELL: IconData
    EAR: IconData
    EAR_OFF: IconData
    EARTH: IconData
    EARTH_LOCK: IconData
    ECLIPSE: IconData
    EDIT: IconData
    EDIT_2: IconData
    EDIT_3: IconData
    EGG: IconData
    EGG_FRIED: IconData
    EGG_OFF: IconData
    EJECT: IconData
    ELLIPSE: IconData
    ELLIPSIS: IconData
    ELLIPSIS_VERTICAL: IconData
    ENGINE: IconData
    EQUAL: IconData
    EQUAL_APPROXIMATELY: IconData
    EQUAL_APPROXIMATELY_NOT: IconData
    EQUAL_NOT: IconData
    EQUAL_SQUARE: IconData
    ERASER: IconData
    ETHERNET_PORT: IconData
    EURO: IconData
    EV_CHARGER: IconData
    EXPAND: IconData
    EXTERNAL_LINK: IconData
    EYE: IconData
    EYE_CLOSED: IconData
    EYE_DASHED: IconData
    EYE_OFF: IconData
    FACE_ANGRY: IconData
    FACE_EXPRESSIONLESS: IconData
    FACE_GRINNING: IconData
    FACE_NEUTRAL: IconData
    FACE_SLIGHTLY_FROWNING: IconData
    FACE_SLIGHTLY_SMILING: IconData
    FACE_SLIGHTLY_SMILING_PLUS: IconData
    FACTORY: IconData
    FAN: IconData
    FAST_FORWARD: IconData
    FEATHER: IconData
    FENCE: IconData
    FERRIS_WHEEL: IconData
    FILE: IconData
    FILE_ARCHIVE: IconData
    FILE_AUDIO: IconData
    FILE_AUDIO_2: IconData
    FILE_AXIS_3_D: IconData
    FILE_AXIS_3D: IconData
    FILE_BADGE: IconData
    FILE_BADGE_2: IconData
    FILE_BAR_CHART: IconData
    FILE_BAR_CHART_2: IconData
    FILE_BOX: IconData
    FILE_BRACES: IconData
    FILE_BRACES_CORNER: IconData
    FILE_CHART_COLUMN: IconData
    FILE_CHART_COLUMN_INCREASING: IconData
    FILE_CHART_LINE: IconData
    FILE_CHART_PIE: IconData
    FILE_CHECK: IconData
    FILE_CHECK_2: IconData
    FILE_CHECK_CORNER: IconData
    FILE_CLOCK: IconData
    FILE_CODE: IconData
    FILE_CODE_2: IconData
    FILE_CODE_CORNER: IconData
    FILE_COG: IconData
    FILE_COG_2: IconData
    FILE_DIFF: IconData
    FILE_DIGIT: IconData
    FILE_DOWN: IconData
    FILE_EDIT: IconData
    FILE_EXCLAMATION_POINT: IconData
    FILE_HEADPHONE: IconData
    FILE_HEART: IconData
    FILE_IMAGE: IconData
    FILE_INPUT: IconData
    FILE_JSON: IconData
    FILE_JSON_2: IconData
    FILE_KEY: IconData
    FILE_KEY_2: IconData
    FILE_LINE_CHART: IconData
    FILE_LOCK: IconData
    FILE_LOCK_2: IconData
    FILE_MINUS: IconData
    FILE_MINUS_2: IconData
    FILE_MINUS_CORNER: IconData
    FILE_MUSIC: IconData
    FILE_OUTPUT: IconData
    FILE_PEN: IconData
    FILE_PEN_LINE: IconData
    FILE_PIE_CHART: IconData
    FILE_PLAY: IconData
    FILE_PLUS: IconData
    FILE_PLUS_2: IconData
    FILE_PLUS_CORNER: IconData
    FILE_QUESTION: IconData
    FILE_QUESTION_MARK: IconData
    FILE_SCAN: IconData
    FILE_SEARCH: IconData
    FILE_SEARCH_2: IconData
    FILE_SEARCH_CORNER: IconData
    FILE_SIGNAL: IconData
    FILE_SIGNATURE: IconData
    FILE_SLIDERS: IconData
    FILE_SPREADSHEET: IconData
    FILE_STACK: IconData
    FILE_SYMLINK: IconData
    FILE_TERMINAL: IconData
    FILE_TEXT: IconData
    FILE_TYPE: IconData
    FILE_TYPE_2: IconData
    FILE_TYPE_CORNER: IconData
    FILE_UP: IconData
    FILE_USER: IconData
    FILE_VIDEO: IconData
    FILE_VIDEO_2: IconData
    FILE_VIDEO_CAMERA: IconData
    FILE_VOLUME: IconData
    FILE_VOLUME_2: IconData
    FILE_WARNING: IconData
    FILE_X: IconData
    FILE_X_2: IconData
    FILE_XCORNER: IconData
    FILES: IconData
    FILM: IconData
    FILTER: IconData
    FILTER_X: IconData
    FINGERPRINT: IconData
    FINGERPRINT_PATTERN: IconData
    FIRE_EXTINGUISHER: IconData
    FISH: IconData
    FISH_OFF: IconData
    FISH_SYMBOL: IconData
    FISHING_HOOK: IconData
    FISHING_ROD: IconData
    FLAG: IconData
    FLAG_OFF: IconData
    FLAG_TRIANGLE_LEFT: IconData
    FLAG_TRIANGLE_RIGHT: IconData
    FLAME: IconData
    FLAME_KINDLING: IconData
    FLASHLIGHT: IconData
    FLASHLIGHT_OFF: IconData
    FLASK_CONICAL: IconData
    FLASK_CONICAL_OFF: IconData
    FLASK_ROUND: IconData
    FLIP_HORIZONTAL: IconData
    FLIP_HORIZONTAL_2: IconData
    FLIP_VERTICAL: IconData
    FLIP_VERTICAL_2: IconData
    FLOWER: IconData
    FLOWER_2: IconData
    FOCUS: IconData
    FOLD_HORIZONTAL: IconData
    FOLD_VERTICAL: IconData
    FOLDER: IconData
    FOLDER_ARCHIVE: IconData
    FOLDER_BOOKMARK: IconData
    FOLDER_CHECK: IconData
    FOLDER_CLOCK: IconData
    FOLDER_CLOSED: IconData
    FOLDER_CODE: IconData
    FOLDER_COG: IconData
    FOLDER_COG_2: IconData
    FOLDER_DOT: IconData
    FOLDER_DOWN: IconData
    FOLDER_EDIT: IconData
    FOLDER_GIT: IconData
    FOLDER_GIT_2: IconData
    FOLDER_HEART: IconData
    FOLDER_INPUT: IconData
    FOLDER_KANBAN: IconData
    FOLDER_KEY: IconData
    FOLDER_LOCK: IconData
    FOLDER_MINUS: IconData
    FOLDER_OPEN: IconData
    FOLDER_OPEN_DOT: IconData
    FOLDER_OUTPUT: IconData
    FOLDER_PEN: IconData
    FOLDER_PLUS: IconData
    FOLDER_ROOT: IconData
    FOLDER_SEARCH: IconData
    FOLDER_SEARCH_2: IconData
    FOLDER_SYMLINK: IconData
    FOLDER_SYNC: IconData
    FOLDER_TREE: IconData
    FOLDER_UP: IconData
    FOLDER_X: IconData
    FOLDERS: IconData
    FOOTPRINTS: IconData
    FORK_KNIFE: IconData
    FORK_KNIFE_CROSSED: IconData
    FORKLIFT: IconData
    FORM: IconData
    FORM_INPUT: IconData
    FORWARD: IconData
    FRAME: IconData
    FROWN: IconData
    FUEL: IconData
    FULLSCREEN: IconData
    FUNCTION_SQUARE: IconData
    FUNNEL: IconData
    FUNNEL_PLUS: IconData
    FUNNEL_X: IconData
    GALAXY: IconData
    GALLERY_HORIZONTAL: IconData
    GALLERY_HORIZONTAL_END: IconData
    GALLERY_THUMBNAILS: IconData
    GALLERY_VERTICAL: IconData
    GALLERY_VERTICAL_END: IconData
    GAMEPAD: IconData
    GAMEPAD_2: IconData
    GAMEPAD_DIRECTIONAL: IconData
    GANTT_CHART: IconData
    GANTT_CHART_SQUARE: IconData
    GAP_HORIZONTAL: IconData
    GAP_VERTICAL: IconData
    GAUGE: IconData
    GAUGE_CIRCLE: IconData
    GAVEL: IconData
    GEM: IconData
    GEORGIAN_LARI: IconData
    GERM: IconData
    GERM_OFF: IconData
    GHOST: IconData
    GIFT: IconData
    GIT_BRANCH: IconData
    GIT_BRANCH_MINUS: IconData
    GIT_BRANCH_PLUS: IconData
    GIT_COMMIT: IconData
    GIT_COMMIT_HORIZONTAL: IconData
    GIT_COMMIT_VERTICAL: IconData
    GIT_COMPARE: IconData
    GIT_COMPARE_ARROWS: IconData
    GIT_FORK: IconData
    GIT_GRAPH: IconData
    GIT_MERGE: IconData
    GIT_MERGE_CONFLICT: IconData
    GIT_PULL_REQUEST: IconData
    GIT_PULL_REQUEST_ARROW: IconData
    GIT_PULL_REQUEST_CLOSED: IconData
    GIT_PULL_REQUEST_CREATE: IconData
    GIT_PULL_REQUEST_CREATE_ARROW: IconData
    GIT_PULL_REQUEST_DRAFT: IconData
    GLASS_WATER: IconData
    GLASSES: IconData
    GLOBE: IconData
    GLOBE_2: IconData
    GLOBE_CHECK: IconData
    GLOBE_CODE: IconData
    GLOBE_LOCK: IconData
    GLOBE_OFF: IconData
    GLOBE_X: IconData
    GOAL: IconData
    GPU: IconData
    GRAB: IconData
    GRADUATION_CAP: IconData
    GRAPE: IconData
    GRID: IconData
    GRID_2_X_2: IconData
    GRID_2_X_2_CHECK: IconData
    GRID_2_X_2_PLUS: IconData
    GRID_2_X_2_X: IconData
    GRID_2X_2: IconData
    GRID_2X_2_CHECK: IconData
    GRID_2X_2_PLUS: IconData
    GRID_2X_2_X: IconData
    GRID_3_X_3: IconData
    GRID_3X_2: IconData
    GRID_3X_3: IconData
    GRIP: IconData
    GRIP_HORIZONTAL: IconData
    GRIP_VERTICAL: IconData
    GROUP: IconData
    GUITAR: IconData
    HAM: IconData
    HAMBURGER: IconData
    HAMMER: IconData
    HAND: IconData
    HAND_COINS: IconData
    HAND_FIST: IconData
    HAND_GRAB: IconData
    HAND_HEART: IconData
    HAND_HELPING: IconData
    HAND_METAL: IconData
    HAND_PLATTER: IconData
    HANDBAG: IconData
    HANDSHAKE: IconData
    HARD_DRIVE: IconData
    HARD_DRIVE_DOWNLOAD: IconData
    HARD_DRIVE_UPLOAD: IconData
    HARD_HAT: IconData
    HASH: IconData
    HAT_GLASSES: IconData
    HAZE: IconData
    HD: IconData
    HDMI_PORT: IconData
    HEADING: IconData
    HEADING_1: IconData
    HEADING_2: IconData
    HEADING_3: IconData
    HEADING_4: IconData
    HEADING_5: IconData
    HEADING_6: IconData
    HEADPHONE_OFF: IconData
    HEADPHONES: IconData
    HEADSET: IconData
    HEART: IconData
    HEART_CRACK: IconData
    HEART_HANDSHAKE: IconData
    HEART_MINUS: IconData
    HEART_OFF: IconData
    HEART_PLUS: IconData
    HEART_PULSE: IconData
    HEART_X: IconData
    HEATER: IconData
    HELICOPTER: IconData
    HELP_CIRCLE: IconData
    HELPING_HAND: IconData
    HEXAGON: IconData
    HIGHLIGHTER: IconData
    HISTORY: IconData
    HOME: IconData
    HOP: IconData
    HOP_OFF: IconData
    HOSPITAL: IconData
    HOTEL: IconData
    HOURGLASS: IconData
    HOURGLASS_COG: IconData
    HOUSE: IconData
    HOUSE_HEART: IconData
    HOUSE_PLUG: IconData
    HOUSE_PLUS: IconData
    HOUSE_WIFI: IconData
    HOUSES: IconData
    ICE_CREAM: IconData
    ICE_CREAM_2: IconData
    ICE_CREAM_BOWL: IconData
    ICE_CREAM_CONE: IconData
    ID_CARD: IconData
    ID_CARD_LANYARD: IconData
    IMAGE: IconData
    IMAGE_DOWN: IconData
    IMAGE_MINUS: IconData
    IMAGE_OFF: IconData
    IMAGE_PLAY: IconData
    IMAGE_PLUS: IconData
    IMAGE_UP: IconData
    IMAGE_UPSCALE: IconData
    IMAGES: IconData
    IMPORT: IconData
    INBOX: IconData
    INDENT: IconData
    INDENT_DECREASE: IconData
    INDENT_INCREASE: IconData
    INDIAN_RUPEE: IconData
    INFINITY: IconData
    INFO: IconData
    INSPECT: IconData
    INSPECTION_PANEL: IconData
    ITALIC: IconData
    ITERATION_CCW: IconData
    ITERATION_CW: IconData
    IV_BAG: IconData
    JAPANESE_YEN: IconData
    JOYSTICK: IconData
    KANBAN: IconData
    KANBAN_SQUARE: IconData
    KANBAN_SQUARE_DASHED: IconData
    KAYAK: IconData
    KEY: IconData
    KEY_ROUND: IconData
    KEY_SQUARE: IconData
    KEYBOARD: IconData
    KEYBOARD_MUSIC: IconData
    KEYBOARD_OFF: IconData
    LAMP: IconData
    LAMP_CEILING: IconData
    LAMP_DESK: IconData
    LAMP_FLOOR: IconData
    LAMP_WALL_DOWN: IconData
    LAMP_WALL_UP: IconData
    LAND_PLOT: IconData
    LANDMARK: IconData
    LANGUAGES: IconData
    LAPTOP: IconData
    LAPTOP_2: IconData
    LAPTOP_MINIMAL: IconData
    LAPTOP_MINIMAL_CHECK: IconData
    LASSO: IconData
    LASSO_SELECT: IconData
    LAUGH: IconData
    LAYER_ARROW_DOWN: IconData
    LAYER_ARROW_UP: IconData
    LAYERS: IconData
    LAYERS_2: IconData
    LAYERS_3: IconData
    LAYERS_ARROW_DOWN: IconData
    LAYERS_ARROW_UP: IconData
    LAYERS_MINUS: IconData
    LAYERS_PLUS: IconData
    LAYOUT: IconData
    LAYOUT_ARROW_DOWN: IconData
    LAYOUT_ARROW_RIGHT: IconData
    LAYOUT_DASHBOARD: IconData
    LAYOUT_FREEFORM: IconData
    LAYOUT_GRID: IconData
    LAYOUT_LIST: IconData
    LAYOUT_PANEL_LEFT: IconData
    LAYOUT_PANEL_TOP: IconData
    LAYOUT_TEMPLATE: IconData
    LEAF: IconData
    LEAFY_GREEN: IconData
    LECTERN: IconData
    LENS_CONCAVE: IconData
    LENS_CONVEX: IconData
    LETTER_TEXT: IconData
    LIBRARY: IconData
    LIBRARY_BIG: IconData
    LIBRARY_SQUARE: IconData
    LIFE_BUOY: IconData
    LIGATURE: IconData
    LIGHTBULB: IconData
    LIGHTBULB_OFF: IconData
    LIGHTHOUSE: IconData
    LINE_CHART: IconData
    LINE_DOT_RIGHT_HORIZONTAL: IconData
    LINE_SQUIGGLE: IconData
    LINE_STYLE: IconData
    LINK: IconData
    LINK_2: IconData
    LINK_2_OFF: IconData
    LIST: IconData
    LIST_CHECK: IconData
    LIST_CHECKS: IconData
    LIST_CHEVRONS_DOWN_UP: IconData
    LIST_CHEVRONS_UP_DOWN: IconData
    LIST_CLOCK: IconData
    LIST_COLLAPSE: IconData
    LIST_END: IconData
    LIST_FILTER: IconData
    LIST_FILTER_PLUS: IconData
    LIST_INDENT_DECREASE: IconData
    LIST_INDENT_INCREASE: IconData
    LIST_MINUS: IconData
    LIST_MUSIC: IconData
    LIST_ORDERED: IconData
    LIST_PLUS: IconData
    LIST_RESTART: IconData
    LIST_SORT_ASCENDING: IconData
    LIST_SORT_DESCENDING: IconData
    LIST_START: IconData
    LIST_TODO: IconData
    LIST_TREE: IconData
    LIST_VIDEO: IconData
    LIST_X: IconData
    LOADER: IconData
    LOADER_2: IconData
    LOADER_CIRCLE: IconData
    LOADER_PINWHEEL: IconData
    LOCATE: IconData
    LOCATE_FIXED: IconData
    LOCATE_OFF: IconData
    LOCATION_EDIT: IconData
    LOCK: IconData
    LOCK_KEYHOLE: IconData
    LOCK_KEYHOLE_OPEN: IconData
    LOCK_OPEN: IconData
    LOG_IN: IconData
    LOG_OUT: IconData
    LOGS: IconData
    LOLLIPOP: IconData
    LUGGAGE: IconData
    M_SQUARE: IconData
    MAGNET: IconData
    MAIL: IconData
    MAIL_BADGE: IconData
    MAIL_CHECK: IconData
    MAIL_CLOCK: IconData
    MAIL_MINUS: IconData
    MAIL_OPEN: IconData
    MAIL_PEN: IconData
    MAIL_PLUS: IconData
    MAIL_QUESTION: IconData
    MAIL_QUESTION_MARK: IconData
    MAIL_SEARCH: IconData
    MAIL_WARNING: IconData
    MAIL_X: IconData
    MAILBOX: IconData
    MAILS: IconData
    MAP: IconData
    MAP_MINUS: IconData
    MAP_PIN: IconData
    MAP_PIN_CHECK: IconData
    MAP_PIN_CHECK_INSIDE: IconData
    MAP_PIN_HOUSE: IconData
    MAP_PIN_MINUS: IconData
    MAP_PIN_MINUS_INSIDE: IconData
    MAP_PIN_OFF: IconData
    MAP_PIN_PEN: IconData
    MAP_PIN_PLUS: IconData
    MAP_PIN_PLUS_INSIDE: IconData
    MAP_PIN_SEARCH: IconData
    MAP_PIN_X: IconData
    MAP_PIN_XINSIDE: IconData
    MAP_PINNED: IconData
    MAP_PLUS: IconData
    MARS: IconData
    MARS_STROKE: IconData
    MARTINI: IconData
    MAXIMIZE: IconData
    MAXIMIZE_2: IconData
    MEDAL: IconData
    MEGAPHONE: IconData
    MEGAPHONE_OFF: IconData
    MEH: IconData
    MEMORY_STICK: IconData
    MENU: IconData
    MENU_SQUARE: IconData
    MERGE: IconData
    MESSAGE_CIRCLE: IconData
    MESSAGE_CIRCLE_CHECK: IconData
    MESSAGE_CIRCLE_CODE: IconData
    MESSAGE_CIRCLE_DASHED: IconData
    MESSAGE_CIRCLE_DASHED_CHECK: IconData
    MESSAGE_CIRCLE_HEART: IconData
    MESSAGE_CIRCLE_MORE: IconData
    MESSAGE_CIRCLE_OFF: IconData
    MESSAGE_CIRCLE_PLUS: IconData
    MESSAGE_CIRCLE_QUESTION: IconData
    MESSAGE_CIRCLE_QUESTION_MARK: IconData
    MESSAGE_CIRCLE_REPLY: IconData
    MESSAGE_CIRCLE_WARNING: IconData
    MESSAGE_CIRCLE_X: IconData
    MESSAGE_SQUARE: IconData
    MESSAGE_SQUARE_CHECK: IconData
    MESSAGE_SQUARE_CODE: IconData
    MESSAGE_SQUARE_DASHED: IconData
    MESSAGE_SQUARE_DIFF: IconData
    MESSAGE_SQUARE_DOT: IconData
    MESSAGE_SQUARE_HEART: IconData
    MESSAGE_SQUARE_LOCK: IconData
    MESSAGE_SQUARE_MORE: IconData
    MESSAGE_SQUARE_OFF: IconData
    MESSAGE_SQUARE_PLUS: IconData
    MESSAGE_SQUARE_QUOTE: IconData
    MESSAGE_SQUARE_REPLY: IconData
    MESSAGE_SQUARE_SHARE: IconData
    MESSAGE_SQUARE_TEXT: IconData
    MESSAGE_SQUARE_WARNING: IconData
    MESSAGE_SQUARE_X: IconData
    MESSAGES_CIRCLE: IconData
    MESSAGES_SQUARE: IconData
    METRONOME: IconData
    MIC: IconData
    MIC_2: IconData
    MIC_AUDIO_LINES: IconData
    MIC_OFF: IconData
    MIC_SIGNAL: IconData
    MIC_VOCAL: IconData
    MICROCHIP: IconData
    MICROSCOPE: IconData
    MICROWAVE: IconData
    MIDI_PORT: IconData
    MILESTONE: IconData
    MILK: IconData
    MILK_OFF: IconData
    MINIMIZE: IconData
    MINIMIZE_2: IconData
    MINUS: IconData
    MINUS_CIRCLE: IconData
    MINUS_SQUARE: IconData
    MIRROR_RECTANGULAR: IconData
    MIRROR_ROUND: IconData
    MONITOR: IconData
    MONITOR_CHECK: IconData
    MONITOR_CLOUD: IconData
    MONITOR_COG: IconData
    MONITOR_DOT: IconData
    MONITOR_DOWN: IconData
    MONITOR_OFF: IconData
    MONITOR_PAUSE: IconData
    MONITOR_PC: IconData
    MONITOR_PLAY: IconData
    MONITOR_SMARTPHONE: IconData
    MONITOR_SPEAKER: IconData
    MONITOR_STOP: IconData
    MONITOR_UP: IconData
    MONITOR_X: IconData
    MOON: IconData
    MOON_STAR: IconData
    MOP: IconData
    MOP_SPARKLES: IconData
    MORE_HORIZONTAL: IconData
    MORE_VERTICAL: IconData
    MOSQUE: IconData
    MOTORBIKE: IconData
    MOUNTAIN: IconData
    MOUNTAIN_SNOW: IconData
    MOUSE: IconData
    MOUSE_LEFT: IconData
    MOUSE_OFF: IconData
    MOUSE_POINTER: IconData
    MOUSE_POINTER_2: IconData
    MOUSE_POINTER_2_OFF: IconData
    MOUSE_POINTER_BAN: IconData
    MOUSE_POINTER_CLICK: IconData
    MOUSE_POINTER_SQUARE_DASHED: IconData
    MOUSE_RIGHT: IconData
    MOUTH: IconData
    MOUTH_OFF: IconData
    MOVE: IconData
    MOVE_3_D: IconData
    MOVE_3D: IconData
    MOVE_DIAGONAL: IconData
    MOVE_DIAGONAL_2: IconData
    MOVE_DOWN: IconData
    MOVE_DOWN_LEFT: IconData
    MOVE_DOWN_RIGHT: IconData
    MOVE_HORIZONTAL: IconData
    MOVE_LEFT: IconData
    MOVE_RIGHT: IconData
    MOVE_UP: IconData
    MOVE_UP_LEFT: IconData
    MOVE_UP_RIGHT: IconData
    MOVE_VERTICAL: IconData
    MUSIC: IconData
    MUSIC_2: IconData
    MUSIC_3: IconData
    MUSIC_4: IconData
    NAVIGATION: IconData
    NAVIGATION_2: IconData
    NAVIGATION_2_OFF: IconData
    NAVIGATION_OFF: IconData
    NETWORK: IconData
    NEWSPAPER: IconData
    NFC: IconData
    NON_BINARY: IconData
    NOTEBOOK: IconData
    NOTEBOOK_DOT: IconData
    NOTEBOOK_PEN: IconData
    NOTEBOOK_TABS: IconData
    NOTEBOOK_TEXT: IconData
    NOTEPAD_TEXT: IconData
    NOTEPAD_TEXT_DASHED: IconData
    NUT: IconData
    NUT_OFF: IconData
    OCTAGON: IconData
    OCTAGON_ALERT: IconData
    OCTAGON_MINUS: IconData
    OCTAGON_PAUSE: IconData
    OCTAGON_X: IconData
    OMEGA: IconData
    OPTION: IconData
    ORBIT: IconData
    ORIGAMI: IconData
    OUTDENT: IconData
    PACKAGE: IconData
    PACKAGE_2: IconData
    PACKAGE_CHECK: IconData
    PACKAGE_MINUS: IconData
    PACKAGE_OPEN: IconData
    PACKAGE_PLUS: IconData
    PACKAGE_SEARCH: IconData
    PACKAGE_X: IconData
    PAINT_BUCKET: IconData
    PAINT_ROLLER: IconData
    PAINTBRUSH: IconData
    PAINTBRUSH_2: IconData
    PAINTBRUSH_VERTICAL: IconData
    PALETTE: IconData
    PALMTREE: IconData
    PANDA: IconData
    PANEL_BOTTOM: IconData
    PANEL_BOTTOM_CLOSE: IconData
    PANEL_BOTTOM_DASHED: IconData
    PANEL_BOTTOM_INACTIVE: IconData
    PANEL_BOTTOM_OPEN: IconData
    PANEL_LEFT: IconData
    PANEL_LEFT_CLOSE: IconData
    PANEL_LEFT_DASHED: IconData
    PANEL_LEFT_INACTIVE: IconData
    PANEL_LEFT_OPEN: IconData
    PANEL_LEFT_RIGHT_DASHED: IconData
    PANEL_RIGHT: IconData
    PANEL_RIGHT_CLOSE: IconData
    PANEL_RIGHT_DASHED: IconData
    PANEL_RIGHT_INACTIVE: IconData
    PANEL_RIGHT_OPEN: IconData
    PANEL_TOP: IconData
    PANEL_TOP_BOTTOM_DASHED: IconData
    PANEL_TOP_CLOSE: IconData
    PANEL_TOP_DASHED: IconData
    PANEL_TOP_INACTIVE: IconData
    PANEL_TOP_OPEN: IconData
    PANELS_LEFT_BOTTOM: IconData
    PANELS_LEFT_RIGHT: IconData
    PANELS_RIGHT_BOTTOM: IconData
    PANELS_TOP_BOTTOM: IconData
    PANELS_TOP_LEFT: IconData
    PAPER_BAG: IconData
    PAPERCLIP: IconData
    PARASOL: IconData
    PARENTHESES: IconData
    PARK: IconData
    PARKING_CIRCLE: IconData
    PARKING_CIRCLE_OFF: IconData
    PARKING_METER: IconData
    PARKING_SQUARE: IconData
    PARKING_SQUARE_OFF: IconData
    PARTY_POPPER: IconData
    PAUSE: IconData
    PAUSE_CIRCLE: IconData
    PAUSE_OCTAGON: IconData
    PAW_PRINT: IconData
    PC_CASE: IconData
    PEN: IconData
    PEN_BOX: IconData
    PEN_LINE: IconData
    PEN_OFF: IconData
    PEN_SQUARE: IconData
    PEN_TOOL: IconData
    PENCIL: IconData
    PENCIL_LINE: IconData
    PENCIL_OFF: IconData
    PENCIL_RULER: IconData
    PENCIL_SPARKLES: IconData
    PENTAGON: IconData
    PERCENT: IconData
    PERCENT_CIRCLE: IconData
    PERCENT_DIAMOND: IconData
    PERCENT_SQUARE: IconData
    PERSON_STANDING: IconData
    PHI: IconData
    PHILIPPINE_PESO: IconData
    PHONE: IconData
    PHONE_CALL: IconData
    PHONE_FORWARDED: IconData
    PHONE_INCOMING: IconData
    PHONE_MISSED: IconData
    PHONE_OFF: IconData
    PHONE_OUTGOING: IconData
    PI: IconData
    PI_SQUARE: IconData
    PIANO: IconData
    PICKAXE: IconData
    PICTURE_IN_PICTURE: IconData
    PICTURE_IN_PICTURE_2: IconData
    PIE_CHART: IconData
    PIGGY_BANK: IconData
    PILCROW: IconData
    PILCROW_LEFT: IconData
    PILCROW_RIGHT: IconData
    PILCROW_SQUARE: IconData
    PILL: IconData
    PILL_BOTTLE: IconData
    PIN: IconData
    PIN_OFF: IconData
    PIPETTE: IconData
    PIZZA: IconData
    PLANE: IconData
    PLANE_LANDING: IconData
    PLANE_TAKEOFF: IconData
    PLANT_POT: IconData
    PLAY: IconData
    PLAY_CIRCLE: IconData
    PLAY_OFF: IconData
    PLAY_SQUARE: IconData
    PLAYING_CARD: IconData
    PLAYING_CARDS: IconData
    PLAYING_CARDS_FAN: IconData
    PLUG: IconData
    PLUG_2: IconData
    PLUG_ZAP: IconData
    PLUG_ZAP_2: IconData
    PLUS: IconData
    PLUS_CIRCLE: IconData
    PLUS_SQUARE: IconData
    POCKET_KNIFE: IconData
    PODCAST: IconData
    PODIUM: IconData
    POINTER: IconData
    POINTER_OFF: IconData
    POPCORN: IconData
    POPSICLE: IconData
    POUND_STERLING: IconData
    POWER: IconData
    POWER_CIRCLE: IconData
    POWER_OFF: IconData
    POWER_SQUARE: IconData
    PRESENTATION: IconData
    PRINTER: IconData
    PRINTER_CHECK: IconData
    PRINTER_X: IconData
    PROJECTOR: IconData
    PROPORTIONS: IconData
    PUZZLE: IconData
    PYRAMID: IconData
    QR_CODE: IconData
    QUOTE: IconData
    RABBIT: IconData
    RADAR: IconData
    RADIATION: IconData
    RADICAL: IconData
    RADIO: IconData
    RADIO_OFF: IconData
    RADIO_RECEIVER: IconData
    RADIO_TOWER: IconData
    RADIUS: IconData
    RAINBOW: IconData
    RAT: IconData
    RATIO: IconData
    RECEIPT: IconData
    RECEIPT_CENT: IconData
    RECEIPT_EURO: IconData
    RECEIPT_INDIAN_RUPEE: IconData
    RECEIPT_JAPANESE_YEN: IconData
    RECEIPT_POUND_STERLING: IconData
    RECEIPT_RUSSIAN_RUBLE: IconData
    RECEIPT_SWISS_FRANC: IconData
    RECEIPT_TEXT: IconData
    RECEIPT_TURKISH_LIRA: IconData
    RECTANGLE_CIRCLE: IconData
    RECTANGLE_ELLIPSIS: IconData
    RECTANGLE_GOGGLES: IconData
    RECTANGLE_HORIZONTAL: IconData
    RECTANGLE_VERTICAL: IconData
    RECYCLE: IconData
    REDO: IconData
    REDO_2: IconData
    REDO_DOT: IconData
    REFRESH_CCW: IconData
    REFRESH_CCW_DOT: IconData
    REFRESH_CW: IconData
    REFRESH_CW_OFF: IconData
    REFRIGERATOR: IconData
    REGEX: IconData
    REMOVE_FORMATTING: IconData
    REPEAT: IconData
    REPEAT_1: IconData
    REPEAT_2: IconData
    REPEAT_OFF: IconData
    REPLACE: IconData
    REPLACE_ALL: IconData
    REPLY: IconData
    REPLY_ALL: IconData
    REWIND: IconData
    RIBBON: IconData
    ROAD: IconData
    ROBOT_ARM: IconData
    ROBOT_VACUUM: IconData
    ROCKET: IconData
    ROCKING_CHAIR: IconData
    ROLLER_COASTER: IconData
    ROSE: IconData
    ROTATE_3_D: IconData
    ROTATE_3D: IconData
    ROTATE_CCW: IconData
    ROTATE_CCW_CLOCK: IconData
    ROTATE_CCW_KEY: IconData
    ROTATE_CCW_SQUARE: IconData
    ROTATE_CW: IconData
    ROTATE_CW_FADING_CLOCK: IconData
    ROTATE_CW_SQUARE: IconData
    ROUTE: IconData
    ROUTE_OFF: IconData
    ROUTER: IconData
    ROWS: IconData
    ROWS_2: IconData
    ROWS_3: IconData
    ROWS_4: IconData
    RSS: IconData
    RULER: IconData
    RULER_DIMENSION_LINE: IconData
    RUSSIAN_RUBLE: IconData
    SAILBOAT: IconData
    SALAD: IconData
    SANDWICH: IconData
    SATELLITE: IconData
    SATELLITE_DISH: IconData
    SAUDI_RIYAL: IconData
    SAVE: IconData
    SAVE_ALL: IconData
    SAVE_CHECK: IconData
    SAVE_OFF: IconData
    SAVE_PEN: IconData
    SAVE_PLUS: IconData
    SCALE: IconData
    SCALE_3_D: IconData
    SCALE_3D: IconData
    SCALING: IconData
    SCAN: IconData
    SCAN_BARCODE: IconData
    SCAN_BOX: IconData
    SCAN_EYE: IconData
    SCAN_FACE: IconData
    SCAN_HEART: IconData
    SCAN_LINE: IconData
    SCAN_QR_CODE: IconData
    SCAN_SEARCH: IconData
    SCAN_SQUARE: IconData
    SCAN_TEXT: IconData
    SCATTER_CHART: IconData
    SCHOOL: IconData
    SCHOOL_2: IconData
    SCISSORS: IconData
    SCISSORS_LINE_DASHED: IconData
    SCISSORS_SQUARE: IconData
    SCISSORS_SQUARE_DASHED_BOTTOM: IconData
    SCOOTER: IconData
    SCREEN_SHARE: IconData
    SCREEN_SHARE_OFF: IconData
    SCROLL: IconData
    SCROLL_TEXT: IconData
    SEARCH: IconData
    SEARCH_ALERT: IconData
    SEARCH_CHECK: IconData
    SEARCH_CODE: IconData
    SEARCH_SLASH: IconData
    SEARCH_X: IconData
    SECTION: IconData
    SEND: IconData
    SEND_HORIZONAL: IconData
    SEND_HORIZONTAL: IconData
    SEND_TO_BACK: IconData
    SEPARATOR_HORIZONTAL: IconData
    SEPARATOR_VERTICAL: IconData
    SERVER: IconData
    SERVER_COG: IconData
    SERVER_CRASH: IconData
    SERVER_OFF: IconData
    SERVER_PLUS: IconData
    SETTINGS: IconData
    SETTINGS_2: IconData
    SHAPES: IconData
    SHARE: IconData
    SHARE_2: IconData
    SHEET: IconData
    SHELL: IconData
    SHELVING_UNIT: IconData
    SHIELD: IconData
    SHIELD_ALERT: IconData
    SHIELD_BAN: IconData
    SHIELD_CHECK: IconData
    SHIELD_CLOSE: IconData
    SHIELD_COG: IconData
    SHIELD_COG_CORNER: IconData
    SHIELD_ELLIPSIS: IconData
    SHIELD_HALF: IconData
    SHIELD_KEYHOLE: IconData
    SHIELD_LOCK: IconData
    SHIELD_MINUS: IconData
    SHIELD_OFF: IconData
    SHIELD_PLUS: IconData
    SHIELD_QUESTION: IconData
    SHIELD_QUESTION_MARK: IconData
    SHIELD_USER: IconData
    SHIELD_X: IconData
    SHIP: IconData
    SHIP_CARGO: IconData
    SHIP_WHEEL: IconData
    SHIRT: IconData
    SHOPPING_BAG: IconData
    SHOPPING_BASKET: IconData
    SHOPPING_CART: IconData
    SHOPPING_CART_MINUS: IconData
    SHOPPING_CART_PLUS: IconData
    SHOVEL: IconData
    SHOWER_HEAD: IconData
    SHREDDER: IconData
    SHRIMP: IconData
    SHRIMP_OFF: IconData
    SHRINK: IconData
    SHRUB: IconData
    SHUFFLE: IconData
    SIDEBAR: IconData
    SIDEBAR_CLOSE: IconData
    SIDEBAR_OPEN: IconData
    SIGMA: IconData
    SIGMA_SQUARE: IconData
    SIGNAL: IconData
    SIGNAL_HIGH: IconData
    SIGNAL_LOW: IconData
    SIGNAL_MEDIUM: IconData
    SIGNAL_ZERO: IconData
    SIGNATURE: IconData
    SIGNPOST: IconData
    SIGNPOST_BIG: IconData
    SIREN: IconData
    SKIP_BACK: IconData
    SKIP_FORWARD: IconData
    SKULL: IconData
    SLASH: IconData
    SLASH_SQUARE: IconData
    SLICE: IconData
    SLIDERS: IconData
    SLIDERS_HORIZONTAL: IconData
    SLIDERS_VERTICAL: IconData
    SMARTPHONE: IconData
    SMARTPHONE_CHARGING: IconData
    SMARTPHONE_NFC: IconData
    SMILE: IconData
    SMILE_PLUS: IconData
    SNAIL: IconData
    SNOWFLAKE: IconData
    SOAP_DISPENSER_DROPLET: IconData
    SOFA: IconData
    SOLAR_PANEL: IconData
    SORT_ASC: IconData
    SORT_DESC: IconData
    SOUP: IconData
    SPACE: IconData
    SPADE: IconData
    SPARKLE: IconData
    SPARKLES: IconData
    SPEAKER: IconData
    SPEECH: IconData
    SPELL_CHECK: IconData
    SPELL_CHECK_2: IconData
    SPLINE: IconData
    SPLINE_POINTER: IconData
    SPLIT: IconData
    SPLIT_SQUARE_HORIZONTAL: IconData
    SPLIT_SQUARE_VERTICAL: IconData
    SPOOL: IconData
    SPORT_SHOE: IconData
    SPOTLIGHT: IconData
    SPRAY_CAN: IconData
    SPROUT: IconData
    SQUARE: IconData
    SQUARE_ACTIVITY: IconData
    SQUARE_ARROW_DOWN: IconData
    SQUARE_ARROW_DOWN_LEFT: IconData
    SQUARE_ARROW_DOWN_RIGHT: IconData
    SQUARE_ARROW_LEFT: IconData
    SQUARE_ARROW_OUT_DOWN_LEFT: IconData
    SQUARE_ARROW_OUT_DOWN_RIGHT: IconData
    SQUARE_ARROW_OUT_UP_LEFT: IconData
    SQUARE_ARROW_OUT_UP_RIGHT: IconData
    SQUARE_ARROW_RIGHT: IconData
    SQUARE_ARROW_RIGHT_ENTER: IconData
    SQUARE_ARROW_RIGHT_EXIT: IconData
    SQUARE_ARROW_UP: IconData
    SQUARE_ARROW_UP_LEFT: IconData
    SQUARE_ARROW_UP_RIGHT: IconData
    SQUARE_ASTERISK: IconData
    SQUARE_BOOKMARK: IconData
    SQUARE_BOTTOM_DASHED_SCISSORS: IconData
    SQUARE_CENTERLINE_DASHED_HORIZONTAL: IconData
    SQUARE_CENTERLINE_DASHED_VERTICAL: IconData
    SQUARE_CHART_GANTT: IconData
    SQUARE_CHECK: IconData
    SQUARE_CHECK_BIG: IconData
    SQUARE_CHEVRON_DOWN: IconData
    SQUARE_CHEVRON_LEFT: IconData
    SQUARE_CHEVRON_RIGHT: IconData
    SQUARE_CHEVRON_UP: IconData
    SQUARE_CODE: IconData
    SQUARE_DASHED: IconData
    SQUARE_DASHED_BOTTOM: IconData
    SQUARE_DASHED_BOTTOM_CODE: IconData
    SQUARE_DASHED_KANBAN: IconData
    SQUARE_DASHED_MOUSE_POINTER: IconData
    SQUARE_DASHED_TEXT: IconData
    SQUARE_DASHED_TOP_SOLID: IconData
    SQUARE_DIMENSIONS: IconData
    SQUARE_DIVIDE: IconData
    SQUARE_DOT: IconData
    SQUARE_EQUAL: IconData
    SQUARE_EXCLAMATION_POINT: IconData
    SQUARE_FUNCTION: IconData
    SQUARE_GANTT_CHART: IconData
    SQUARE_KANBAN: IconData
    SQUARE_LIBRARY: IconData
    SQUARE_M: IconData
    SQUARE_MENU: IconData
    SQUARE_MINUS: IconData
    SQUARE_MOUSE_POINTER: IconData
    SQUARE_OFF: IconData
    SQUARE_PARKING: IconData
    SQUARE_PARKING_OFF: IconData
    SQUARE_PAUSE: IconData
    SQUARE_PEN: IconData
    SQUARE_PERCENT: IconData
    SQUARE_PI: IconData
    SQUARE_PILCROW: IconData
    SQUARE_PLAY: IconData
    SQUARE_PLUS: IconData
    SQUARE_POWER: IconData
    SQUARE_RADICAL: IconData
    SQUARE_ROUND_CORNER: IconData
    SQUARE_SCISSORS: IconData
    SQUARE_SIGMA: IconData
    SQUARE_SLASH: IconData
    SQUARE_SPLIT_HORIZONTAL: IconData
    SQUARE_SPLIT_VERTICAL: IconData
    SQUARE_SQUARE: IconData
    SQUARE_STACK: IconData
    SQUARE_STAR: IconData
    SQUARE_STOP: IconData
    SQUARE_TERMINAL: IconData
    SQUARE_TEXT: IconData
    SQUARE_USER: IconData
    SQUARE_USER_ROUND: IconData
    SQUARE_X: IconData
    SQUARES_EXCLUDE: IconData
    SQUARES_INTERSECT: IconData
    SQUARES_SUBTRACT: IconData
    SQUARES_UNITE: IconData
    SQUIRCLE: IconData
    SQUIRCLE_DASHED: IconData
    SQUIRREL: IconData
    STAMP: IconData
    STAR: IconData
    STAR_CHECK: IconData
    STAR_HALF: IconData
    STAR_MINUS: IconData
    STAR_OFF: IconData
    STAR_PLUS: IconData
    STAR_X: IconData
    STARS: IconData
    STEP_BACK: IconData
    STEP_FORWARD: IconData
    STETHOSCOPE: IconData
    STICKER: IconData
    STICKY_NOTE: IconData
    STICKY_NOTE_CHECK: IconData
    STICKY_NOTE_MINUS: IconData
    STICKY_NOTE_OFF: IconData
    STICKY_NOTE_PLUS: IconData
    STICKY_NOTE_X: IconData
    STICKY_NOTES: IconData
    STONE: IconData
    STOP_CIRCLE: IconData
    STORE: IconData
    STRETCH_HORIZONTAL: IconData
    STRETCH_VERTICAL: IconData
    STRIKETHROUGH: IconData
    SUBSCRIPT: IconData
    SUBTITLES: IconData
    SUMMARY: IconData
    SUN: IconData
    SUN_DIM: IconData
    SUN_MEDIUM: IconData
    SUN_MOON: IconData
    SUN_SNOW: IconData
    SUNRISE: IconData
    SUNSET: IconData
    SUPERSCRIPT: IconData
    SWATCH_BOOK: IconData
    SWISS_FRANC: IconData
    SWITCH_CAMERA: IconData
    SWORD: IconData
    SWORDS: IconData
    SYRINGE: IconData
    TABLE: IconData
    TABLE_2: IconData
    TABLE_CELLS_MERGE: IconData
    TABLE_CELLS_SPLIT: IconData
    TABLE_COLUMNS_SPLIT: IconData
    TABLE_CONFIG: IconData
    TABLE_OF_CONTENTS: IconData
    TABLE_PROPERTIES: IconData
    TABLE_ROWS_SPLIT: IconData
    TABLET: IconData
    TABLET_SMARTPHONE: IconData
    TABLETS: IconData
    TAG: IconData
    TAG_PLUS: IconData
    TAG_X: IconData
    TAGS: IconData
    TALLY_1: IconData
    TALLY_2: IconData
    TALLY_3: IconData
    TALLY_4: IconData
    TALLY_5: IconData
    TANGENT: IconData
    TARGET: IconData
    TELESCOPE: IconData
    TENT: IconData
    TENT_TREE: IconData
    TERMINAL: IconData
    TERMINAL_SQUARE: IconData
    TEST_TUBE: IconData
    TEST_TUBE_2: IconData
    TEST_TUBE_DIAGONAL: IconData
    TEST_TUBES: IconData
    TEXT: IconData
    TEXT_ALIGN_CENTER: IconData
    TEXT_ALIGN_END: IconData
    TEXT_ALIGN_JUSTIFY: IconData
    TEXT_ALIGN_START: IconData
    TEXT_CURSOR: IconData
    TEXT_CURSOR_INPUT: IconData
    TEXT_INITIAL: IconData
    TEXT_QUOTE: IconData
    TEXT_SEARCH: IconData
    TEXT_SELECT: IconData
    TEXT_SELECTION: IconData
    TEXT_WRAP: IconData
    THEATER: IconData
    THERMOMETER: IconData
    THERMOMETER_SNOWFLAKE: IconData
    THERMOMETER_SUN: IconData
    THUMBS_DOWN: IconData
    THUMBS_UP: IconData
    TIC_TAC_TOE: IconData
    TICKET: IconData
    TICKET_CHECK: IconData
    TICKET_MINUS: IconData
    TICKET_PERCENT: IconData
    TICKET_PLUS: IconData
    TICKET_SLASH: IconData
    TICKET_X: IconData
    TICKETS: IconData
    TICKETS_PLANE: IconData
    TIMELINE: IconData
    TIMER: IconData
    TIMER_OFF: IconData
    TIMER_RESET: IconData
    TOGGLE_LEFT: IconData
    TOGGLE_RIGHT: IconData
    TOILET: IconData
    TOOL_CASE: IconData
    TOOLBOX: IconData
    TOOTHBRUSH: IconData
    TOOTHBRUSH_SPARKLES: IconData
    TORNADO: IconData
    TORUS: IconData
    TOUCHPAD: IconData
    TOUCHPAD_OFF: IconData
    TOWEL_RACK: IconData
    TOWER_CONTROL: IconData
    TOY_BRICK: IconData
    TRACTOR: IconData
    TRAFFIC_CONE: IconData
    TRAILER: IconData
    TRAIN: IconData
    TRAIN_FRONT: IconData
    TRAIN_FRONT_TUNNEL: IconData
    TRAIN_TRACK: IconData
    TRAM_FRONT: IconData
    TRANSGENDER: IconData
    TRASH: IconData
    TRASH_2: IconData
    TRASH_OFF: IconData
    TREE_DECIDUOUS: IconData
    TREE_PALM: IconData
    TREE_PINE: IconData
    TREES: IconData
    TRENDING_DOWN: IconData
    TRENDING_UP: IconData
    TRENDING_UP_DOWN: IconData
    TRIANGLE: IconData
    TRIANGLE_ALERT: IconData
    TRIANGLE_DASHED: IconData
    TRIANGLE_RIGHT: IconData
    TRIANGLES_CENTERLINE_DASHED_HORIZONTAL: IconData
    TRIANGLES_CENTERLINE_DASHED_VERTICAL: IconData
    TROPHY: IconData
    TRUCK: IconData
    TRUCK_ELECTRIC: IconData
    TURKISH_LIRA: IconData
    TURNTABLE: IconData
    TURTLE: IconData
    TV: IconData
    TV_2: IconData
    TV_MINIMAL: IconData
    TV_MINIMAL_PLAY: IconData
    TYPE: IconData
    TYPE_OUTLINE: IconData
    UMBRELLA: IconData
    UMBRELLA_OFF: IconData
    UNDERLINE: IconData
    UNDO: IconData
    UNDO_2: IconData
    UNDO_DOT: IconData
    UNFOLD_HORIZONTAL: IconData
    UNFOLD_VERTICAL: IconData
    UNGROUP: IconData
    UNIVERSITY: IconData
    UNLINK: IconData
    UNLINK_2: IconData
    UNLOCK: IconData
    UNLOCK_KEYHOLE: IconData
    UNPLUG: IconData
    UPLOAD: IconData
    UPLOAD_CLOUD: IconData
    USB: IconData
    USB_CPORT: IconData
    USER: IconData
    USER_2: IconData
    USER_CHECK: IconData
    USER_CHECK_2: IconData
    USER_CIRCLE: IconData
    USER_CIRCLE_2: IconData
    USER_COG: IconData
    USER_COG_2: IconData
    USER_GROUP: IconData
    USER_KEY: IconData
    USER_LOCK: IconData
    USER_MINUS: IconData
    USER_MINUS_2: IconData
    USER_PEN: IconData
    USER_PLUS: IconData
    USER_PLUS_2: IconData
    USER_ROUND: IconData
    USER_ROUND_ARROW_LEFT: IconData
    USER_ROUND_CHECK: IconData
    USER_ROUND_COG: IconData
    USER_ROUND_GROUP: IconData
    USER_ROUND_KEY: IconData
    USER_ROUND_MINUS: IconData
    USER_ROUND_PEN: IconData
    USER_ROUND_PLUS: IconData
    USER_ROUND_SEARCH: IconData
    USER_ROUND_X: IconData
    USER_SEARCH: IconData
    USER_SHIELD: IconData
    USER_SQUARE: IconData
    USER_SQUARE_2: IconData
    USER_STAR: IconData
    USER_X: IconData
    USER_X_2: IconData
    USERS: IconData
    USERS_2: IconData
    USERS_ROUND: IconData
    UTENSILS: IconData
    UTENSILS_CROSSED: IconData
    UTILITY_POLE: IconData
    VAN: IconData
    VARIABLE: IconData
    VAULT: IconData
    VECTOR_POLYGON: IconData
    VECTOR_SQUARE: IconData
    VEGAN: IconData
    VENETIAN_MASK: IconData
    VENUS: IconData
    VENUS_AND_MARS: IconData
    VERIFIED: IconData
    VIBRATE: IconData
    VIBRATE_OFF: IconData
    VIDEO: IconData
    VIDEO_OFF: IconData
    VIDEOTAPE: IconData
    VIEW: IconData
    VIRUS: IconData
    VIRUS_OFF: IconData
    VOICEMAIL: IconData
    VOLLEYBALL: IconData
    VOLUME: IconData
    VOLUME_1: IconData
    VOLUME_2: IconData
    VOLUME_OFF: IconData
    VOLUME_X: IconData
    VOTE: IconData
    WALLET: IconData
    WALLET_2: IconData
    WALLET_CARDS: IconData
    WALLET_MINIMAL: IconData
    WALLPAPER: IconData
    WAND: IconData
    WAND_2: IconData
    WAND_SPARKLES: IconData
    WAREHOUSE: IconData
    WASHING_MACHINE: IconData
    WATCH: IconData
    WAVES: IconData
    WAVES_ARROW_DOWN: IconData
    WAVES_ARROW_UP: IconData
    WAVES_HORIZONTAL: IconData
    WAVES_LADDER: IconData
    WAVES_VERTICAL: IconData
    WAYPOINTS: IconData
    WEBCAM: IconData
    WEBCAM_OFF: IconData
    WEBHOOK: IconData
    WEBHOOK_OFF: IconData
    WEIGHT: IconData
    WEIGHT_TILDE: IconData
    WHEAT: IconData
    WHEAT_OFF: IconData
    WHISTLE: IconData
    WHOLE_WORD: IconData
    WIFI: IconData
    WIFI_COG: IconData
    WIFI_HIGH: IconData
    WIFI_LOW: IconData
    WIFI_OFF: IconData
    WIFI_PEN: IconData
    WIFI_SYNC: IconData
    WIFI_ZERO: IconData
    WIND: IconData
    WIND_ARROW_DOWN: IconData
    WINE: IconData
    WINE_OFF: IconData
    WORKFLOW: IconData
    WORM: IconData
    WRAP_TEXT: IconData
    WRENCH: IconData
    WRENCH_OFF: IconData
    X: IconData
    X_CIRCLE: IconData
    X_LINE_TOP: IconData
    X_OCTAGON: IconData
    X_SQUARE: IconData
    ZAP: IconData
    ZAP_OFF: IconData
    ZODIAC_AQUARIUS: IconData
    ZODIAC_ARIES: IconData
    ZODIAC_CANCER: IconData
    ZODIAC_CAPRICORN: IconData
    ZODIAC_GEMINI: IconData
    ZODIAC_LEO: IconData
    ZODIAC_LIBRA: IconData
    ZODIAC_OPHIUCHUS: IconData
    ZODIAC_PISCES: IconData
    ZODIAC_SAGITTARIUS: IconData
    ZODIAC_SCORPIO: IconData
    ZODIAC_TAURUS: IconData
    ZODIAC_VIRGO: IconData
    ZOOM_IN: IconData
    ZOOM_OUT: IconData
