name: Documentation update
about: Found some unclear, missing or outdated documentation?
title: "docs: "
labels: ["documentation"]

body:
  - type: textarea
    id: "description"
    attributes:
      label: "Description"
      description: "Is something unclear, missing or outdated in our documentation?"
      placeholder: Tell us what feature you want...
    validations:
      required: true

  - type: textarea
    id: "link"
    attributes:
      label: "Relevant documentation sections"
      description: "Add a link to the relevant section of our documentation, or any addition context."
      placeholder: https://docs.flet.dev/...
    validations:
      required: false

  - type: textarea
    id: "code-snippet"
    attributes:
      label: "Relevant code snippets"
      description: "If the documentation issue is related to code, please provide relevant code snippets here."
      value: |
        <details open><summary>Code</summary>

        ```python
        [Paste your code here]
        ```

        </details>
    validations:
      required: false
