# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  before_all do
    setup_ci
  end

  desc "Run build"
  lane :build do
    Dir.chdir "../.." do
      sh("flutter", "packages", "get")
      sh("flutter", "clean")
      sh("flutter", "build", "ios", "--release", "--no-codesign")
    end

    match(type: "development")
    match(type: "adhoc")

    gym(
      export_method: "ad-hoc",
      output_name: "flet.ipa",
      xcargs: "-allowProvisioningUpdates",
      export_options: {
        provisioningProfiles: { 
          "com.appveyor.flet" => "match AdHoc com.appveyor.flet"
        }
      }
    )
  end
end
