# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  before_all do
    setup_ci

    match(type: "development")
    match(type: "adhoc")
    match(type: "appstore")
  end

  desc "Build Flutter without codesign"
  lane :build_flutter do
    increment_version_number(
      version_number: "$FLET_PACKAGE_VERSION"
    )

    Dir.chdir "../.." do
      sh("flutter", "packages", "get")
      sh("flutter", "clean")
      sh("flutter", "build", "ios", "--release", "--no-codesign")
    end   
  end

  desc "Build for internal testing"
  lane :build_ipa do
    build_flutter

    gym(
      export_method: "ad-hoc",
      output_directory: "build",
      output_name: "flet.ipa",
      xcargs: "-allowProvisioningUpdates",
      export_options: {
        provisioningProfiles: { 
          "com.appveyor.flet" => "match AdHoc com.appveyor.flet"
        }
      }
    )
  end

  desc "Upload to App Store"
  lane :upload_appstore do
    build_flutter

    gym(
      export_method: "app-store",
      output_directory: "build",
      output_name: "flet.ipa",
      xcargs: "-allowProvisioningUpdates",
      export_options: {
        provisioningProfiles: { 
          "com.appveyor.flet" => "match AppStore com.appveyor.flet"
        }
      }
    )

    app_store_connect_api_key
    deliver(
      skip_screenshots: true,
      skip_metadata: true,
      run_precheck_before_submit: false,
      submit_for_review: false,
      force: true
    )    
  end
end
