# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  before_all do
    setup_ci

    match(type: "development")
    match(type: "adhoc")
    match(type: "appstore")
  end

  desc "Build Flutter without codesign"
  lane :build_flutter do
    Dir.chdir "../.." do
      sh("flutter", "packages", "get")
      sh("flutter", "clean")
      sh("flutter", "build", "ios", "--release", "--no-codesign")
    end

    increment_build_number(
      build_number: "$APPVEYOR_BUILD_NUMBER"
    )      
  end

  desc "Build for Ad-hoc"
  lane :build_adhoc do
    gym(
      export_method: "ad-hoc",
      output_directory: "build/ad-hoc"
      output_name: "flet.ipa",
      xcargs: "-allowProvisioningUpdates",
      export_options: {
        provisioningProfiles: { 
          "com.appveyor.flet" => "match AdHoc com.appveyor.flet"
        }
      }
    )
  end

  desc "Build for App Store"
  lane :build_appstore do
    gym(
      export_method: "appstore",
      output_directory: "build/appstore"
      output_name: "flet.ipa",
      xcargs: "-allowProvisioningUpdates",
      export_options: {
        provisioningProfiles: { 
          "com.appveyor.flet" => "match AppStore com.appveyor.flet"
        }
      }
    )
  end

  desc "Run build"
  lane :build do
    build_flutter
    build_adhoc
    build_appstore
  end
end
