project_name: fletd

builds:
  - id: fletd
    main: cmd/fletd/main.go
    binary: fletd
    env:
      - CGO_ENABLED=0
    flags:
      - -tags=release
    ldflags:
      - -s -w -X github.com/flet-dev/flet/server/commands.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm64
      - arm
    goarm:
      - 7
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: linux
        goarch: 386
      - goos: darwin
        goarch: 386

# dockers:
#   - ids:
#       - fletd

#     goos: linux
#     goarch: amd64
#     goarm: ""

#     image_templates:
#       - "flet-dev/fletd:latest"
#       - "flet-dev/fletd:{{ .Version }}"
#       #- "us.gcr.io/flet-app/flet-server:{{ .Version }}"

#     skip_push: true
#     dockerfile: Dockerfile
#     use: buildx

#     # Template of the docker build flags.
#     build_flag_templates:
#       - "--pull"
#       - "--label=org.opencontainers.image.created={{.Date}}"
#       - "--label=org.opencontainers.image.title={{.ProjectName}}"
#       - "--label=org.opencontainers.image.revision={{.FullCommit}}"
#       - "--label=org.opencontainers.image.version={{.Version}}"
#       #- "--build-arg=FOO={{.Env.Bar}}"
#       - "--platform=linux/amd64"

archives:
  - id: fletd-binaries
    builds:
      - fletd
    format: binary
    name_template: "fletd-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
  - id: fletd-tars
    builds:
      - fletd
    name_template: "fletd-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

release:
  prerelease: auto
