"""MkDocs navigation to Docusaurus sidebar generation."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

try:
    import yaml
except ModuleNotFoundError:  # pragma: no cover
    yaml = None


def _doc_id_for_output_path(output_path: str) -> str:
    return output_path.removesuffix(".md").removesuffix(".mdx")


def _load_nav(mkdocs_yml: Path) -> list[Any]:
    if yaml is None:  # pragma: no cover
        raise RuntimeError(
            "PyYAML is required to parse mkdocs.yml. Install CrocoDocs dependencies first."
        )
    text = mkdocs_yml.read_text(encoding="utf-8")
    marker = "\nnav:\n"
    if marker in text:
        text = text[text.index(marker) + 1 :]
    elif text.startswith("nav:\n"):
        text = text
    else:
        raise ValueError(f"Could not find 'nav:' section in {mkdocs_yml}")
    data = yaml.safe_load(text) or {}
    nav = data.get("nav")
    if not isinstance(nav, list):
        raise ValueError(f"Expected 'nav' list in {mkdocs_yml}")
    return nav


def _normalize_label(value: str) -> str:
    return value.strip().lower()


def _collect_nav_titles(entries: list[Any], out: dict[str, str]) -> None:
    for entry in entries:
        if isinstance(entry, str):
            continue
        if not isinstance(entry, dict) or len(entry) != 1:
            continue
        label, value = next(iter(entry.items()))
        if isinstance(value, str):
            out[value] = label
            continue
        if isinstance(value, list):
            _collect_nav_titles(value, out)


def _doc_item(
    label: str, source_path: str, page_by_source: dict[str, dict[str, Any]]
) -> dict[str, Any]:
    page = page_by_source.get(source_path)
    if page is None:
        raise KeyError(f"Navigation source path not found in manifest: {source_path}")
    item: dict[str, Any] = {
        "type": "doc",
        "id": _doc_id_for_output_path(page["output_path"]),
    }
    if label and label != page.get("title"):
        item["label"] = label
    return item


def _should_use_category_link(
    category_label: str, first_item: dict[str, Any], first_source_path: str | None
) -> bool:
    if first_item.get("type") != "doc":
        return False
    item_label = _normalize_label(first_item.get("label") or "")
    category_name = _normalize_label(category_label)
    if item_label in {"overview", category_name}:
        return True
    return bool(first_source_path and first_source_path.endswith("/index.md"))


def _convert_nav_entry(
    entry: Any,
    page_by_source: dict[str, dict[str, Any]],
) -> tuple[dict[str, Any], str | None]:
    if isinstance(entry, str):
        return _doc_item("", entry, page_by_source), entry

    if not isinstance(entry, dict) or len(entry) != 1:
        raise ValueError(f"Unsupported nav entry: {entry!r}")

    label, value = next(iter(entry.items()))
    if isinstance(value, str):
        return _doc_item(label, value, page_by_source), value

    if not isinstance(value, list):
        raise ValueError(f"Unsupported nav group for {label!r}: {value!r}")

    converted_children: list[dict[str, Any]] = []
    child_sources: list[str | None] = []
    for child in value:
        converted, source_path = _convert_nav_entry(child, page_by_source)
        converted_children.append(converted)
        child_sources.append(source_path)

    category: dict[str, Any] = {
        "type": "category",
        "label": label,
        "collapsed": True,
        "items": converted_children,
    }
    if converted_children and _should_use_category_link(
        label, converted_children[0], child_sources[0]
    ):
        category["link"] = {
            "type": "doc",
            "id": converted_children[0]["id"],
        }
        category["items"] = converted_children[1:]
    return category, None


def build_sidebar_items(
    mkdocs_yml: Path,
    pages: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    page_by_source = {page["source_path"]: page for page in pages}
    items: list[dict[str, Any]] = []
    for entry in _load_nav(mkdocs_yml):
        converted, _ = _convert_nav_entry(entry, page_by_source)
        items.append(converted)
    return items


def build_nav_title_map(mkdocs_yml: Path) -> dict[str, str]:
    titles: dict[str, str] = {}
    _collect_nav_titles(_load_nav(mkdocs_yml), titles)
    return titles


def render_sidebars_js(sidebar_items: list[dict[str, Any]]) -> str:
    payload = json.dumps({"docs": sidebar_items}, indent=2)
    return (
        "// Generated by CrocoDocs from sdk/python/packages/flet/mkdocs.yml.\n"
        "// Do not edit by hand.\n\n"
        f"module.exports = {payload};\n"
    )


def write_sidebars_js(
    mkdocs_yml: Path,
    pages: list[dict[str, Any]],
    output_path: Path,
) -> None:
    sidebar_items = build_sidebar_items(mkdocs_yml, pages)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_sidebars_js(sidebar_items), encoding="utf-8")
