name: flet_dropzone
description: Flet Drop Zone control
homepage: https://flet.dev
repository: https://github.com/flet-dev/flet/packages/flet_dropzone
version: 0.26.0

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.16.0
  desktop_drop: ^0.5.0

  flet:
    path: ../flet/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0