paths: src
badge: ./docs/assets/badges/docs-coverage.svg
skip_magic: true  # Ignore __*__ methods except __init__
skip_init: true   # Also ignore __init__
skip_file_doc: True
skip_private: False
ignore_patterns: # Dict with key/value pairs of file-pattern/node-pattern
  .*:
    - before_update  # Ignore framework lifecycle hook in all files
    - init           # Ignore init hook in all classes; documented on BaseControl
    - _migrate_state # Ignore state migration hook in all classes; documented on BaseControl
fail_under: 40
