# Project information
site_name: "flet"
site_url: https://docs.flet.dev/
site_author: Flet
site_description: Build multi-platform Python apps powered by Flutter.

# Repository
edit_uri: edit/docs/sdk/python/packages/flet/docs
repo_name: flet-dev/flet
repo_url: https://github.com/flet-dev/flet

# Copyright
copyright: Copyright &copy; 2025 Flet

# Theme
theme:
  name: "material"
  favicon: 'images/favicon.ico'
  logo: 'images/logo.svg'
  icon:
    annotation: material/plus-circle
  palette:
    - scheme: default
      primary: indigo
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
    - scheme: slate
      primary: indigo
      accent: pink
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
  features:
    - content.action.edit
    - content.action.view
    - content.action.annotate
    - content.action.copy
    - content.tooltips
    - content.action.tooltips
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.footer
    - navigation.top
    - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/flet-dev
    - icon: fontawesome/brands/discord
      link: https://discord.gg/bCFXYgZR3b
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/fletdev
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/fletdev.bsky.social

# Navigation
nav:
  - Getting Started:
      - Overview: index.md
      - Installation: getting-started/installation.md
      - Creating a new Flet app: getting-started/create-flet-app.md
      - Running a Flet app (Hot Reload): getting-started/running-app.md
      - Testing on Android: getting-started/testing-on-android.md
      - Testing on iOS: getting-started/testing-on-ios.md
      - Navigation and Routing: getting-started/navigation-and-routing.md
      - Flet Controls: getting-started/flet-controls.md
      - Custom Controls: getting-started/custom-controls.md
      - Adaptive apps: getting-started/adaptive-apps.md
      - Async apps: getting-started/async-apps.md
      - Changelog: getting-started/changelog.md
      - License: getting-started/license.md
  - API Reference:
      - Controls:
          - controls/overview.md
          - Control: controls/control.md
          - ConstrainedControl: controls/constrainedcontrol.md
          - Animations:
              - AnimatedSwitcher: controls/animatedswitcher.md
          - Buttons:
              - CupertinoActionSheetAction: controls/cupertinoactionsheetaction.md
              - CupertinoButton: controls/cupertinobutton.md
              - CupertinoContextmenuaction: controls/cupertinocontextmenuaction.md
              - CupertinoDialogaction: controls/cupertinodialogaction.md
              - CupertinoFilledButton: controls/cupertinofilledbutton.md
              - CupertinoSegmentedButton: controls/cupertinosegmentedbutton.md
              - CupertinoSlidingsegmentedButton: controls/cupertinoslidingsegmentedbutton.md
              - ElevatedButton: controls/elevatedbutton.md
              - FilledButton: controls/filledbutton.md
              - FilledTonalButton: controls/filledtonalbutton.md
              - FloatingActionButton: controls/floatingactionbutton.md
              - IconButton: controls/iconbutton.md
              - MenuitemButton: controls/menuitembutton.md
              - OutlinedButton: controls/outlinedbutton.md
              - PopupMenuButton: controls/popupmenubutton.md
              - SegmentedButton: controls/segmentedbutton.md
              - SubmenuButton: controls/submenubutton.md
              - TextButton: controls/textbutton.md
          - Dialogs, Alerts and Panels:
              - AlertDialog: controls/alertdialog.md
              - Banner: controls/banner.md
              - Bottomsheet: controls/bottomsheet.md
              - CupertinoActionSheet: controls/cupertinoactionsheet.md
              - CupertinoAlertDialog: controls/cupertinoalertdialog.md
              - CupertinoBottomSheet: controls/cupertinobottomsheet.md
              - CupertinoContextMenu: controls/cupertinocontextmenu.md
              - CupertinoDatePicker: controls/cupertinodatepicker.md
              - CupertinoPicker: controls/cupertinopicker.md
              - CupertinoTimerPicker: controls/cupertinotimerpicker.md
              - DatePicker: controls/datepicker.md
              - SnackBar: controls/snackbar.md
              - TimePicker: controls/timepicker.md
          - Information Displays:
              - Canvas: controls/canvas.md
              - Circleavatar: controls/circleavatar.md
              - Cupertinoactivityindicator: controls/cupertinoactivityindicator.md
              - Icon: controls/icon.md
              - Image: controls/image.md
              - Markdown: controls/markdown.md
              - Text: controls/text.md
              - Progressbar: controls/progressbar.md
              - Progressring: controls/progressring.md
          - Inputs and Selections:
              - AutoComplete: controls/autocomplete.md
              - AutofillGroup: controls/autofillgroup.md
              - Checkbox: controls/checkbox.md
              - Chip: controls/chip.md
              - CupertinoCheckbox: controls/cupertinocheckbox.md
              - CupertinoRadio: controls/cupertinoradio.md
              - CupertinoSlider: controls/cupertinoslider.md
              - CupertinoSwitch: controls/cupertinoswitch.md
              - CupertinoTextfield: controls/cupertinotextfield.md
              - Dropdown: controls/dropdown.md
              - DropdownM2: controls/dropdownm2.md
              - Radio: controls/radio.md
              - RangeSlider: controls/rangeslider.md
              - SearchBar: controls/searchbar.md
              - Slider: controls/slider.md
              - Switch: controls/switch.md
              - Textfield: controls/textfield.md
          - Layout:
              - Card: controls/card.md
              - Column: controls/column.md
              - Container: controls/container.md
              - Cupertinolisttile: controls/cupertinolisttile.md
              - Datatable: controls/datatable.md
              - Dismissible: controls/dismissible.md
              - Divider: controls/divider.md
              - Expansionpanel: controls/expansionpanel.md
              - Expansiontile: controls/expansiontile.md
              - Gridview: controls/gridview.md
              - Listtile: controls/listtile.md
              - Listview: controls/listview.md
              - Page: controls/page.md
              - Pagelet: controls/pagelet.md
              - Placeholder: controls/placeholder.md
              - Reorderablelistview: controls/reorderablelistview.md
              - Responsiverow: controls/responsiverow.md
              - Row: controls/row.md
              - Safearea: controls/safearea.md
              - Stack: controls/stack.md
              - Tabs: controls/tabs.md
              - Verticaldivider: controls/verticaldivider.md
              - View: controls/view.md
          - Navigation:
              - AppBar: controls/appbar.md
              - bottomappbar: controls/bottomappbar.md
              - cupertinoappbar: controls/cupertinoappbar.md
              - cupertinonavigationbar: controls/cupertinonavigationbar.md
              - menubar: controls/menubar.md
              - navigationbar: controls/navigationbar.md
              - navigationdrawer: controls/navigationdrawer.md
              - navigationrail: controls/navigationrail.md
  - Publish:
      - publish/overview.md
      - Android: publish/android.md
      - iOS: publish/ios
      - Linux: publish/linux
      - macOS: publish/macos
      - Web:
          - publish/web/index.md
          - Dynamic Website:
              - publish/web/dynamic-website/index.md
              - Hosting:
                  - publish/web/dynamic-website/hosting/index.md
                  - Fly.io: publish/web/dynamic-website/hosting/fly-io.md
                  - Replit: publish/web/dynamic-website/hosting/replit.md
                  - Self-Hosting: publish/web/dynamic-website/hosting/self-hosting.md
          - Static Website:
              - publish/web/static-website/index.md
              - Hosting:
                  - Cloudflare: publish/web/static-website/hosting/cloudflare.md
      - Windows: publish/windows
  - Cookbook:
      - Accessibility: cookbook/accessibility.md
      - Animations: cookbook/animations.md
      - Assets: cookbook/assets.md
      - Authentication: cookbook/authentication.md
      - Client Storage: cookbook/client-storage.md
      - Control Refs: cookbook/control-refs.md
      - Drag and Drop: cookbook/drag-and-drop.md
      - Encrypting sensitive data: cookbook/encrypting-sensitive-data.md
      - File picker: cookbook/file-picker.md
      - Fonts: cookbook/fonts.md
      - Keyboard Shortcuts: cookbook/keyboard-shortcuts.md
      - Large Lists: cookbook/large-lists.md
      - Logging: cookbook/logging.md
      - PubSub: cookbook/pubsub.md
      - Read and Write Files: cookbook/read-and-write-files.md
      - Session Storage: cookbook/session-storage.md
      - Theming: cookbook/theming.md
  - Tutorials:
      - Calculator: tutorials/calculator.md
      - Chat: tutorials/chat.md
      - Solitaire: tutorials/solitaire.md
      - ToDo: tutorials/todo.md
      - Trolli: tutorials/trolli.md

# Validation
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn

# Watch
watch:
  - docs
  - src
  - ../../../../CHANGELOG.md
  - ../../../../LICENSE

# Plugins
plugins:
  # - footnotes
  - search:
      lang: en
  - mike:
      alias_type: symlink
  - glightbox:
      background: none
  # - section-index
  - markdown-exec
  - mkdocstrings:
      default_handler: python_xref
      handlers:
        python_xref:
          options:
            relative_crossrefs: true
            docstring_style: google
            show_signature_annotations: true
            signature_crossrefs: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_root_heading: true
            show_root_full_path: false
            show_bases: true
            show_source: false
            group_by_category: true
            show_category_heading: false
            show_labels: false
            show_if_no_docstring: true
            docstring_section_style: spacy
            inherited_members: true
            filters:
              - "!^_"   # Exclude private members starting with only one underscore
              - "!before_update"
              - "!before_event"
              - "!clean"
              - "!did_mount"
              - "!init"
              - "!is_isolated"
              - "!update"
              - "!will_unmount"
            extensions:
              - griffe_modernized_annotations
          inventories:
            - url: https://docs.python.org/3/objects.inv
              domains: [ py, std ]
            - url: https://typing-extensions.readthedocs.io/en/latest/objects.inv

# Markdown Extensions
markdown_extensions:
  - abbr
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: "#"

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: python
          class: python
          validator: !!python/name:markdown_exec.validator
          format: !!python/name:markdown_exec.formatter
  - pymdownx.snippets:
      restrict_base_path: False
      url_download: True
  - pymdownx.magiclink:
      repo_url_shorthand: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.blocks.caption
  - pymdownx.blocks.admonition
  - pymdownx.blocks.details
  - pymdownx.blocks.tab:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  # - meta