from flet_runtime.auth.providers.auth0_oauth_provider import Auth0OAuthProvider
from flet_runtime.auth.providers.azure_oauth_provider import AzureOAuthProvider
from flet_runtime.auth.providers.github_oauth_provider import GitHubOAuthProvider
from flet_runtime.auth.providers.google_oauth_provider import GoogleOAuthProvider
