name: flet_integration_test
description: Internal utilities for driving Flet Flutter integration tests.
publish_to: none
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flet:
    path: ../flet
  integration_test:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
