[project]
name = "flet-desktop"
version = "0.1.0"
description = "Flet Desktop client in Flutter"
authors = [{name = "Appveyor Systems Inc.", email ="hello@flet.dev"}]
license = "Apache-2.0"
readme = "README.md"
requires-python = ">=3.9"

[tool.poetry]
packages = [
    { include = "flet_desktop", from = "src" },
]

include = [
    { path = "src/flet_desktop/app/**/*", format = ["sdist", "wheel"] },
]

[tool.poetry.urls]
Homepage = "https://flet.dev"
Repository = "https://github.com/flet-dev/flet"
Documentation = "https://flet.dev/docs"

[tool.poetry.dependencies]
flet = { version = "0.1.0" }

[tool.poetry.group.dev.dependencies]
pre-commit = "^2.6"
pytest = "^7.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
float_to_top = true