name: Build docs

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Enable Corepack
        run: corepack enable

      - name: Setup uv
        uses: astral-sh/setup-uv@v8.2.0

      - name: Build website
        run: |
          cd website
          yarn install
          yarn build
