name: flet_local_auth
description: Flet Local Authentication service
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  local_auth: 3.0.2
  local_auth_android: 2.0.9
  local_auth_darwin: 2.0.3
  local_auth_windows: 2.0.1

  flet:
    path: ../../../../../../../packages/flet

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
